# -*- coding: utf-8 -*-
"""Past-paper API validation and real student flows using a disposable SQLite database.

python tests/test_past_papers.py
Uses installed Edge, as the shared browser runtime has no connected browser.
"""
import json, os, subprocess, sys, tempfile, time, urllib.request
from pathlib import Path
from playwright.sync_api import sync_playwright

ROOT=Path(__file__).resolve().parents[1]
BASE='http://localhost:8769'
H={'Content-Type':'application/json','X-Requested-With':'stemcloud'}

def check(name, condition):
    assert condition, name
    print('PASS '+name)

def run():
    with tempfile.TemporaryDirectory() as temp:
        env=dict(os.environ,DB_PATH=str(Path(temp)/'test.db'))
        for k in ('DATABASE_URL','POSTGRES_URL','VERCEL'):env.pop(k,None)
        srv=subprocess.Popen([sys.executable,'-m','uvicorn','index:app','--port','8769','--log-level','warning'],cwd=ROOT/'api',env=env)
        try:
            for _ in range(80):
                try:urllib.request.urlopen(BASE+'/healthz',timeout=1);break
                except Exception:time.sleep(.25)
            with sync_playwright() as pw:
                browser=pw.chromium.launch(channel='msedge',headless=True)
                admin=browser.new_context()
                check('admin setup',admin.request.post(BASE+'/api/signup',headers=H,data=json.dumps(dict(username='ppadmin',password='PastPaper-2468'))).ok)
                for name in ('student_one','student_two'):
                    check('student setup '+name,admin.request.post(BASE+'/api/admin/create-user',headers=H,data=json.dumps(dict(username=name,password='PastPaper-2468'))).ok)
                ctx=browser.new_context(viewport={'width':1280,'height':900})
                ctx.add_init_script("localStorage.setItem('stem_coach_done','1')")
                check('student login',ctx.request.post(BASE+'/api/login',headers=H,data=json.dumps(dict(username='student_one',password='PastPaper-2468'))).ok)
                page=ctx.new_page(); errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
                page.goto(BASE+'/lessons/past-papers.html')
                page.locator('#pp-list button').first.wait_for()
                check('19 physics questions available',page.locator('#pp-list button').count()==19)
                page.locator('.pp-skip').focus();page.keyboard.press('Enter')
                check('skip link focuses question',page.evaluate("document.activeElement.id==='pp-question'"))
                page.locator('#pp-list [aria-current=true]').focus();page.keyboard.press('ArrowDown')
                check('question navigation supports keyboard',page.locator('#pp-list [aria-current=true]').get_attribute('data-q')=='ol2015-i-09')
                page.keyboard.press('ArrowUp');page.keyboard.press('Enter')
                check('bank source provenance',ctx.request.get(BASE+'/lessons/past-papers/2015.json').json()['teacherReviewed'] is False)
                bank=ctx.request.get(BASE+'/lessons/past-papers/2015.json').json()
                check('39 physics written subparts',sum(len(q.get('parts',[])) for q in bank['questions'])==39)
                check('bank contains physics only',bank['scope']=='physics' and all(q['subjects']==['physics'] for q in bank['questions']) and all(p['subject']=='physics' for q in bank['questions'] for p in q.get('parts',[])))
                check('mixed questions omit nonphysics parts and marks',all('marks' not in q for q in bank['questions'] if q.get('physicsSubset')))
                check('no subject selector',page.locator('#pp-subject').count()==0)
                explanations=[item for q in bank['questions'] for item in ([q] if q['type']=='mcq' else q['parts'])]
                check('all 53 answers have bilingual teaching notes',len(explanations)==53 and all(all(item['detailedExplanation'][field].get(lang) for field in ('concept','reasoning','commonMistake') for lang in ('en','ta')) for item in explanations))
                book_refs=[ref for item in explanations for ref in item['references'] if ref['kind']=='textbook']
                check('uploaded textbook coverage is explicit',bank['textbookReferenceStatus']=='verified-with-coverage-gaps' and len(book_refs)==71 and sum(item['textbookReferenceStatus']=='verified' for item in explanations)==39)
                check('printed and PDF pages kept separate',all(ref['verifiedAgainst']=='uploaded-textbook' and ref['url'].endswith('#page='+str(ref['pdfPages'][0])) and ref['sourceSha256'] for ref in book_refs))
                page.locator('[name=pp-choice][value="3"]').check();page.locator('#pp-check').click()
                page.wait_for_function("document.querySelector('#pp-status').textContent.includes('Saved to your account')")
                check('MCQ feedback',page.locator('.pp-feedback').inner_text().startswith('Correct on your last attempt'))
                check('attempt persisted',len(ctx.request.get(BASE+'/api/past-papers/state').json()['attempts'])==1)
                check('detailed reasoning and common mistake visible',page.locator('.pp-teaching').count()==1 and page.locator('.pp-mistake').count()==1)
                page.locator('.pp-similar > summary').click()
                check('similar question answer starts hidden',not page.locator('.pp-similar details p').is_visible())
                page.locator('.pp-similar details summary').click()
                check('similar question answer can be revealed',page.locator('.pp-similar details p').is_visible())
                page.locator('#pp-list [data-q="ol2015-i-29"]').click()
                page.locator('[name=pp-choice][value="3"]').check();page.locator('#pp-check').click()
                check('worked calculations visible',page.locator('.pp-feedback').inner_text().find('36 g')>=0 and 'Worked steps' in page.locator('.pp-feedback').inner_text())
                check('verified grade and chapter link',page.locator('.pp-references a').first.get_attribute('href')=='/lessons/g10-chapter-15-hydrostatic-pressure.html' and 'Grade 10 · Chapter 15' in page.locator('.pp-references a').first.inner_text())
                check('English textbook opens exact PDF page',page.locator('.pp-book-ref').first.get_attribute('href')=='/lessons/textbooks/g10-p2-en.pdf#page=77' and 'printed p. 67' in page.locator('.pp-book-ref').first.inner_text())
                page.locator('#pp-ta').click()
                check('Tamil source appears first with its own page',page.locator('.pp-book-ref').first.get_attribute('href')=='/lessons/textbooks/g10-p2-ta.pdf#page=94' and '84' in page.locator('.pp-book-ref').first.inner_text())
                page.locator('#pp-en').click()
                pdf=ctx.request.get(BASE+'/lessons/textbooks/g10-p2-en.pdf',headers={'Range':'bytes=0-1023'})
                check('textbook PDF served with byte ranges',pdf.status==206 and pdf.headers.get('content-type')=='application/pdf' and pdf.body().startswith(b'%PDF'))
                page.locator('#pp-list [data-q="ol2015-i-05"]').click()
                page.locator('#pp-bookmark').click();page.wait_for_timeout(250)
                page.locator('#pp-review').select_option('saved')
                check('bookmark filter',page.locator('#pp-list button').count()==1)
                page.locator('#pp-clear').click();page.locator('#pp-type').select_option('written')
                page.locator('#pp-answer-0').fill('Transverse waves; particles oscillate perpendicular to travel.')
                page.locator('.pp-solution > summary').first.click()
                check('written model answer includes teaching notes',page.locator('.pp-solution .pp-teaching').first.is_visible())
                page.locator('#pp-save-written').click();page.wait_for_timeout(250)
                page.locator('#pp-ta').click()
                check('Tamil switch preserves written draft',page.locator('#pp-answer-0').input_value().startswith('Transverse waves'))
                check('Tamil question text',any('\u0b80' <= c <= '\u0bff' for c in page.locator('#pp-question').inner_text()))
                page.locator('#pp-en').click()
                page.reload();page.locator('#pp-type').select_option('written');page.locator('#pp-answer-0').wait_for()
                check('draft survives reload',page.locator('#pp-answer-0').input_value().startswith('Transverse waves'))

                removed=dict(id='removed_question_0001',question='ol2015-i-01',mode='practice',choice=0)
                check('biology attempts rejected',ctx.request.post(BASE+'/api/past-papers/attempts',headers=H,data=json.dumps(dict(events=[removed]))).status==400)
                removed.update(question='ol2015-ii-01',answers={'i':'biology answer'},selfCheck=None)
                check('nonphysics written parts rejected',ctx.request.post(BASE+'/api/past-papers/attempts',headers=H,data=json.dumps(dict(events=[removed]))).status==400)

                # Validate server scoring and strict input handling, including idempotent retries.
                event=dict(id='test_event_00000001',question='ol2015-i-09',choice=0,mode='practice',correct=True)
                r=ctx.request.post(BASE+'/api/past-papers/attempts',headers=H,data=json.dumps(dict(events=[event])))
                check('server ignores forged correctness',r.ok and r.json()['attempts'][0]['result']['correct'] is False)
                again=ctx.request.post(BASE+'/api/past-papers/attempts',headers=H,data=json.dumps(dict(events=[event])))
                check('retry uses same recorded timestamp',again.json()['attempts'][0]['at']==r.json()['attempts'][0]['at'])
                event['choice']=2
                check('reused ID cannot replace an attempt',ctx.request.post(BASE+'/api/past-papers/attempts',headers=H,data=json.dumps(dict(events=[event]))).status==409)
                for bad in (True,4,-1,'1'):
                    event.update(id='test_bad_'+str(bad).replace('-','x')+'_000000000',choice=bad)
                    check('invalid choice rejected '+str(bad),ctx.request.post(BASE+'/api/past-papers/attempts',headers=H,data=json.dumps(dict(events=[event]))).status==400)
                check('CSRF header required',ctx.request.put(BASE+'/api/past-papers/bookmark',data=json.dumps(dict(question='ol2015-i-05',saved=True))).status==403)
                other=browser.new_context();other.request.post(BASE+'/api/login',headers=H,data=json.dumps(dict(username='student_two',password='PastPaper-2468')))
                check('other account cannot see attempts',other.request.get(BASE+'/api/past-papers/state').json()=={'attempts':[],'bookmarks':[]})
                anon=browser.new_context()
                check('anonymous API rejected',anon.request.get(BASE+'/api/past-papers/state').status==401)
                check('anonymous bank gated',anon.request.get(BASE+'/lessons/past-papers/2015.json',max_redirects=0).status==401)
                check('anonymous textbook gated',anon.request.get(BASE+'/lessons/textbooks/g10-p2-en.pdf',max_redirects=0).status==401)
                check('past papers do not award XP',not ctx.request.get(BASE+'/api/progress').json()['progress'].get('scx_xp_total'))

                # A second device restores submitted written responses from account storage.
                second=browser.new_context();second.add_init_script("localStorage.setItem('stem_coach_done','1')")
                second.request.post(BASE+'/api/login',headers=H,data=json.dumps(dict(username='student_one',password='PastPaper-2468')))
                sp=second.new_page();sp.goto(BASE+'/lessons/past-papers.html');sp.locator('#pp-list button').first.wait_for()
                sp.wait_for_function("document.querySelector('#pp-status').textContent.includes('Saved to your account')")
                sp.locator('#pp-type').select_option('written')
                check('written response restores on second device',sp.locator('#pp-answer-0').input_value().startswith('Transverse waves'))
                legacy_id=sp.evaluate('window.SCX_USER.id')
                sp.evaluate('''uid=>{localStorage.removeItem('stem_pp_physics_'+uid);localStorage.setItem('stem_pp_'+uid,JSON.stringify({drafts:{'ol2015-ii-01':{touched:true,answers:{'i':'old biology','iv':'saved physics'}},'ol2015-i-01':{choice:0}},events:[],pending:[],bookmarks:['ol2015-i-01','ol2015-i-05'],bookmarkPending:{},exam:{paper:'II',responses:{},selected:['ol2015-ii-02']}}));}''',legacy_id)
                sp.reload();sp.locator('#pp-list button').first.wait_for()
                migrated=sp.evaluate("uid=>JSON.parse(localStorage.getItem('stem_pp_physics_'+uid))",legacy_id)
                check('legacy migration keeps physics draft only',migrated['drafts']['ol2015-ii-01']['answers']=={'iv':'saved physics'} and 'ol2015-i-01' not in migrated['drafts'])
                check('legacy mixed exam is cleared',migrated['exam'] is None)
                check('legacy data remains archived',sp.evaluate("uid=>localStorage.getItem('stem_pp_'+uid)!==null",legacy_id))
                second.close()

                page.locator('#pp-clear').click();page.locator('#pp-exam-i').click();page.locator('#pp-confirm [value=ok]').click()
                page.locator('#pp-exam-bar').wait_for()
                check('paper MCQ hides explanations',page.locator('.pp-feedback').count()==0)
                check('paper MCQ hides teaching and similar answers',page.locator('.pp-teaching,.pp-similar,.pp-references').count()==0)
                page.locator('[name=pp-choice][value="3"]').check()
                page.evaluate("()=>{const key='stem_pp_physics_'+SCX_USER.id;let s=JSON.parse(localStorage.getItem(key));s.exam.deadline=1;localStorage.setItem(key,JSON.stringify(s));}");page.reload();page.locator('#pp-exam-bar').wait_for()
                check('exam responses survive reload',page.locator('[name=pp-choice][value="3"]').is_checked())
                check('legacy deadline cannot auto-submit',page.locator('#pp-clock').count()==0 and page.evaluate("!JSON.parse(localStorage.getItem('stem_pp_physics_'+SCX_USER.id)).exam.deadline"))
                page.locator('#pp-submit').click();page.locator('#pp-confirm [value=ok]').click()
                page.locator('#pp-result').wait_for()
                check('unanswered MCQs score zero', '1/14' in page.locator('#pp-result').inner_text())
                page.wait_for_function("document.querySelector('#pp-status').textContent.includes('Saved to your account')")
                page.locator('#pp-exam-ii').click();page.locator('#pp-confirm [value=ok]').click()
                for qid in ('ol2015-ii-09','ol2015-ii-10'):
                    page.locator('#pp-list [data-q="'+qid+'"]').click()
                    check('no mixed-paper selection controls '+qid,page.locator('#pp-choose').count()==0)
                check('paper written practice contains physics only',page.locator('#pp-list button').count()==5 and page.locator('#pp-choose').count()==0)
                page.locator('#pp-submit').click();page.locator('#pp-confirm [value=ok]').click()
                check('written paper remains ungraded','5 written questions saved' in page.locator('#pp-result').inner_text())
                page.locator('#pp-type').select_option('written')
                check('blank paper submission preserves previous written response',page.locator('#pp-answer-0').input_value().startswith('Transverse waves'))

                # Year-specific practice, source links and account validation.
                counts={2016:16,2017:19,2018:18,2019:17,2020:15,2021:18,2022:16,2023:17}
                page.locator('#pp-clear').click()
                for year,count in counts.items():
                    page.locator('#pp-year').select_option(str(year))
                    check('year bank '+str(year),page.locator('#pp-list button').count()==count)
                    check('year source '+str(year),page.locator('#pp-pdf').get_attribute('href')==f'/lessons/past-papers/{year}/source.pdf')
                    check('new years do not claim official key '+str(year),page.locator('#pp-key').is_hidden())
                    data=ctx.request.get(BASE+f'/lessons/past-papers/{year}.json').json()
                    first=data['questions'][0]
                    result=ctx.request.post(BASE+'/api/past-papers/attempts',headers=H,data=json.dumps({'events':[{'id':'physics-year-check-'+str(year),'question':first['id'],'mode':'practice','choice':first['correct']}]}))
                    check('API accepts new physics ID '+str(year),result.ok and result.json()['attempts'][0]['result']['correct'])
                page.locator('#pp-year').select_option('2023')
                page.locator('#pp-exam-i').click();page.locator('#pp-confirm [value=ok]').click()
                check('2023 practice selects its 13 MCQs only',page.locator('#pp-list button').count()==13)
                page.locator('[name=pp-choice][value="3"]').check()
                page.reload();page.locator('#pp-exam-bar').wait_for()
                check('new year practice persists without deadline',page.locator('#pp-exam-title').inner_text().startswith('2023') and page.locator('[name=pp-choice][value="3"]').is_checked() and page.locator('#pp-clock').count()==0)
                page.locator('#pp-submit').click();page.locator('#pp-confirm [value=ok]').click()
                page.locator('#pp-result').wait_for()
                check('new year practice scores only that year','1/13' in page.locator('#pp-result').inner_text())
                page.locator('#pp-year').select_option('2020')
                check('missing source coverage explained','missing' in page.locator('#pp-note').text_content())
                check('coverage visible outside collapsed notice',page.locator('#pp-coverage').is_visible())
                page.locator('#pp-ta').click()
                check('coverage translates to Tamil','PDF' in page.locator('#pp-coverage').inner_text() and 'பக்கங்கள்' in page.locator('#pp-coverage').inner_text())
                page.locator('#pp-en').click()
                page.locator('#pp-year').select_option('2015')
                # Mark a retry offline, then ensure its exact event is replayed once online.
                page.locator('#pp-clear').click()
                page.wait_for_timeout(500);ctx.set_offline(True)
                page.locator('[name=pp-choice][value="1"]').check();page.locator('#pp-check').click()
                check('offline feedback available',page.locator('.pp-feedback').count()==1)
                page.wait_for_function("document.querySelector('#pp-status').textContent.includes('sync is pending')")
                ctx.set_offline(False);page.locator('#pp-status button').click()
                page.wait_for_function("document.querySelector('#pp-status').textContent.includes('Saved to your account')")
                check('offline attempt synced',ctx.request.get(BASE+'/api/past-papers/state').json()['attempts'][-1]['result']['choice']==1)
                # Reload once under service-worker control, then reopen the bank offline.
                page.wait_for_function('navigator.serviceWorker.controller !== null')
                page.reload();page.locator('#pp-list button').first.wait_for()
                page.locator('#pp-list [data-q="ol2015-i-28"]').click()
                page.locator('figure img').wait_for()
                page.wait_for_function("document.querySelector('figure img').naturalWidth>0")
                page.wait_for_function("caches.keys().then(async ks=>{let c=await caches.open(ks.find(k=>k.includes('pages')));return !!(await c.match('/lessons/past-papers/2015.json')) && !!(await c.match('/lessons/past-papers/catalog.json')) && !!(await c.match('/lessons/past-papers/2015/mcq-28.jpg'));})")
                ctx.set_offline(True);page.reload();page.locator('#pp-list button').first.wait_for()
                check('cached question bank reopens offline',page.locator('#pp-list button').count()==19)
                page.locator('#pp-list [data-q="ol2015-i-28"]').click()
                page.wait_for_function("document.querySelector('figure img').naturalWidth>0")
                check('visited diagram reopens offline',page.locator('figure img').is_visible())
                ctx.set_offline(False);page.reload();page.locator('#pp-list button').first.wait_for()
                check('other year result stays hidden after reload',page.locator('#pp-result').is_hidden())
                # Return to unfiltered view for layout checks.
                page.set_viewport_size({'width':375,'height':812})
                page.locator('#pp-filter-panel summary').click()
                check('mobile has no horizontal overflow',page.evaluate('document.documentElement.scrollWidth<=innerWidth+1'))
                page.locator('#pp-ta').click()
                check('Tamil mobile has no overflow',page.evaluate('document.documentElement.scrollWidth<=innerWidth+1'))
                out=ROOT/'tmp'/'past-papers-qa';out.mkdir(parents=True,exist_ok=True)
                page.screenshot(path=str(out/'mobile-tamil.png'),full_page=True)
                page.locator('#pp-en').click();page.set_viewport_size({'width':1280,'height':900})
                page.screenshot(path=str(out/'desktop.png'),full_page=True)
                page.locator('#pp-list [data-q="ol2015-i-29"]').click()
                page.screenshot(path=str(out/'textbook-references.png'),full_page=True)
                page.set_viewport_size({'width':375,'height':812});page.locator('#pp-ta').click()
                check('Tamil textbook references have no mobile overflow',page.evaluate('document.documentElement.scrollWidth<=innerWidth+1'))
                page.screenshot(path=str(out/'textbook-references-tamil.png'),full_page=True)
                page.locator('#pp-en').click();page.set_viewport_size({'width':1280,'height':900})
                check('no browser script errors',not errors)
                page.goto(BASE+'/lessons/g11-chapter-04-waves.html')
                check('lesson topic practice link',page.locator('#stem-past-link').get_attribute('href').endswith('?lesson=g11-chapter-04-waves'))
                page.goto(BASE+page.locator('#stem-past-link').get_attribute('href'));page.locator('#pp-list button').first.wait_for()
                check('lesson filter applied',0<page.locator('#pp-list button').count()<19)
                browser.close()
        finally:
            srv.terminate();srv.wait(timeout=10)

if __name__=='__main__':run()
