from expanded_physics import mc,written

def add():
    y=2018
    mc(y,2,1,'units','Express the SI unit of force in base units.','விசையின் SI அலகை அடிப்படை அலகுகளில் எழுதுக.',['kg m s⁻¹','kg m⁻¹ s⁻¹','kg m s⁻²','kg m⁻² s⁻²'],3,'F = ma: kg × m s⁻² = kg m s⁻².','F = ma: kg × m s⁻² = kg m s⁻².')
    mc(y,4,1,'transformer','Which claim about a transformer is false?','நிலைமாற்றி பற்றிய பொய்யான கூற்று எது?', [('Can step voltage up','வோல்ற்றளவை உயர்த்தலாம்'),('Can act as an amplifier','விரிவாக்கியாக இயங்கலாம்'),('Can step current up','மின்னோட்டத்தை உயர்த்தலாம்'),('Can step voltage down','வோல்ற்றளவைக் குறைக்கலாம்')],2,'A transformer exchanges voltage for current without increasing power. It cannot amplify power like an active electronic amplifier.','நிலைமாற்றி வலுவை அதிகரிக்காமல் வோல்ற்றளவையும் மின்னோட்டத்தையும் மாற்றும். செயற்படும் இலத்திரனியல் விரிவாக்கிபோல் வலுவை விரிவாக்காது.')
    mc(y,5,1,'forces','Three forces keep an object in equilibrium. Which condition must hold?','மூன்று விசைகளின்கீழ் பொருள் சமநிலையில் உள்ளது. அவசியமான நிபந்தனை எது?', [('Resultant of two equals third in same direction','இரண்டின் விளையுள் மூன்றாவதுடன் ஒரே திசை'),('Resultant is nonzero','விளையுள் பூச்சியமல்ல'),('All three have equal magnitude','மூன்றின் பருமனும் சமம்'),('Their lines of action are concurrent','செயற்கோடுகள் ஒரு புள்ளியில் சந்திக்கும்')],4,'For three nonparallel forces in equilibrium, their lines of action meet at one point and their vector sum is zero. The resultant of two is opposite to the third, not in the same direction.','சமநிலையிலுள்ள மூன்று சமாந்தரமற்ற விசைகளின் செயற்கோடுகள் ஒரு புள்ளியில் சந்திக்கும்; துணிக்கணியக் கூட்டுத்தொகை பூச்சியம். இரண்டின் விளையுள் மூன்றாவதற்கு எதிர்த்திசையில் இருக்கும்.')
    mc(y,8,1,'induction','Which device works on electromagnetic induction?','மின்காந்தத் தூண்டல் தத்துவத்தில் இயங்கும் சாதனம் எது?', [('DC motor','நேரோட்ட மோட்டர்'),('Loudspeaker','ஒலிபெருக்கி'),('Electric bell','மின் மணி'),('Moving-coil microphone','அசையும் சுருள் நுணுக்குப்பன்னி')],4,'Sound moves the microphone coil in a magnetic field; changing flux induces an electrical signal. A loudspeaker uses the reverse conversion through the motor effect.','ஒலி காந்தப் புலத்தில் நுணுக்குப்பன்னிச் சுருளை அசைக்கும்; மாறும் பாயம் மின் சைகையைத் தூண்டும். ஒலிபெருக்கி மோட்டர் விளைவால் எதிர் மாற்றத்தைச் செய்யும்.')
    mc(y,12,2,'buoyancy','A wooden block floats partly submerged. Which statement is true?','மரக்குற்றி பகுதியாக அமிழ்ந்து மிதக்கிறது. உண்மையான கூற்று எது?', [('Displaced liquid mass equals total block mass','இடம்பெயர்த்த திரவத் திணிவு முழுக் குற்றித் திணிவிற்குச் சமம்'),('Equals submerged block mass','அமிழ்ந்த குற்றிப் பகுதியின் திணிவிற்குச் சமம்'),('Displaced volume equals total block volume','இடம்பெயர்த்த கனவளவு முழுக் குற்றிக் கனவளவிற்குச் சமம்'),('Block and liquid have equal density','இரண்டின் அடர்த்தியும் சமம்')],1,'Floating equilibrium: buoyancy = weight. ρliquid Vdisplaced g = mblock g, so displaced liquid mass equals the entire block’s mass.','மிதக்கும் சமநிலையில் மேலுதைப்பு = நிறை. ρதிரவம் Vஇடப்பெயர்ச்சி g = mகுற்றி g; இடம்பெயர்ந்த திரவத் திணிவு முழுக் குற்றித் திணிவிற்குச் சமம்.')
    mc(y,15,2,'capacitor','A capacitor smooths a full-wave rectifier output. Which graph matches the voltage?','முழு அலைச் சீராக்கியின் வெளியீட்டைக் கொள்ளளவி ஒப்பமாக்குகிறது. பொருத்தமான வரைபு எது?', [('Zero voltage','பூச்சிய வோல்ற்றளவு'),('Unsmoothed full-wave pulses','ஒப்பமாக்காத முழு அலைத் துடிப்புகள்'),('Half-wave pulses','அரை அலைத் துடிப்புகள்'),('Nearly steady positive voltage with ripple','சிறிய அலைவுடன் ஏறத்தாழ மாறா நேர் வோல்ற்றளவு')],4,'The capacitor charges near voltage peaks and supplies charge between peaks. Output stays positive with a small ripple rather than dropping to zero each cycle.','கொள்ளளவி உச்சங்களில் ஏற்றம்பெற்று இடையில் ஏற்றத்தை வழங்கும். ஒவ்வொரு சுற்றிலும் பூச்சியமாகாமல் சிறிய அலைவுடன் நேர் வெளியீடு இருக்கும்.',(.09,.458,.86,.585))
    mc(y,25,3,'lenses','Beam a is parallel, b converges and c diverges. Which source statement is correct?','a சமாந்தரம், b குவிகிறது, c விரிகிறது. மூலக் கூற்றுகளில் சரியானது எது?', [('Convex lens changes a into b','குவிவு வில்லை a ஐ b ஆக்கும்'),('Concave lens changes a into b','குழிவு வில்லை a ஐ b ஆக்கும்'),('Concave lens changes b into a','குழிவு வில்லை b ஐ a ஆக்கும்'),('Concave lens changes a into c','குழிவு வில்லை a ஐ c ஆக்கும்')],1,'The source asks for the correctly stated conversion: a convex lens converges a parallel beam (a → b). A concave lens diverges parallel rays. Use the original wording: its option 4 says a convex lens changes a into c, which is false.','மூலக் கூற்றில் குவிவு வில்லை சமாந்தர a கற்றையை குவியும் b கற்றையாக்கும். குழிவு வில்லை சமாந்தரக் கதிர்களை விரிக்கும். மூலத் தெரிவு 4 இல் குவிவு வில்லை a ஐ c ஆக்கும் எனக் கூறுவது பொய்.',(.10,.752,.89,.977))
    from expanded_physics import DATA,bi
    DATA[y][-1]['options'][3]=bi('Convex lens changes a into c','குவிவு வில்லை a ஐ c ஆக்கும்')
    mc(y,26,4,'lenses','Where is an object placed when a convex lens is used to read tiny print?','சிறிய எழுத்துகளை வாசிக்க குவிவு வில்லையைப் பயன்படுத்தும்போது பொருள் எங்கு வைக்கப்படும்?', [('Between lens and focus','வில்லைக்கும் குவியத்திற்கும் இடையில்'),('At focus','குவியத்தில்'),('At twice focal length','இரு குவியத் தூரத்தில்'),('Beyond twice focal length','இரு குவியத் தூரத்திற்கு அப்பால்')],1,'Inside the focal length, the convex lens forms an upright enlarged virtual image, suitable for a magnifier.','குவியத் தூரத்தினுள் குவிவு வில்லை நிமிர்ந்த பெரிய மாயவிம்பத்தை உருவாக்கும்; இது கைவில்லைக்குப் பொருத்தமானது.')
    mc(y,28,4,'gas','A sealed soda bottle is brought from a refrigerator to room temperature. How do gas-space A and liquid B volumes change?','மூடிய சோடா போத்தல் குளிர்சாதனத்திலிருந்து அறை வெப்பநிலைக்குக் கொண்டுவரப்படுகிறது. வாயு A, திரவ B கனவளவுகள் எவ்வாறு மாறும்?', [('Both increase','இரண்டும் அதிகரிக்கும்'),('Both decrease','இரண்டும் குறையும்'),('A increases, B decreases','A அதிகரிக்கும், B குறையும்'),('A decreases, B increases','A குறையும், B அதிகரிக்கும்')],4,'The sealed rigid bottle has approximately fixed total internal volume. Liquid B expands on warming, occupying more space, so the remaining gas space A decreases. Gas pressure rises; it cannot freely expand at constant pressure here.','மூடிய உறுதியான போத்தலின் மொத்த உள் கனவளவு ஏறத்தாழ மாறாது. சூடாகும்போது திரவ B விரிந்து அதிக இடத்தை எடுப்பதால் எஞ்சிய வாயு இடம் A குறையும். வாயு அமுக்கம் உயரும்; இங்கு மாறா அமுக்கத்தில் சுதந்திரமாக விரிய முடியாது.')
    mc(y,31,4,'motion','A small glass ball strikes a larger iron ball at the same speed; only the glass breaks. Which property of the iron ball is larger?','சிறிய கண்ணாடிப் பந்தும் பெரிய இரும்புப் பந்தும் ஒரே கதியில் மோதும்போது கண்ணாடி உடைகிறது. இரும்பில் பெரியதாக இருப்பது எது?', [('Speed','கதி'),('Volume','கனவளவு'),('Momentum','உந்தம்'),('Acceleration','ஆர்முடுகல்')],3,'Momentum p = mv. At the same speed the larger mass has larger momentum; speed itself is equal.','உந்தம் p = mv. சம கதியில் பெரிய திணிவுக்கு பெரிய உந்தம் உண்டு; கதியே சமமாகும்.')
    mc(y,32,4,'pressure','Three different-shaped vessels hold water to the same height above points PA, PB, PC. Compare pressures.','வேறுபட்ட வடிவப் பாத்திரங்களில் PA, PB, PC இற்கு மேலே நீரின் உயரம் சமம். அமுக்கங்களை ஒப்பிடுக.',['PA > PB > PC','PC > PB > PA','PB > PA = PC','PA = PB = PC'],4,'p = ρgh depends on depth and density, not vessel shape or total volume. Same water and same depth give equal pressures.','p = ρgh ஆழத்திலும் அடர்த்தியிலும் தங்கும்; வடிவத்திலும் மொத்தக் கனவளவிலும் அல்ல. அதே நீர், சம ஆழம் என்பதால் அமுக்கங்கள் சமம்.')
    mc(y,35,5,'ohm','A bulb is rated 12 V, 0.5 A. Which claims are true: A current 0.5 A at 12 V; B power 12×0.5 W; C resistance 12/0.5 Ω?','குமிழ் 12 V, 0.5 A. A மின்னோட்டம் 0.5 A; B வலு 12×0.5 W; C தடை 12/0.5 Ω. உண்மையானவை எவை?',['A,B','B,C','A,C','A,B,C'],4,'At its rating, I = 0.5 A, P = VI = 6 W and R = V/I = 24 Ω. All three are consistent.','குறிப்பிட்ட நிலையில் I = 0.5 A; P = VI = 6 W; R = V/I = 24 Ω. மூன்று கூற்றுகளும் பொருந்தும்.')
    mc(y,36,5,'circuit','Which arrangement of 1 Ω, 5 Ω and 12 Ω gives 4 Ω?','1 Ω, 5 Ω, 12 Ω மூலம் 4 Ω தரும் அமைப்பு எது?', [('(1+5) parallel 12','(1+5), 12 சமாந்தரம்'),('All parallel','அனைத்தும் சமாந்தரம்'),('(1+12) parallel 5','(1+12), 5 சமாந்தரம்'),('(5+12) parallel 1','(5+12), 1 சமாந்தரம்')],1,'First put 1 Ω and 5 Ω in series to obtain 6 Ω. Then R = 6×12/(6+12) = 72/18 = 4 Ω.','முதலில் 1 Ω, 5 Ω தொடரில் 6 Ω பெறுக. பின்னர் R = 6×12/(6+12) = 72/18 = 4 Ω.',(.06,.24,.89,.373))
    mc(y,37,5,'pressure','Which labelled structure reduces damage from sudden pressure changes at a hydroelectric dam?','நீர்மின் அணையில் திடீர் அமுக்க மாற்றச் சேதத்தைக் குறைக்கும் பெயரிடப்பட்ட பகுதி எது?',['A','B','C','D'],3,'C is the surge tank. It accommodates rapid flow changes and reduces water-hammer pressure transients in the penstock.','C அதிர்வுத் தொட்டி. திடீர் ஓட்ட மாற்றங்களுக்கு இடமளித்து அழுத்தக் குழாயில் நீர்ச் சுத்தியல் அமுக்கத்தைத் தணிக்கும்.',(.08,.4,.91,.55))
    written(y,4,[9],[
      ('A(i–iii)','refraction','Name refraction at B and angles a,b in the source. How does b change as a increases?','B இல் நிகழ்வு, a,b கோணங்களைப் பெயரிடுக. a அதிகரித்தால் b எவ்வாறு மாறும்?','Refraction at the air–glass boundary. a is incidence to the normal; b is refraction to the normal. As incidence increases, refraction increases; in glass b < a.','வளி–கண்ணாடி எல்லையில் முறிவு. a செங்குத்திற்கான படுகோணம்; b செங்குத்திற்கான முறிவுக் கோணம். a உயரும்போது b உயரும்; கண்ணாடியில் b < a.'),
      ('A(iv–vi)','refraction','What occurs at C? Name a communication application and compare the incidence there with the critical angle.','C இல் நிகழ்வு என்ன? தொடர்பாடல் பயன்பாட்டையும் படுகோணத்தின் அவதிக் கோண ஒப்பீட்டையும் கூறுக.','Total internal reflection occurs at C: glass to air and incidence exceeds the critical angle. Optical fibres use repeated total internal reflection for communication.','C இல் முழு அகத்தெறிப்பு: கண்ணாடியிலிருந்து வளிக்கு ஒளி செல்கிறது; படுகோணம் அவதிக் கோணத்தைவிடப் பெரிது. ஒளியியல் நார்கள் தொடர்ந்த முழு அகத்தெறிப்பால் தொடர்பாடல் செய்கின்றன.'),
      ('B(i–iii)','heatcapacity','Compare A: dyed water heated at bottom and B: inverted dyed water above cold clear water. Predict capillary movement and heat transfer through B’s partition.','A இல் அடியில் சூடாக்கும் நிறநீர்; B இல் குளிர்நீரின் மேல் நிறநீர். நுண்குழாயிலுள்ள மாற்றத்தையும் B பிரிப்பானூடான வெப்ப மாற்றத்தையும் கூறுக.','A’s heated water expands and rises in the narrow tube. In B, warming the upper dyed water expands it and forces water into the tube; convection does not carry warm water downward efficiently. Heat through a solid partition is transferred by conduction.','A இல் நீர் சூடாகி விரிவதால் நுண்குழாயில் உயரும். B இல் மேலுள்ள நிறநீர் சூடாகி விரிந்து குழாயில் நகரும்; சூடான நீர் கீழே செல்லும் உடன்காவல் திறனற்றது. திண்மப் பிரிப்பானூடாக வெப்பம் கடத்தலால் செல்கிறது.'),
      ('B(iv)','heatcapacity','Find heat absorbed by 50 g water heated from 30 °C to 40 °C (c = 4200).','50 g நீர் 30 °C இலிருந்து 40 °C இற்கு சூடாகும் (c = 4200). வெப்பம் என்ன?','m = 50/1000 = 0.050 kg; ΔT = 10 K. | Q = mcΔT = 0.050 × 4200 × 10 = 2100 J.','m = 50/1000 = 0.050 kg; ΔT = 10 K. | Q = mcΔT = 0.050 × 4200 × 10 = 2100 J.')])
    written(y,7,[12],[
      ('A(i)(a–c)','forces','An 800 g block rests on a table (g = 10). Find weight, normal force and the applicable Newton law.','800 g மரக்குற்றி மேசையில் ஓய்வில் (g = 10). நிறை, செங்குத்து மறுதாக்கம், நியூட்டன் விதி என்ன?','W = 0.8 × 10 = 8 N downward; normal reaction = 8 N upward. The balanced forces give zero acceleration (Newton’s first law). They act on the same body, so they are not a third-law action–reaction pair.','W = 0.8 × 10 = 8 N கீழே; செங்குத்து மறுதாக்கம் 8 N மேலே. சமப்பட்ட விசைகள் ஆர்முடுகல் பூச்சியம் தரும் (முதலாம் விதி). ஒரே பொருளில் தாக்குவதால் அவை மூன்றாம் விதி தாக்க–மறுதாக்க ஜோடி அல்ல.'),
      ('A(ii)(a–b)','moment','Is pushing the upright block at low point A or high point B better to slide it without toppling?','நிமிர்ந்த குற்றியைச் சரியாமல் நகர்த்தத் தாழ்ந்த A அல்லது உயர்ந்த B இல் தள்ளுவதில் எது சிறந்தது?','Push at A, close to the surface. The shorter moment arm about the bottom edge gives less overturning moment than a push at B.','மேற்பரப்பருகிலுள்ள A இல் தள்ளுக. அடிவிளிம்பைப் பற்றிய திறன் புயம் குறைவதால் B ஐவிடக் கவிழ்க்கும் திருப்புத் திறன் குறையும்.'),
      ('A(iii)(a–b)','friction','Friction graph follows applied force to 4 N, then drops slightly. Name friction at 3 N and find limiting friction.','உராய்வு வரைபு விசையுடன் 4 N வரை உயரும்; பின்னர் சற்றுக் குறையும். 3 N இல் உராய்வு வகையும் எல்லை உராய்வும் என்ன?','At 3 N it is static friction balancing the applied force. The limiting static friction is the peak, 4 N. After sliding starts, kinetic friction is slightly lower.','3 N இல் நிலையுராய்வு தள்ளும் விசையைச் சமப்படுத்தும். எல்லை நிலையுராய்வு உச்சமான 4 N. நகரத் தொடங்கிய பின்னர் இயக்க உராய்வு சற்றுக் குறைவானது.'),
      ('A(iv–vi)','motion','Reduce sliding friction; then find acceleration of a 200 kg block under net 100 N and work over 4 m.','உராய்வைக் குறைக்க முறைகளைக் கூறி 200 kg குற்றியில் நிகர 100 N இற்கான ஆர்முடுகலையும் 4 m வேலையையும் காண்க.','Use lubricant or rollers between surfaces. | a = Fnet/m = 100/200 = 0.5 m s⁻². | Work = Fnet s = 100 × 4 = 400 J. Use net force for acceleration.','உராய்வு நீக்கி அல்லது உருளைகளைப் பயன்படுத்துக. | a = Fநிகர/m = 100/200 = 0.5 m s⁻². | வேலை = Fநிகர s = 100 × 4 = 400 J. ஆர்முடுகலுக்கு நிகர விசையைப் பயன்படுத்தவும்.'),
      ('B(i–ii)','moment','A 10 N downward force acts 30 cm from a nut on a spanner. Find moment, turning sense and a way to increase it without increasing force.','சாவியில் ஆணியிலிருந்து 30 cm இல் 10 N கீழ்நோக்கிய விசை. திறன், சுழற்சித் திசை, விசையை மாற்றாமல் திறன் உயர்த்தும் முறை என்ன?','Convert 30 cm to 0.30 m. | Moment = 10 × 0.30 = 3 N m, clockwise. Use a longer spanner or apply the force farther from the nut, perpendicular to the handle.','30 cm = 0.30 m. | திறன் = 10 × 0.30 = 3 N m, வலஞ்சுழி. நீண்ட சாவியைப் பயன்படுத்தவும் அல்லது ஆணியிலிருந்து தூரத்தில் கைப்பிடிக்குச் செங்குத்தாக விசையைப் பிரயோகிக்கவும்.')])
    written(y,8,[13],[
      ('D(i)','circuit','Six 2 V cells make a 12 V car battery. Describe the circuit symbols and connection.','ஆறு 2 V கலங்கள் 12 V பற்றரியை உருவாக்குகின்றன. குறியீடுகளையும் இணைப்பையும் விளக்குக.','Connect cells in series, positive to negative, so emf = 6 × 2 = 12 V. Draw six long/short line pairs; the outer long line is positive and short line negative.','நேர்முனை–மறைமுனை தொடராக இணைக்க: மின்னியக்க விசை = 6 × 2 = 12 V. ஆறு நீள/குறுகிய கோடு ஜோடிகளை வரைந்து வெளி நீள முனையை நேராகவும் குறுகியதை மறையாகவும் குறிக்கவும்.'),
      ('D(ii)(a–c)','circuit','Name the headlamp connection and describe an alternative. Why retain the original?','முகப்பு விளக்குகளின் இணைப்பைப் பெயரிட்டு மாற்று முறையையும் மூல இணைப்பின் பயனையும் கூறுக.','Original connection is parallel; an alternative is series. Parallel lamps each receive 12 V and remain independent if one fails. In series each receives less voltage and one broken filament interrupts both.','மூல இணைப்பு சமாந்தரம்; மாற்று தொடர். சமாந்தரத்தில் ஒவ்வொரு விளக்கும் 12 V பெறும்; ஒன்று பழுதானாலும் மற்றது இயங்கும். தொடரில் குறைந்த வோல்ற்றளவு கிடைக்கும்; ஒன்று உடைந்தால் இரண்டும் அணையும்.'),
      ('D(iii–v)','ohm','Each lamp is 2 Ω. Find combined resistance, current in one lamp at 12 V, and current in the other if one breaks.','ஒவ்வொரு விளக்கும் 2 Ω. சமவலுத் தடை, 12 V இல் ஒரு விளக்கின் மின்னோட்டம், மற்றது உடைந்தபின் மின்னோட்டம் என்ன?','Parallel R = (2×2)/(2+2) = 1 Ω. | Each branch current = V/Rlamp = 12/2 = 6 A. | If one branch breaks, the remaining branch still has 12 V and carries 6 A (ideal supply).','சமாந்தர R = (2×2)/(2+2) = 1 Ω. | கிளை மின்னோட்டம் = V/Rவிளக்கு = 12/2 = 6 A. | ஒன்று உடைந்தாலும் மற்றதிற்கு 12 V இருப்பதால் 6 A செல்லும் (இலட்சிய வழங்கல்).')])
    written(y,9,[14],[
      ('B(i–iii)','frequency','State audible frequency range and explain changes when generator frequency and amplifier amplitude are increased.','கேட்கக்கூடிய மீடிறன் வீச்சையும் பிறப்பாக்கி மீடிறன், விரிவாக்கி வீச்சு அதிகரிக்கும்போது மாற்றங்களையும் கூறுக.','Human hearing is approximately 20–20000 Hz. Increasing frequency raises pitch. Increasing amplitude raises loudness without changing pitch.','மனிதரின் கேட்கும் வீச்சு ஏறத்தாழ 20–20000 Hz. மீடிறன் உயர்ந்தால் சுருதி உயரும். வீச்சு உயர்ந்தால் ஒலியுரப்பு அதிகரிக்கும்; சுருதி மாறாது.'),
      ('B(iv)(a–b)','waves','Classify sound in air and describe air-particle motion.','வளியில் ஒலியை வகைப்படுத்தி வளித் துணிக்கைகளின் இயக்கத்தை விளக்குக.','Sound in air is a longitudinal mechanical wave. Particles oscillate parallel to propagation, making compressions and rarefactions. They do not travel from speaker to detector with the wave.','வளியில் ஒலி நெட்டாங்குப் பொறிமுறை அலை. துணிக்கைகள் பரவும் திசைக்குச் சமாந்தரமாக அதிர்ந்து நெருக்கங்களையும் ஐதாக்கங்களையும் உருவாக்கும். அலைக்கொப்ப துணிக்கைகள் ஒலிபெருக்கியிலிருந்து உணரிக்கு பயணிக்காது.'),
      ('B(v)(a–b)','sounddistance','Sound reaches a detector 170 m away in 0.5 s. Find speed and its response to frequency and air-temperature changes.','170 m தூரத்தில் உணரிக்கு ஒலி 0.5 s இல் வரும். கதியையும் மீடிறன்/வளி வெப்பநிலை மாற்ற விளைவையும் கூறுக.','v = d/t = 170/0.5 = 340 m s⁻¹. Changing frequency does not appreciably change sound speed in the same air. Increasing temperature increases speed.','v = d/t = 170/0.5 = 340 m s⁻¹. அதே வளியில் மீடிறன் மாற்றம் ஒலிக் கதியை மாற்றாது. வெப்பநிலை உயர்ந்தால் கதி உயரும்.')])
    y=2019
    mc(y,3,1,'units','Which quantity is scalar?','காவிக் கணியம் எது?', [('Displacement','இடப்பெயர்ச்சி'),('Distance','தூரம்'),('Pressure','அமுக்கம்'),('Velocity','வேகம்')],3,'Pressure is scalar; distance is also scalar. The source option 2 is momentum (உந்தம்), not distance, so pressure is the sole scalar among the source choices.','அமுக்கம் காவிக் கணியம்; தூரமும் காவிக் கணியம். ஆனால் மூலத் தெரிவு 2 உந்தம்; தூரம் அல்ல. எனவே மூலத் தெரிவுகளில் அமுக்கம் மட்டுமே காவிக் கணியம்.')
    DATA[y][-1]['options'][1]=bi('Momentum','உந்தம்')
    mc(y,11,2,'forces','A person weighs 600 N on Earth; Moon gravity is one-sixth. Find Moon weight.','புவியில் 600 N நிறையுள்ள மனிதனின் சந்திர நிறை என்ன? சந்திர ஈர்ப்பு ஆறிலொரு பங்கு.',['60 N','100 N','360 N','600 N'],2,'Weight is proportional to g for fixed mass: 600/6 = 100 N. Mass does not change.','மாறா திணிவிற்கு நிறை g இற்கு நேர்விகிதம்: 600/6 = 100 N. திணிவு மாறாது.')
    mc(y,15,2,'graph','Velocity rises 0→10 m/s in 10 s, stays constant until 20 s and falls to zero at 25 s. Which source statement is correct?','வேகம் 10 s இல் 0→10 m/s, 20 s வரை மாறாது, 25 s இல் பூச்சியம். சரியான மூலக் கூற்று எது?', [('Deceleration is 2 m s⁻²','அமர்முடுகல் 2 m s⁻²'),('Displacement is zero','இடப்பெயர்ச்சி பூச்சியம்'),('Acceleration is 10 m s⁻²','ஆர்முடுகல் 10 m s⁻²'),('Travels at 10 m/s for 20 s','10 m/s இல் 20 s இயங்கும்')],1,'Deceleration magnitude = (10−0)/(25−20) = 2 m s⁻². Initial acceleration is 1 m s⁻²; constant-speed interval is 10 s; displacement is positive.','அமர்முடுகல் பருமன் = (10−0)/(25−20) = 2 m s⁻². தொடக்க ஆர்முடுகல் 1 m s⁻²; மாறா வேக இடைவெளி 10 s; இடப்பெயர்ச்சி நேரானது.')
    mc(y,18,2,'circuit','An equal-length wire is used whole (1), cut in two parallel pieces (2), or three parallel pieces (3), all in series with a bulb and 6 V. When is the bulb brightest?','சமநீளக் கம்பி முழுதாக (1), இரண்டாக வெட்டி சமாந்தரம் (2), மூன்றாக வெட்டி சமாந்தரம் (3). 6 V குமிழ் எப்போது மிகப் பிரகாசம்?', [('1','1'),('2','2'),('3','3'),('2 and 3 equally','2,3 சமம்')],3,'If the whole wire has R, two halves in parallel give R/4; three thirds give R/9. The smallest added resistance gives the largest bulb current.','முழுக் கம்பியின் தடை R எனில் இரு அரைப் பகுதிகள் சமாந்தரத்தில் R/4; மூன்று மூன்றிலொன்றுகள் R/9. குறைந்த மேலதிகத் தடை மிகப்பெரிய குமிழ் மின்னோட்டத்தைத் தரும்.')
    mc(y,20,3,'photodiode','Which source diode arrangement protects a device against reversed supply polarity?','மாற்றிய மின் வழங்கல் முனைகளிலிருந்து சாதனத்தைப் பாதுகாக்கும் இருமுனைய இணைப்பு எது?',['Diagram 1 / படம் 1','Diagram 2 / படம் 2','Diagram 3 / படம் 3','Diagram 4 / படம் 4'],1,'A series diode oriented to conduct from the positive terminal blocks current when the supply is reversed. Source diagram 1 has this orientation.','நேர்முனையிலிருந்து கடத்தும் திசையில் தொடராக இணைத்த இருமுனையம் முனைகள் மாற்றப்பட்டால் மின்னோட்டத்தைத் தடுக்கும். மூலப் படம் 1 இல் இவ்வமைப்பு உள்ளது.',(.08,.176,.93,.317))
    mc(y,23,3,'pressure','Atmospheric pressure is 10⁵ Pa; eardrum area is 5×10⁻⁵ m². Find force on one side.','வளிமண்டல அமுக்கம் 10⁵ Pa; செவிப்பறை பரப்பு 5×10⁻⁵ m². ஒரு பக்க விசை என்ன?',['5 N','1/5 N','(1/5)×10¹⁰ N','5×10⁻¹⁰ N'],1,'F = pA = 10⁵ × 5×10⁻⁵ = 5 N. This is one-side force; balanced pressures on both sides reduce the net force.','F = pA = 10⁵ × 5×10⁻⁵ = 5 N. இது ஒரு பக்க விசை; இருபக்கச் சம அமுக்கம் நிகர விசையைக் குறைக்கும்.')
    mc(y,24,3,'transformer','An ideal transformer has primary power 200 W and secondary voltage 10 V. Find secondary current.','இலட்சிய நிலைமாற்றியின் முதன்மை வலு 200 W; துணை வோல்ற்றளவு 10 V. துணை மின்னோட்டம் என்ன?',['10 A','20 A','40 A','50 A'],2,'100% efficiency gives output power 200 W. Is = P/Vs = 200/10 = 20 A.','100% திறனில் வெளியீட்டு வலு 200 W. Is = P/Vs = 200/10 = 20 A.')
    mc(y,28,3,'magnetic','Which device uses the force on a current-carrying conductor in a magnetic field?','காந்தப் புலத்தில் மின்னோட்டமுள்ள கடத்தியில் தாக்கும் விசையைப் பயன்படுத்துவது எது?', [('Moving-coil microphone','அசையும் சுருள் நுணுக்குப்பன்னி'),('Electric bell','மின் மணி'),('Transformer','நிலைமாற்றி'),('DC motor','நேரோட்ட மோட்டர்')],4,'A DC motor uses the motor effect to turn a coil. Microphones and transformers use induction; an electric bell uses an electromagnet’s attraction.','நேரோட்ட மோட்டர் விசை விளைவால் சுருளைச் சுழற்றும். நுணுக்குப்பன்னியும் நிலைமாற்றியும் தூண்டலைப் பயன்படுத்தும்; மின் மணி மின்காந்தக் கவர்ச்சியைப் பயன்படுத்தும்.')
    mc(y,32,4,'buoyancy','A swimmer wearing an air-filled ring is more buoyant as the ring inflates. Why?','வளி நிரம்பிய மிதவை வளையம் பெரிதாகும்போது நீந்துபவரின் மிதப்பு ஏன் அதிகரிக்கும்?', [('Upthrust increases','மேலுதைப்பு அதிகரிக்கும்'),('Upthrust decreases','மேலுதைப்பு குறையும்'),('More gas dissolves in water','அதிக வாயு நீரில் கரையும்'),('Water cools','நீர் குளிரும்')],1,'The inflated ring displaces more water, increasing buoyancy U = ρwater g Vdisplaced. Added air mass is small compared with the extra displaced water.','விரிந்த வளையம் அதிக நீரை இடம்பெயர்ப்பதால் U = ρநீர் g Vஇடப்பெயர்ச்சி அதிகரிக்கும். மேலதிக வளித் திணிவு இடம்பெயர்ந்த நீர்த் திணிவைவிடச் சிறியது.')
    mc(y,33,4,'absorption','Which sound property decreases as a loudspeaker’s wave travels through air?','ஒலிபெருக்கியிலிருந்து வளியில் ஒலி பரவும்போது குறைவது எது?', [('Frequency','மீடிறன்'),('Speed','கதி'),('Wavelength','அலைநீளம்'),('Amplitude','வீச்சு')],4,'Spreading and absorption reduce amplitude and intensity. Frequency remains set by the source; speed is set by the air conditions.','பரவலும் உறிஞ்சலும் வீச்சையும் செறிவையும் குறைக்கும். மீடிறன் மூலத்தாலும் கதி வளியின் நிலைகளாலும் நிர்ணயிக்கப்படும்.')
    mc(y,37,4,'pressure','Which affects pressure at the bottom for water filled to a given height?','குறித்த உயரத்திற்கு நிரம்பிய நீரின் அடியமுக்கத்தை நிர்ணயிப்பது எது?', [('Volume','கனவளவு'),('Vessel shape','பாத்திர வடிவம்'),('Bottom area','அடிப்பரப்பு'),('Water-column height','நீர்நிரல் உயரம்')],4,'p = ρgh. For the same liquid and g, pressure depends on the vertical water-column height.','p = ρgh. அதே திரவம், g இற்கு அமுக்கம் செங்குத்து நீர்நிரல் உயரத்தில் தங்கும்.')
    mc(y,39,4,'heatcapacity','Which comparison of boiling and evaporation is false?','கொதித்தல், ஆவியாதல் பற்றிய பொய்யான ஒப்பீடு எது?', [('Boiling temperature is constant','கொதிக்கும் வெப்பநிலை மாறாது'),('Boiling is slow; evaporation is fast','கொதித்தல் மந்தம்; ஆவியாதல் துரிதம்'),('Wind affects evaporation, not bulk boiling directly','காற்று ஆவியாதலைப் பாதிக்கும்'),('Evaporation can cool remaining water','ஆவியாதல் நீரைக் குளிர்விக்கும்')],2,'Boiling is rapid vaporisation throughout liquid; evaporation occurs at the surface and is generally slower. At fixed pressure, boiling temperature stays constant while latent heat is supplied.','கொதித்தல் திரவம் முழுவதிலும் துரிதமாக நடக்கும்; ஆவியாதல் மேற்பரப்பில் பொதுவாக மெதுவாக நடக்கும். மாறா அமுக்கத்தில் மறை வெப்பம் வழங்கும்போது கொதிநிலை மாறாது.')
    written(y,1,[5,6],[
      ('B(i)(a–b)','power','State two measures for comfortable laboratory lighting and two to reduce electricity consumption.','ஆய்வுகூடத்தில் பொருத்தமான ஒளிக்கான இரு முறைகளையும் மின் நுகர்வைக் குறைக்க இரு முறைகளையும் கூறுக.','Use well-distributed lamps and appropriate brightness to avoid glare/shadows. Reduce electricity use with efficient LEDs and switching off unnecessary lamps or using daylight.','கண்ணைக் கூசவைக்கும் ஒளி/நிழலைத் தவிர்க்கச் சீராகப் பரவிய பொருத்தமான விளக்குகளைப் பயன்படுத்துக. திறனுள்ள LED, தேவையற்ற விளக்குகளை அணைத்தல், பகல் ஒளி மூலம் மின் நுகர்வைக் குறைக்கவும்.'),
      ('B(ii)(a–b)','energy','Complete chemical energy → potential energy → a → b for steam turning a generator.','நீராவி பிறப்பாக்கியை இயக்கும்போது இரசாயனச் சக்தி → அழுத்தச் சக்தி → a → b பூர்த்திசெய்க.','a = kinetic/mechanical energy of the turbine; b = electrical energy of the generator. Steam expansion does work on turbine blades, and the generator converts rotation into electricity by induction.','a = சுழலியின் இயக்க/பொறிமுறைச் சக்தி; b = பிறப்பாக்கியின் மின் சக்தி. விரியும் நீராவி சுழலியை இயக்கும்; பிறப்பாக்கி தூண்டலால் சுழற்சியை மின்சாரமாக மாற்றும்.')])
    written(y,4,[8],[
      ('A(i–iii)','ohm','Describe the Ohm-law circuit: cell arrangement, missing meter at XY and purpose of rheostat.','ஓம் விதிச் சுற்றின் கல இணைப்பு, XY இல் விடுபட்ட மீற்றர், மாறுதடையின் பயன்பாடு என்ன?','Cells are in series. Insert an ammeter in series at XY; connect a voltmeter in parallel across the nichrome wire. Use the rheostat to vary current for several V–I readings.','கலங்கள் தொடரில். XY இல் அம்மீற்றரைத் தொடரிலும் நைக்குரோம் கம்பிக்குச் சமாந்தரமாக வோல்ற்மீற்றரையும் இணைக்கவும். மாறுதடை மூலம் மின்னோட்டத்தை மாற்றி பல V–I வாசிப்புகளைப் பெறலாம்.'),
      ('A(iv–v)','ohm','Why open the switch between readings? What quantity is the slope of a V-versus-I graph?','வாசிப்புகளுக்கிடையில் ஆளியை ஏன் திறக்க வேண்டும்? V–I சாய்வு குறிக்கும் கணியம் என்ன?','Opening prevents heating, helping maintain constant temperature and resistance. For V on the vertical axis and I horizontally, slope ΔV/ΔI = R, measured in ohms.','சூடாவதைத் தவிர்த்து வெப்பநிலையையும் தடையையும் மாறாமல் பேண ஆளியைத் திறக்க வேண்டும். V செங்குத்து, I கிடை எனில் சாய்வு ΔV/ΔI = R; அலகு ஓம்.'),
      ('B(i–iii)','forces','Two balances support a statue and read 250 N and 150 N. Name forces, classify them and find statue weight.','சிலையைத் தாங்கும் இரு தராசுகள் 250 N, 150 N காட்டுகின்றன. விசைகள், வகை, சிலையின் நிறை என்ன?','Upward reactions R = 250 N and S = 150 N; downward gravity W. R and S are contact forces, W is non-contact. | W = R + S = 250 + 150 = 400 N.','மேல்நோக்கிய R = 250 N, S = 150 N; கீழ்நோக்கிய ஈர்ப்பு W. R, S தொடுகை விசைகள்; W தொடுகையற்றது. | W = R + S = 250 + 150 = 400 N.'),
      ('B(iv–vi)','moment','Supports are 2 m apart. Express moment of W about A using d, calculate S moment and find centre-of-gravity distance d.','ஆதாரங்கள் 2 m இடைவெளியில். A பற்றி W திறனை d கொண்டு எழுதி S திறனையும் ஈர்ப்பு மையத் தூரம் d ஐயும் காண்க.','W’s clockwise moment = 400d N m. | S’s anticlockwise moment = 150 × 2 = 300 N m. | Equilibrium: 400d = 300, so d = 0.75 m from A.','W இன் வலஞ்சுழித் திறன் = 400d N m. | S இன் இடஞ்சுழித் திறன் = 150 × 2 = 300 N m. | சமநிலை: 400d = 300; A இலிருந்து d = 0.75 m.')])
    written(y,7,[10,11],[
      ('A(i–ii)','lenses','Name C and D in the convex-lens diagram and complete the two rays through C and B.','குவிவு வில்லைப் படத்தில் C, D ஐப் பெயரிட்டு C, B வழிக் கதிர்களைப் பூர்த்திசெய்க.','C is optical centre; D is principal focus on the far side. A ray through C is undeviated. A ray through near-side focus B emerges parallel to the principal axis.','C ஒளியியல் மையம்; D மறுபுற முதலான குவியம். C வழிக் கதிர் திசை மாறாது. அருகுபுற குவியம் B வழிக் கதிர் முதலான அச்சிற்குச் சமாந்தரமாக வெளிவரும்.'),
      ('A(iii–iv)','lenses','For an object between F and 2F, give two image properties and describe finding focal length experimentally.','F, 2F இடையில் பொருள் எனில் விம்பத்தின் இரு இயல்புகள் என்ன? சோதனையில் குவியத் தூரம் பெறுவது எவ்வாறு?','The image is real, inverted and enlarged beyond 2F. Focus a distant object sharply on a screen; the lens–screen distance approximates focal length because incident rays are nearly parallel.','விம்பம் 2F இற்கு அப்பால் மெய், தலைகீழ், பெரியது. தொலைப் பொருளின் தெளிவான விம்பத்தைத் திரையில் பெறுக; படுகதிர்கள் ஏறத்தாழ சமாந்தரமாதலால் வில்லை–திரைத் தூரம் குவியத் தூரத்திற்கு அண்மிக்கும்.'),
      ('B(i–iii)','power','Compare a 60 W filament lamp with a 10 W LED over 10 hours. Find energies in joules and explain the advantage.','60 W இழை விளக்கும் 10 W LED உம் 10 மணி இயங்குகின்றன. சக்திகளை யூலில் கணித்து நன்மையை விளக்குக.','t = 10 × 3600 = 36000 s. | Filament E = 60 × 36000 = 2160000 J; LED E = 10 × 36000 = 360000 J. | Same useful brightness with LED uses one-sixth the electricity: saving = 1800000 J, about 83.3%.','t = 10 × 3600 = 36000 s. | இழை E = 60 × 36000 = 2160000 J; LED E = 10 × 36000 = 360000 J. | சம பயனுள்ள ஒளிக்கு LED ஆறிலொரு மின்சாரம் பயன்படுத்தும்; சேமிப்பு = 1800000 J, ஏறத்தாழ 83.3%.'),
      ('B(iv–v)','power','Find LED energy for 10 h/day over 30 days, and filament efficiency if 40% is wasted as heat.','LED நாள் 10 மணி, 30 நாள் இயங்குவதற்கான சக்தியும் இழை விளக்கில் 40% வெப்பமாக விரயமானால் திறனும் காண்க.','LED energy = 0.010 kW × 10 h × 30 = 3 kWh. | Useful fraction = 100% − 40% = 60%; efficiency = 60%.','LED சக்தி = 0.010 kW × 10 h × 30 = 3 kWh. | பயனுள்ள பகுதி = 100% − 40% = 60%; திறன் = 60%.')])
    written(y,8,[11,12],[
      ('B(i–iii)','heatcapacity','2 kg water has c = 4200; 2 kg liquid X has c = 2100. Each receives 8400 J. Find temperature rises and the better coolant.','2 kg நீரின் c = 4200; 2 kg X திரவத்தின் c = 2100. ஒவ்வொன்றுக்கும் 8400 J. வெப்பநிலை உயர்வுகளும் சிறந்த குளிர்ச்சியாக்கியும் என்ன?','ΔTwater = Q/(mc) = 8400/(2×4200) = 1 K. | ΔTX = 8400/(2×2100) = 2 K. | Water is better: higher specific heat absorbs more heat for a given temperature rise.','ΔTநீர் = Q/(mc) = 8400/(2×4200) = 1 K. | ΔTX = 8400/(2×2100) = 2 K. | நீர் சிறந்தது; உயர் தன்வெப்பக் கொள்ளளவு குறைந்த வெப்பநிலை உயர்விற்கு அதிக வெப்பத்தை ஏற்கும்.'),
      ('B(iv)(a–e)','heatcapacity','Heating water reaches a constant thermometer reading. Name the temperature, observations, phase change, heat and reason for constant temperature.','தொடர்ந்து சூடாக்கும் நீரில் வாசிப்பு மாறாமல் உள்ளது. வெப்பநிலை, அவதானிப்பு, நிலை மாற்றம், வெப்பம், மாறாததற்கான காரணம் என்ன?','At ordinary pressure it is the boiling point, approximately 100 °C. Bubbles and steam form as liquid becomes gas. Supplied latent heat of vaporisation overcomes intermolecular attraction rather than raising average kinetic energy, so temperature stays constant while boiling.','சாதாரண அமுக்கத்தில் இது கொதிநிலை; ஏறத்தாழ 100 °C. குமிழ்களும் நீராவியும் உருவாகி திரவம் வாயுவாகும். ஆவியாக்க மறை வெப்பம் மூலக்கூறிடைக் கவர்ச்சியை வெல்வதால் சராசரி இயக்கச் சக்தி/வெப்பநிலை உயராது.')])
    written(y,9,[12],[
      ('B(i–iii)','transistor','Identify transistor amplifier terminals X,Y,Z and input connections for a moving-coil microphone.','திரான்சிஸ்ரர் விரிவாக்கியின் X,Y,Z முனைகளையும் நுணுக்குப்பன்னி உள்ளீட்டு இணைப்பையும் இனங்காண்க.','X = base, Y = collector, Z = emitter. Connect microphone across P and Q at the input coupling capacitor. The moving coil generates a changing electrical signal by electromagnetic induction.','X = அடி, Y = சேகரிப்பான், Z = காலி. உள்ளீட்டுக் கொள்ளளவியருகில் P,Q இற்கிடையில் நுணுக்குப்பன்னியை இணைக்கவும். அசையும் சுருள் மின்காந்தத் தூண்டலால் மாறும் மின் சைகையை உருவாக்கும்.'),
      ('B(iv–v)','transistor','Where does the loudspeaker connect and what does the coupling capacitor change?','ஒலிபெருக்கி எங்கு இணைக்கப்படும்? இணைப்புக் கொள்ளளவி சைகையில் என்ன மாற்றம் செய்கிறது?','Connect the speaker between R and S in the collector circuit. The input capacitor passes changing signal components while blocking steady DC, preserving the amplifier bias.','சேகரிப்பான் சுற்றில் R,S இடையில் ஒலிபெருக்கி இணைக்கப்படும். உள்ளீட்டுக் கொள்ளளவி மாறும் சைகையை அனுமதித்து நிலையான நேரோட்டத்தைத் தடுப்பதால் சாய்வூட்டல் பேணப்படும்.'),
      ('B(vi–vii)','magnetic','What changes in the amplified signal, and how does the speaker produce sound?','விரிவாக்கப்பட்ட சைகையில் என்ன மாற்றம்? ஒலிபெருக்கி எவ்வாறு ஒலி உருவாக்கும்?','Amplification increases signal amplitude while retaining frequency. Current in the speaker coil experiences magnetic force and moves the attached cone, causing air compressions/rarefactions that form sound.','விரிவாக்கம் மீடிறனைப் பேணியபடி வீச்சை உயர்த்தும். ஒலிபெருக்கிச் சுருள் மின்னோட்டம் காந்த விசையை அனுபவித்து கூம்பை அசைக்கும்; வளி நெருக்கங்கள்/ஐதாக்கங்கள் ஒலியை உருவாக்கும்.')])
