from expanded_physics import mc, written

def add():
    y=2016
    mc(y,1,1,'units','Which is a scalar quantity?','காவிக் கணியம் எது?', [('Mass','திணிவு'),('Weight','நிறை'),('Velocity','வேகம்'),('Displacement','இடப்பெயர்ச்சி')],1,'Mass has magnitude only. Weight is a force; velocity and displacement include direction.','திணிவிற்கு பருமன் மட்டும் உண்டு. நிறை ஒரு விசை; வேகமும் இடப்பெயர்ச்சியும் திசையுடையவை.')
    mc(y,15,2,'kelvin','Day and night temperatures are 16 °C and 4 °C. Find their difference in kelvin.','பகல் 16 °C, இரவு 4 °C. வெப்பநிலை வேறுபாட்டைக் கெல்வினில் காண்க.',['12 K','277 K','285 K','289 K'],1,'ΔT = 16 − 4 = 12 °C = 12 K. Add 273 only to convert an absolute temperature, not a difference.','ΔT = 16 − 4 = 12 °C = 12 K. தனி வெப்பநிலைக்கு மட்டுமே 273 கூட்டப்படும்; வேறுபாட்டிற்கு அல்ல.')
    mc(y,19,2,'lenses','A convex lens has focal length 30 cm. Where must an object be placed for a real image of equal size?','குவிவு வில்லையின் குவியத் தூரம் 30 cm. சம அளவுள்ள மெய்விம்பத்திற்கு பொருள் எங்கு இருக்க வேண்டும்?',['30 cm','60 cm','120 cm','150 cm'],2,'Equal-size real images form when u = v = 2f. Thus u = 2 × 30 = 60 cm.','சம அளவுள்ள மெய்விம்பத்திற்கு u = v = 2f. எனவே u = 2 × 30 = 60 cm.')
    mc(y,21,2,'pressure','Find water pressure 2 m below a lake surface (ρ = 1000 kg m⁻³, g = 10 m s⁻²).','ஏரியின் மேற்பரப்பிலிருந்து 2 m ஆழத்தில் நீரமுக்கத்தைக் காண்க (ρ = 1000 kg m⁻³, g = 10 m s⁻²).',['1000 Pa','2000 Pa','10000 Pa','20000 Pa'],4,'p = ρgh = 1000 × 10 × 2 = 20000 Pa. This is the pressure due to water, excluding atmospheric pressure.','p = ρgh = 1000 × 10 × 2 = 20000 Pa. இது நீரால் மட்டும் ஏற்படும் அமுக்கம்; வளிமண்டல அமுக்கம் சேர்க்கப்படவில்லை.')
    mc(y,25,3,'heatcapacity','Two nested glass tumblers are stuck. Which heating/cooling arrangement releases them most easily?','ஒன்றினுள் ஒன்று சிக்கிய கண்ணாடிக் குவளைகளை எவ்வாறு பிரிக்கலாம்?', [('Hot inner, hot outer','உள் சூடு, வெளி சூடு'),('Cold inner, hot outer','உள் குளிர், வெளி சூடு'),('Hot inner, cold outer','உள் சூடு, வெளி குளிர்'),('Cold inner, cold outer','உள் குளிர், வெளி குளிர்')],2,'Cool the inner tumbler so it contracts, and warm the outer tumbler so it expands. The source arrangement is option 2.','உள் குவளையைக் குளிர்வித்துச் சுருக்கி வெளிக் குவளையைச் சூடாக்கி விரிவாக்குக. மூலத்தாளில் இது தெரிவு 2.',(.05,.065,.9,.215))
    # Options follow the source: 1 hot/hot, 2 cold/hot, 3 hot/cold, 4 cold/cold.
    mc(y,31,3,'friction','On what do frictional forces between two surfaces depend?','இரு மேற்பரப்புகளுக்கிடையிலான உராய்வு விசை எதில் தங்கியுள்ளது?', [('Surface nature and normal reaction','மேற்பரப்பின் தன்மையும் செங்குத்து மறுதாக்கமும்'),('Normal reaction and contact area','செங்குத்து மறுதாக்கமும் தொடுகைப் பரப்பும்'),('Surface nature and contact area','மேற்பரப்பின் தன்மையும் தொடுகைப் பரப்பும்'),('Surface nature, reaction and area','மேற்பரப்பு, மறுதாக்கம், பரப்பு')],1,'For dry sliding friction, F = μN. μ describes the contacting materials; N is the normal reaction. Apparent area is not an independent factor in this model.','உலர் உராய்விற்கு F = μN. μ மேற்பரப்புகளின் தன்மையையும் N செங்குத்து மறுதாக்கத்தையும் குறிக்கும். இம்மாதிரியில் தொடுகைப் பரப்பு தனிக் காரணி அல்ல.')
    mc(y,32,3,'forces','Find the Moon weight of a 60 kg person if Earth g = 10 m s⁻² and Moon g is one-sixth of Earth g.','புவியில் g = 10 m s⁻²; சந்திரனில் அதன் ஆறிலொரு பங்கு. 60 kg மனிதனின் சந்திர நிறை என்ன?',['1/6 N','10 N','100 N','1000/6 N'],3,'Mass remains 60 kg. Moon weight = mg = 60 × (10/6) = 100 N.','திணிவு 60 kg ஆகவே இருக்கும். சந்திர நிறை = mg = 60 × (10/6) = 100 N.')
    mc(y,35,4,'circuit','Two 18 Ω resistors are parallel across a 6 V cell. Find the total current.','6 V கலத்துடன் இரு 18 Ω தடைகள் சமாந்தரமாக உள்ளன. மொத்த மின்னோட்டம் என்ன?',['1/6 A','2/3 A','3 A','6 A'],2,'1/R = 1/18 + 1/18, so R = 9 Ω. I = V/R = 6/9 = 2/3 A.','1/R = 1/18 + 1/18; R = 9 Ω. I = V/R = 6/9 = 2/3 A.',(.14,.08,.59,.19))
    mc(y,36,4,'magnetic','Current travels upward from P to S. Which diagram gives its magnetic field?','P இலிருந்து S நோக்கி மேலே மின்னோட்டம் செல்கிறது. சரியான காந்தப் புலப் படம் எது?', [('Downward current, anticlockwise field','கீழ் மின்னோட்டம், இடஞ்சுழிப் புலம்'),('Upward current, anticlockwise field','மேல் மின்னோட்டம், இடஞ்சுழிப் புலம்'),('Upward current, clockwise field','மேல் மின்னோட்டம், வலஞ்சுழிப் புலம்'),('Downward current, clockwise field','கீழ் மின்னோட்டம், வலஞ்சுழிப் புலம்')],2,'The long cell line at S is positive, so conventional current flows S to P, downward. Looking from above, the field is clockwise: source option 4.','S பக்கத்திலுள்ள நீளமான கலக் கோடு நேர்முனை. மரபு மின்னோட்டம் S இலிருந்து P நோக்கிக் கீழே செல்கிறது. மேலிருந்து பார்த்தால் புலம் வலஞ்சுழி; மூலத் தெரிவு 4.',(.07,.235,.86,.38))
    # Correct the prompt/options to the cell polarity, rather than assuming upward flow.
    from expanded_physics import DATA,bi
    q=DATA[y][-1]; q['prompt']=bi('Use the 6 V circuit above. Which diagram correctly shows current and field around SP?','மேலுள்ள 6 V சுற்றைப் பயன்படுத்துக. SP இல் மின்னோட்டத்தையும் காந்தப் புலத்தையும் சரியாகக் காட்டும் படம் எது?');q['correct']=3
    mc(y,37,4,'forces','Opposing forces X and 15 N give a 10 N resultant in the direction of X. Find X.','X, 15 N ஆகிய எதிர் விசைகளின் விளையுள் X திசையில் 10 N. X ஐக் காண்க.',['15 N','25 N','35 N','45 N'],2,'Choose X as positive: X − 15 = 10. Hence X = 25 N.','X திசையை நேராகக் கொள்க: X − 15 = 10. எனவே X = 25 N.')
    mc(y,38,4,'graph','Displacements at t = 0…11 s are 0,2,4,6,6,6,8,8,7,4,2,0 m. Which statement is false?','t = 0…11 s இல் இடப்பெயர்ச்சிகள் 0,2,4,6,6,6,8,8,7,4,2,0 m. பொய்யான கூற்று எது?', [('Uniform velocity for first 3 s','முதல் 3 s இல் சீரான வேகம்'),('At rest for a total of 5 s','மொத்தம் 5 s ஓய்வு'),('Returns to the starting position','தொடக்க இடத்திற்குத் திரும்பும்'),('Total distance is 16 m','மொத்தத் தூரம் 16 m')],2,'Rest occurs from 3–5 s (2 s) and 6–7 s (1 s): total 3 s, not 5 s. Distance is 8 m outward + 8 m back = 16 m.','3–5 s இல் 2 s, 6–7 s இல் 1 s ஓய்வு; மொத்தம் 3 s, 5 s அல்ல. தூரம் = வெளியே 8 + திரும்ப 8 = 16 m.')
    mc(y,39,4,'induction','In which case is no current induced in a coil near a magnet?','காந்தத்தின் அருகிலுள்ள சுருளில் எந்த நிலையில் தூண்டல் மின்னோட்டம் இல்லை?', [('Magnet moves toward fixed coil','நிலையான சுருளை நோக்கிக் காந்தம் நகரும்'),('Both remain at rest','காந்தமும் சுருளும் ஓய்வில்'),('Magnet moves away','காந்தம் விலகும்'),('Coil moves toward fixed magnet','நிலையான காந்தத்தை நோக்கிச் சுருள் நகரும்')],2,'Induced emf requires changing magnetic flux. With both at rest, flux is unchanged and no current is induced.','தூண்டலுக்கு காந்தப் பாயம் மாற வேண்டும். இரண்டும் ஓய்வில் இருந்தால் பாயம் மாறாது; மின்னோட்டம் தூண்டப்படாது.')
    written(y,4,[7,8],[
      ('i','waves','Classify the listed waves into longitudinal and transverse: radio, gamma, visible light, ultraviolet, microwave, infrasonic, sound and ultrasonic.','வானொலி, காமா, கட்புல ஒளி, ஊதாக்கடந்த, நுண்ணலை, தாழொலி, ஒலி, கழியொலி ஆகியவற்றை நெட்டாங்கு/குறுக்காக வகைப்படுத்துக.','Electromagnetic waves (radio, gamma, light, UV, microwave) are transverse. Sound, infrasonic and ultrasonic waves in air are longitudinal.','மின்காந்த அலைகள் (வானொலி, காமா, ஒளி, ஊதாக்கடந்த, நுண்ணலை) குறுக்கு அலைகள். வளியில் ஒலி, தாழொலி, கழியொலி நெட்டாங்கு அலைகள்.'),
      ('ii–iii','frequency','State a special property of ultrasound and identify the wave used to inspect a foetus.','கழியொலியின் சிறப்பியல்பையும் கருவைப் பரிசோதிக்கும் அலையையும் குறிப்பிடுக.','Ultrasound has frequency above 20000 Hz, outside human hearing. Echoes from tissue boundaries are used in ultrasound scanning, without ionising X-rays.','கழியொலியின் மீடிறன் 20000 Hz இற்கு மேல்; மனிதரால் கேட்க முடியாது. இழைய எல்லைகளின் எதிரொலிகள் கருப் பரிசோதனையில் பயன்படும்; அயனாக்கும் X-கதிர்கள் அல்ல.'),
      ('iv(a)','waves','Complete the electromagnetic sequence A, B, visible, ultraviolet, C, gamma.','A, B, கட்புல ஒளி, ஊதாக்கடந்த, C, காமா என்ற மின்காந்த வரிசையைப் பூர்த்திசெய்க.','A = radio/microwaves (the combined long-wave band in this six-box sequence); B = infrared; C = X-rays. Frequency increases and wavelength decreases toward gamma.','A = வானொலி/நுண்ணலை (இவ்வாறு இணைக்கப்பட்ட நீள அலைப் பகுதி); B = செங்கீழ்; C = X-கதிர்கள். காமாவை நோக்கி மீடிறன் அதிகரித்து அலைநீளம் குறையும்.'),
      ('iv(b) I–IV','waves','In the source wave, name R and the distance PQ. Draw a shorter-frequency wave at the same speed and name the band before A.','மூல அலையில் R, PQ ஐப் பெயரிடுக. அதே கதியில் குறைந்த மீடிறனுள்ள அலையை வரைந்து A இற்கு முந்தைய பகுதியைப் பெயரிடுக.','R is a trough. PQ joins consecutive crests and equals one wavelength. | At constant v, λ = v/f: a lower frequency needs wider crest spacing. | Before the visible/infrared end toward low frequency lie microwaves and radio waves.','R தாழி. அடுத்தடுத்த முகடுகளுக்கிடையிலான PQ ஒரு அலைநீளம். | மாறா கதியில் λ = v/f; குறைந்த மீடிறனுக்கு முகடுகளின் இடைவெளி பெரிதாகும். | குறைந்த மீடிறன் பக்கத்தில் நுண்ணலைகளும் வானொலி அலைகளும் உள்ளன.'),
      ('v(a–c)','frequency','A vibrating metal strip projects 5 cm (P) or 10 cm (Q) from a table. Compare pitch and frequency; what can this experiment establish?','உலோகத் தகடு மேசைக்கு வெளியே P இல் 5 cm, Q இல் 10 cm நீளமாக உள்ளது. சுருதி, மீடிறனை ஒப்பிடுக; சோதனையின் முடிவு என்ன?','P’s shorter free length vibrates faster and gives higher pitch than Q. Pitch depends on frequency. This is a qualitative comparison; no numerical frequency follows from length alone.','P இன் குறுகிய பகுதி விரைவாக அதிர்ந்து Q ஐவிட உயர்ந்த சுருதியைக் கொடுக்கும். சுருதி மீடிறனில் தங்கியுள்ளது. இது தர ஒப்பீடு; நீளத்திலிருந்து மட்டும் எண் மீடிறனைப் பெற முடியாது.'),
      ('vi','sounddistance','How does the speed of sound in air change with temperature?','வளியில் ஒலியின் கதி வெப்பநிலையுடன் எவ்வாறு மாறும்?','It increases as air temperature rises, because molecular motion and the propagation of pressure disturbances become faster.','வளியின் வெப்பநிலை உயரும்போது ஒலியின் கதி அதிகரிக்கும்; மூலக்கூறுகளின் இயக்கமும் அமுக்கக் குழப்பங்களின் பரவலும் விரைவாகும்.')])
    written(y,7,[10],[
      ('A(i)','energy','Write the energy changes in a hydroelectric station.','நீர்மின் நிலையத்தின் சக்தி மாற்றங்களை எழுதுக.','Stored water: gravitational potential energy → moving water: kinetic energy → turbine: rotational mechanical energy → generator: electrical energy. Some energy is dissipated as heat and sound.','தேக்க நீரின் ஈர்ப்பு அழுத்தச் சக்தி → பாயும் நீரின் இயக்கச் சக்தி → சுழலியின் சுழற்சிப் பொறிமுறைச் சக்தி → பிறப்பாக்கியின் மின் சக்தி. ஒரு பகுதி வெப்பம், ஒலியாக விரயமாகும்.'),
      ('A(ii)(a–b)','transformer','Name P (12.5→220 kV). For R (22 kV→230 V), find secondary turns if primary turns are 8800.','P (12.5→220 kV) ஐப் பெயரிடுக. R (22 kV→230 V) இல் முதன்மை 8800 முறுக்குகள் எனில் துணை முறுக்குகளைக் காண்க.','P is a step-up transformer. | Ns/Np = Vs/Vp; convert 22 kV to 22000 V. | Ns = 8800 × 230/22000 = 92 turns.','P ஏற்றும் நிலைமாற்றி. | Ns/Np = Vs/Vp; 22 kV = 22000 V. | Ns = 8800 × 230/22000 = 92 முறுக்குகள்.'),
      ('B(i–ii)','heating','Why does a fully immersed heater heat water faster than a partly immersed one? Why do water and vessel temperatures rise differently?','முழுமையாக அமிழ்ந்த வெப்பமாக்கி ஏன் விரைவாக நீரைச் சூடாக்குகிறது? நீரும் பாத்திரமும் ஏன் வேறுபட்ட வீதத்தில் சூடாகும்?','Full immersion transfers a greater fraction of heat into water instead of air; convection distributes it. The vessel and water have different heat capacities (mc), so equal heat does not mean equal temperature rise.','முழு அமிழ்வு வெப்பத்தின் பெரும்பகுதியை வளிக்கு அல்ல நீருக்கு வழங்கும்; உடன்காவல் பரப்பும். நீர், பாத்திரத்தின் வெப்பக் கொள்ளளவுகள் mc வேறுபடுவதால் சம வெப்பத்திற்கு வெப்பநிலை உயர்வுகள் சமமல்ல.'),
      ('B(iii)(a)','heatcapacity','Heat 1.5 kg water from 27 °C to 97 °C (c = 4200 J kg⁻¹ K⁻¹). Find absorbed heat.','1.5 kg நீரை 27 °C இலிருந்து 97 °C இற்கு வெப்பமாக்குக (c = 4200 J kg⁻¹ K⁻¹). உறிஞ்சிய வெப்பம் என்ன?','ΔT = 97 − 27 = 70 K. | Q = mcΔT = 1.5 × 4200 × 70 = 441000 J.','ΔT = 97 − 27 = 70 K. | Q = mcΔT = 1.5 × 4200 × 70 = 441000 J.'),
      ('B(iii)(b–c)','power','A 1 kW heater runs for 8 min. Find electrical energy and monthly units for four uses daily over 30 days.','1 kW வெப்பமாக்கி 8 min இயங்குகிறது. மின் சக்தியையும் நாள் ஒன்றுக்கு நான்கு பயன்பாடுகளாக 30 நாளுக்கான அலகுகளையும் காண்க.','E = Pt = 1000 × (8 × 60) = 480000 J per use. | Monthly energy = 1 kW × (8/60) h × 4 × 30 = 16 kWh = 16 units.','E = Pt = 1000 × (8 × 60) = 480000 J ஒரு பயன்பாட்டிற்கு. | மாத சக்தி = 1 kW × (8/60) h × 4 × 30 = 16 kWh = 16 அலகுகள்.'),
      ('C(i–iv)','lightdevice','For a solar cell, state a suitable material, what incident sunlight does, how a panel is assembled and one use.','சூரிய கலத்தின் பொருள், சூரிய ஒளி படும்போது நிகழ்வு, பலகை அமைப்பு, ஒரு பயன்பாடு என்பவற்றைக் குறிப்பிடுக.','Silicon is a suitable semiconductor. Light produces an emf/current through the photovoltaic effect. Multiple cells are combined in series/parallel to obtain useful voltage/current. Example: generating electricity for lighting.','சிலிக்கன் பொருத்தமான அரைக்கடத்தி. ஒளிமின்னழுத்த விளைவால் ஒளி மின்னியக்க விசை/மின்னோட்டத்தை உருவாக்கும். பல கலங்களைத் தொடர்/சமாந்தரமாக இணைத்து தேவையான வோல்ற்றளவு/மின்னோட்டம் பெறப்படும். உதாரணம்: விளக்குகளுக்கு மின்சாரம்.')])
    written(y,8,[11],[
      ('B(i)','forces','A stationary swing has upward tensions F1, F2 and downward weight W. State the relation.','ஓய்விலுள்ள ஊஞ்சலில் மேல்நோக்கிய F1, F2 இழுவைகளும் கீழ்நோக்கிய W நிறையும் உள்ளன. தொடர்பை எழுதுக.','Vertical resultant is zero: F1 + F2 − W = 0, so F1 + F2 = W. Equal tensions require the additional assumption of symmetry.','செங்குத்து விளையுள் பூச்சியம்: F1 + F2 − W = 0; F1 + F2 = W. இழுவைகள் சமமாக இருக்கச் சமச்சீர் அமைப்பும் தேவை.'),
      ('B(ii)(a–b)','moment','Two 25 kg children sit 1.5 m either side of a seesaw pivot. State equilibrium and each turning moment (g = 10).','25 kg குழந்தைகள் ஆதாரத்தின் இருபுறமும் 1.5 m இல் அமர்ந்துள்ளனர். சமநிலையையும் ஒவ்வொரு திருப்புத் திறனையும் காண்க (g = 10).','Each weight = 25 × 10 = 250 N. | Each moment = 250 × 1.5 = 375 N m in opposite senses. Equal clockwise and anticlockwise moments give zero resultant turning moment.','ஒவ்வொரு நிறை = 25 × 10 = 250 N. | திருப்புத் திறன் = 250 × 1.5 = 375 N m; திசைகள் எதிர். இரு திறன்களும் சமமாக இருப்பதால் விளையுள் திருப்புத் திறன் பூச்சியம்.'),
      ('B(iii)(a)','graph','Describe the train graph: v rises 0→3 m/s in 0–5 s, stays 3 m/s until 35 s and falls to zero at 40 s.','புகையிரத வரைபு: 0–5 s இல் v 0→3 m/s, 5–35 s இல் 3 m/s, 40 s இல் பூச்சியம். இயக்கத்தை விளக்குக.','Uniform acceleration a = 3/5 = 0.6 m s⁻² for 5 s; constant velocity for 30 s; uniform deceleration −0.6 m s⁻² for the last 5 s.','முதல் 5 s இல் சீரான ஆர்முடுகல் a = 3/5 = 0.6 m s⁻²; அடுத்த 30 s இல் மாறா வேகம்; இறுதி 5 s இல் −0.6 m s⁻² அமர்முடுகல்.'),
      ('B(iii)(b–c)','motion','For train mass 1500 kg, find momentum from 5–35 s. If the track area is 18 m², find track length.','புகையிரத திணிவு 1500 kg. 5–35 s இல் உந்தம் என்ன? பாதைப் பரப்பு 18 m² எனில் நீளம் என்ன?','p = mv = 1500 × 3 = 4500 kg m s⁻¹. | Lap distance = area under v–t = ½×5×3 + 30×3 + ½×5×3 = 105 m. | Track width = area/length = 18/105 ≈ 0.171 m; asked track length is 105 m.','p = mv = 1500 × 3 = 4500 kg m s⁻¹. | சுற்றுத் தூரம் = v–t பரப்பு = ½×5×3 + 30×3 + ½×5×3 = 105 m. | பாதை அகலம் = பரப்பு/நீளம் = 18/105 ≈ 0.171 m; கேட்கப்பட்ட பாதை நீளம் 105 m.')])
    written(y,9,[12],[
      ('B(i)(a–b)','mirror','Which situation uses a concave mirror, and draw the ray path for a dentist’s enlarged image?','குழிவாடி பயன்படுத்தும் சந்தர்ப்பம் எது? பல் வைத்தியரின் பெரிதாக்கிய விம்பத்திற்கு கதிர்ப்பாதையை விளக்குக.','Situation 1: the dentist inspecting a mouth. Place the tooth inside the focal length. A parallel ray reflects through F; a ray toward the centre of curvature retraces its path. Backward extensions meet behind the mirror, making an upright enlarged virtual image.','சந்தர்ப்பம் 1: பல் வைத்தியர் வாயைப் பரிசோதித்தல். பல் குவியத் தூரத்தினுள் இருக்க வேண்டும். சமாந்தரக் கதிர் F வழியாகத் தெறிக்கும்; வளைவு மையத்தை நோக்கிய கதிர் அதே பாதையில் திரும்பும். பின்னோக்கிய நீட்டிப்புகள் வாடிக்குப் பின்னால் சேர்ந்து நிமிர்ந்த பெரிய மாயவிம்பத்தை உருவாக்கும்.'),
      ('B(ii)(a–d)','refraction','Identify the fibre-optic situation, its principle, necessary conditions and its device.','ஒளியியல் நாரைப் பயன்படுத்தும் சந்தர்ப்பம், தத்துவம், நிபந்தனைகள், சாதனம் என்பவற்றைக் குறிப்பிடுக.','Situation 2: inspecting internal organs. Total internal reflection guides light in the fibre. Light must go from optically denser core to rarer cladding, with incidence above the critical angle. An endoscope uses this effect.','சந்தர்ப்பம் 2: உட்புற அங்கங்களைப் பரிசோதித்தல். முழு அகத்தெறிப்பால் நாரில் ஒளி செல்கிறது. அடர்ந்த மையத்திலிருந்து அரும் உறைக்கு ஒளி செல்ல வேண்டும்; படுகோணம் அவதிக் கோணத்தைவிடப் பெரிதாக வேண்டும். அகநோக்கி இதைப் பயன்படுத்தும்.')])
    y=2017
    mc(y,15,2,'units','Which apparatus accurately measures 26.0 cm³ of solution?','26.0 cm³ கரைசலைத் திருத்தமாக அளக்கும் உபகரணம் எது?', [('Burette','அளவுச் சாடி'),('Beaker','குவளை'),('Pipette','அளவி'),('Volumetric flask','கனவளவுக் குடுவை')],1,'A burette has fine graduations and dispenses a variable measured volume. A fixed-volume pipette or flask does not provide an arbitrary 26.0 cm³.','அளவுச் சாடி நுண் அளவீடுகளுடன் மாறும் கனவளவை வழங்கும். நிலையான கனவளவு அளவி/குடுவை எந்த 26.0 cm³ அளவையும் வழங்காது.')
    mc(y,16,2,'gas','A balloon expands as its gas warms from 20 °C to 60 °C. Which statements are true: (1) volume rises, (2) cold pressure is higher, (3) Charles’s law applies?','வாயு 20 °C இலிருந்து 60 °C இற்கு சூடாகும்போது பலூன் விரியும். (1) கனவளவு அதிகரிக்கும், (2) குளிர் அமுக்கம் அதிகம், (3) சாள்ஸ் விதி பொருந்தும். சரியானவை எவை?',['1 and 2 / 1,2','2 and 3 / 2,3','1 and 3 / 1,3','None / எதுவுமில்லை'],3,'At approximately constant external pressure, V is proportional to absolute T. Warming increases volume; pressure is approximately unchanged.','ஏறத்தாழ மாறா வெளி அமுக்கத்தில் V முழு வெப்பநிலை T இற்கு நேர்விகிதம். சூடாக்கினால் கனவளவு அதிகரிக்கும்; அமுக்கம் ஏறத்தாழ மாறாது.')
    mc(y,22,3,'safety','An electrical appliance catches fire. What must be disconnected before using a fire extinguisher?','மின் சாதனம் தீப்பற்றுகிறது. தீயணைப்பதற்கு முன்னர் எதைத் துண்டிக்க வேண்டும்?', [('Oil','எண்ணெய்'),('Plastic','பிளாஸ்ரிக்'),('Electrical appliance from supply','மின் சாதனத்தின் மின் இணைப்பு'),('Wooden floor','மரத் தளம்')],3,'Disconnect electricity first so the live supply cannot cause shock or continue feeding the fault. Use an appropriate electrical-fire extinguisher.','முதலில் மின் இணைப்பைத் துண்டித்து மின்னதிர்ச்சியையும் பழுதிற்குத் தொடரும் வழங்கலையும் தடுக்கவும். பொருத்தமான மின்தீ அணைப்பானைப் பயன்படுத்தவும்.')
    mc(y,25,3,'units','Select a scalar followed by a vector.','காவிக் கணியம், துணிக்கணியம் என்ற வரிசையில் சரியான தெரிவு எது?', [('Momentum, force','உந்தம், விசை'),('Momentum, mass','உந்தம், திணிவு'),('Distance, mass','தூரம், திணிவு'),('Speed, acceleration','கதி, ஆர்முடுகல்')],4,'Speed has magnitude only. Acceleration has magnitude and direction. Momentum and force are both vectors; mass is scalar.','கதி பருமன் மட்டும் உடையது. ஆர்முடுகல் பருமனும் திசையும் உடையது. உந்தமும் விசையும் துணிக்கணியங்கள்; திணிவு காவிக் கணியம்.')
    mc(y,26,3,'kelvin','Convert 300 K to °C (school approximation).','300 K ஐ °C இற்கு மாற்றுக (பாடசாலை அண்மிப்பு).',['27 °C','30 °C','273 °C','573 °C'],1,'T(°C) = T(K) − 273 = 300 − 273 = 27 °C.','T(°C) = T(K) − 273 = 300 − 273 = 27 °C.')
    mc(y,27,3,'photodiode','Identify the diode symbol with arrows pointing outward.','வெளிநோக்கிய அம்புகளுள்ள இருமுனையக் குறியீட்டை இனங்காண்க.', [('LED','ஒளி இருவாயி'),('Ordinary diode','சேர் இருவாயி'),('NOT gate','NOT படலை'),('OR gate','OR படலை')],1,'Outward arrows represent emitted light: a light-emitting diode. Inward arrows would indicate a photodiode.','வெளிநோக்கிய அம்புகள் வெளியிடப்படும் ஒளியைக் குறிக்கும்; இது LED. உள்நோக்கிய அம்புகள் ஒளியிருமுனையத்தைக் குறிக்கும்.',(.41,.524,.68,.586))
    mc(y,28,3,'waves','Which is NOT a property of electromagnetic waves?','மின்காந்த அலைகளின் இயல்பு அல்லாதது எது?', [('Produced by accelerating charges','ஆர்முடுகும் ஏற்றங்களால் உருவாகும்'),('Carry electric charge','மின்னேற்றத்தைக் கொண்டிருக்கும்'),('Transverse waves','குறுக்கு அலைகள்'),('Obey reflection laws','தெறிப்பு விதிகளுக்கு உட்படும்')],2,'Electromagnetic waves carry energy, not a net electric charge. Their electric and magnetic fields oscillate transverse to propagation.','மின்காந்த அலைகள் சக்தியைக் காவும்; நிகர மின்னேற்றத்தைக் காவாது. மின், காந்தப் புலங்கள் பரவலுக்குக் குறுக்காக அதிரும்.')
    mc(y,29,3,'lenses','Which source ray(s) go through a lens without deviation?','வில்லையூடாகத் திசை மாறாமல் செல்லும் மூலக் கதிர்(கள்) எவை?',['AB','CD','AB, EF','CD, EF'],1,'Ray AB passes through the optical centre and continues straight. CD and EF meet the lens away from the centre and refract.','AB ஒளியியல் மையத்தினூடாகச் சென்று நேராகத் தொடரும். CD, EF மையத்திற்கு வெளியே வில்லையைச் சந்தித்து முறியும்.',(.08,.688,.79,.793))
    mc(y,30,3,'motion','A person walks 15 m east, 6 m south and 15 m west. Find displacement magnitude.','ஒருவர் 15 m கிழக்கு, 6 m தெற்கு, 15 m மேற்கு நடக்கிறார். இடப்பெயர்ச்சிப் பருமன் என்ன?',['6 m','15 m','30 m','36 m'],1,'East and west components cancel. Only 6 m south remains. Distance travelled is 36 m, but displacement is 6 m.','கிழக்கு, மேற்கு கூறுகள் ஒன்றையொன்று நீக்கும். தெற்கு 6 m மட்டும் எஞ்சும். தூரம் 36 m; இடப்பெயர்ச்சி 6 m.')
    mc(y,31,4,'heatcapacity','1 kg water needs 4200 J for a 1 °C rise. Find heat to raise 10 kg by 50 °C.','1 kg நீருக்கு 1 °C உயர்விற்கு 4200 J தேவை. 10 kg நீரை 50 °C உயர்த்த வெப்பம் என்ன?',['21000 J','42000 J','210000 J','2100000 J'],4,'Q = mcΔT = 10 × 4200 × 50 = 2100000 J. Both the mass and temperature rise multiply the specific heat capacity.','Q = mcΔT = 10 × 4200 × 50 = 2100000 J. திணிவும் வெப்பநிலை உயர்வும் தன்வெப்பக் கொள்ளளவுடன் பெருக்கப்படும்.')
    mc(y,32,4,'lenses','Which instruments use two convex lenses: A simple microscope, B compound microscope, C astronomical telescope?','இரு குவிவு வில்லைகளைப் பயன்படுத்துவது எது: A எளிய நுணுக்குக்காட்டி, B கூட்டு நுணுக்குக்காட்டி, C வானியல் தொலைகாட்டி?',['A,B','B,C','A,C','A,B,C'],2,'A compound microscope and a refracting astronomical telescope use objective and eyepiece convex lenses. A simple microscope uses one convex lens.','கூட்டு நுணுக்குக்காட்டியும் முறிக்கும் வானியல் தொலைகாட்டியும் பொருள், பார்வைக் குவிவு வில்லைகளைப் பயன்படுத்தும். எளிய நுணுக்குக்காட்டியில் ஒரு குவிவு வில்லை மட்டுமே உண்டு.')
    mc(y,33,4,'motion','Find momentum of a 2 kg object moving at 4 m s⁻¹.','4 m s⁻¹ வேகத்தில் நகரும் 2 kg பொருளின் உந்தம் என்ன?',['2 kg m s⁻¹','6 kg m s⁻¹','8 kg m s⁻¹','16 kg m s⁻¹'],3,'p = mv = 2 × 4 = 8 kg m s⁻¹, in the direction of velocity.','p = mv = 2 × 4 = 8 kg m s⁻¹; வேகத்தின் திசையிலேயே உந்தம் இருக்கும்.')
    mc(y,34,4,'capacitor','Which affect capacitance: A plate area, B separation, C dielectric material?','கொள்ளளவில் செல்வாக்குச் செலுத்துவது எது: A தகட்டுப் பரப்பு, B இடைவெளி, C மின்காப்புப் பொருள்?',['A,B','B,C','A,C','A,B,C'],4,'C = εA/d. Area A increases capacitance, separation d decreases it, and the dielectric determines ε. All three matter.','C = εA/d. பரப்பு அதிகரித்தால் கொள்ளளவு அதிகரிக்கும்; இடைவெளி அதிகரித்தால் குறையும்; மின்காப்பு ε ஐ நிர்ணயிக்கும். மூன்றும் முக்கியம்.')
    mc(y,35,4,'doping','Which doping produces a p-type semiconductor?','p-வகை அரைக்கடத்தியை உருவாக்கும் கலப்பு எது?', [('Ge with phosphorus','ஜெர்மேனியத்துடன் பொசுபரசு'),('Si with aluminium','சிலிக்கனுடன் அலுமினியம்'),('Ge with antimony','ஜெர்மேனியத்துடன் அன்ரிமனி'),('Ge with silicon','ஜெர்மேனியத்துடன் சிலிக்கன்')],2,'Aluminium is trivalent. In tetravalent silicon it leaves holes, making p-type material. Pentavalent impurities produce n-type material.','அலுமினியம் மூன்று வலுவளவுடையது. நான்கு வலுவளவு சிலிக்கனில் துளைகளை உருவாக்கி p-வகையைத் தரும். ஐந்து வலுவளவுக் கலப்பு n-வகையைத் தரும்.')
    mc(y,36,4,'refraction','A coin is 26 cm below water; refractive index is 1.3. Find its apparent depth from above.','நீரில் நாணயம் 26 cm ஆழத்தில் உள்ளது; முறிவுச் சுட்டி 1.3. மேலிருந்து தோற்ற ஆழம் என்ன?',['2.0 cm','2.6 cm','13.0 cm','20.0 cm'],4,'n = real depth/apparent depth. Apparent depth = 26/1.3 = 20 cm, so the coin appears raised by 6 cm.','n = மெய்யாழம்/தோற்ற ஆழம். தோற்ற ஆழம் = 26/1.3 = 20 cm; நாணயம் 6 cm உயர்ந்ததாகத் தோன்றும்.')
    written(y,1,[6],[('iv(a–b)','graph','A distance–time graph is a straight line from 0 to 100 m in 40 s. Find AB and speed.','தூரம்–நேர நேர்கோடு 0 இலிருந்து 40 s இல் 100 m அடையும். AB தூரத்தையும் கதியையும் காண்க.','AB = 100 m. | Speed = slope = distance/time = 100/40 = 2.5 m s⁻¹. A straight line means constant speed.','AB = 100 m. | கதி = சாய்வு = தூரம்/நேரம் = 100/40 = 2.5 m s⁻¹. நேர்கோடு மாறா கதியைக் குறிக்கும்.')])
    written(y,4,[7,8],[
      ('i–iii','ohm','Identify R and S, explain the circuit error and correct the two-cell connection.','R, S ஐ இனங்கண்டு சுற்றின் பிழையையும் இரு கலங்களின் சரியான இணைப்பையும் குறிப்பிடுக.','R is an ammeter (circle with A); S is a cell (unequal parallel lines). The two 1.5 V cells oppose each other, giving zero net emf. Connect the positive of one to the negative of the other for 3 V in series, keeping the ammeter in series.','R அம்மீற்றர் (A கொண்ட வட்டம்); S கலம் (சமமற்ற கோடுகள்). இரு 1.5 V கலங்கள் எதிராக இருப்பதால் நிகர மின்னியக்க விசை பூச்சியம். ஒன்றின் நேர்முனையை மற்றதின் மறைமுனையுடன் இணைத்து தொடரில் 3 V பெறுக; அம்மீற்றரைத் தொடரில் வைத்திருக்கவும்.'),
      ('iv(a–b)','ohm','After correction, current is 1.5 A through a 2 cm nichrome wire. Find resistance and two factors affecting it.','திருத்திய பின்னர் 2 cm நைக்குரோம் கம்பியில் 1.5 A செல்கிறது. தடையையும் இரு காரணிகளையும் காண்க.','V = 1.5 + 1.5 = 3 V. | R = V/I = 3/1.5 = 2 Ω. Resistance depends on length and cross-sectional area; material and temperature also matter.','V = 1.5 + 1.5 = 3 V. | R = V/I = 3/1.5 = 2 Ω. தடை நீளத்திலும் குறுக்குவெட்டுப் பரப்பிலும் தங்கும்; பொருளும் வெப்பநிலையும் முக்கியம்.'),
      ('v(a–b)','circuit','A 6 cm wire has resistance 6 Ω. Combine it with the 2 Ω wire to obtain 1.5 Ω, and show the calculation.','6 cm கம்பியின் தடை 6 Ω. அதை 2 Ω கம்பியுடன் இணைத்து 1.5 Ω பெறும் முறையையும் கணிப்பையும் காட்டுக.','Use parallel connection: both wires span the same two circuit nodes. | 1/R = 1/2 + 1/6 = 4/6, so R = 6/4 = 1.5 Ω. A series connection would give 8 Ω.','இரு கம்பிகளையும் ஒரே இரு முனைகளுக்கிடையில் சமாந்தரமாக இணைக்கவும். | 1/R = 1/2 + 1/6 = 4/6; R = 6/4 = 1.5 Ω. தொடர் இணைப்பு 8 Ω தரும்.')])
    written(y,9,[11,12],[
      ('i–iii','buoyancy','A full bucket has mass 5 kg (g = 10). Find its weight, the hand load in air and the change when fully immersed; describe its force diagram.','நிரம்பிய வாளியின் திணிவு 5 kg (g = 10). நிறை, வளியில் கை உணரும் சுமை, நீரில் அமிழ்ந்தபோது மாற்றம், விசைப் படம் என்பவற்றைக் குறிப்பிடுக.','W = mg = 5 × 10 = 50 N. In air the hand tension is approximately 50 N. In water, upward buoyancy reduces apparent load: T = W − U. Draw downward W, upward U and upward T; equilibrium gives T + U = W.','W = mg = 5 × 10 = 50 N. வளியில் கை இழுவை ஏறத்தாழ 50 N. நீரில் மேலுதைப்பு சுமையைக் குறைக்கும்: T = W − U. கீழே W, மேலே U, T; சமநிலைக்கு T + U = W.'),
      ('iv(a–f)','machines','A fixed pulley lifts the 50 N bucket with mechanical advantage 0.9. Name the machine, its benefit, effort, changes during lifting, velocity ratio and efficiency.','நிலைக் கப்பியின் பொறிமுறை நயம் 0.9; 50 N வாளியை உயர்த்துகிறது. பெயர், நன்மை, எத்தனம், உயரும்போது மாற்றம், வேகவிகிதம், திறன் என்பவற்றைக் காண்க.','It is a single fixed pulley; it changes effort direction. | MA = load/effort, so effort = 50/0.9 ≈ 55.6 N. Below ground near water, buoyancy can reduce the initial effort; once clear, the full load is lifted. | VR = 1; efficiency = MA/VR × 100 = 90%.','இது ஒற்றை நிலைக் கப்பி; எத்தனத்தின் திசையை மாற்றும். | MA = சுமை/எத்தனம்; எத்தனம் = 50/0.9 ≈ 55.6 N. நீரருகில் மேலுதைப்பு ஆரம்ப எத்தனத்தைக் குறைக்கும்; நீரிலிருந்து வெளியே வந்ததும் முழுச் சுமை உயர்த்தப்படும். | VR = 1; திறன் = MA/VR × 100 = 90%.'),
      ('iv(g)','potential','The bucket is 10 m below the pulley. Take potential energy at the pulley as zero; find its initial potential energy.','கப்பியிலிருந்து வாளி 10 m கீழே உள்ளது. கப்பியில் அழுத்தச் சக்தி பூச்சியம் எனில் வாளியின் தொடக்க அழுத்தச் சக்தி என்ன?','Height relative to the chosen zero is h = −10 m. | Ep = mgh = 5 × 10 × (−10) = −500 J. A negative value is valid because potential energy depends on the reference level.','தெரிவு செய்த பூச்சிய மட்டத்திற்குச் சார்பாக h = −10 m. | Ep = mgh = 5 × 10 × (−10) = −500 J. அழுத்தச் சக்தி சார்பு மட்டத்தில் தங்குவதால் மறைப் பெறுமானம் பொருத்தமானது.')])
    written(y,10,[12],[
      ('A(i–iii)','timbre','Identify instruments with vibrating strings and an air column; state two ways to raise violin pitch and explain same-note differences between violin and flute.','அதிரும் நரம்பு, வளிநிரல் உள்ள கருவிகளை இனங்காண்க; வயலின் சுருதியை உயர்த்த இரு முறைகளையும் வயலின்/புல்லாங்குழல் ஒரே குறிப்பு வேறுபாட்டையும் கூறுக.','Violin: strings; flute: air column. Shorten the vibrating string or increase its tension to raise frequency and pitch. The same note has the same fundamental frequency, but different harmonics give different timbre.','வயலின்: நரம்புகள்; புல்லாங்குழல்: வளிநிரல். அதிரும் நரம்பைக் குறுக்கவும் அல்லது இழுவையை அதிகரிக்கவும்; மீடிறனும் சுருதியும் உயரும். ஒரே குறிப்பிற்கு அடிப்படை மீடிறன் சமம்; வேறுபட்ட மேற்றோன்கள் ஒலிப் பண்பை வேறுபடுத்தும்.'),
      ('B(i)(a–e)','sounddistance','Name the depth-measuring device/principle. Sound frequency is 2920 Hz, speed 1460 m/s and echo time 20 s. Find depth and wavelength.','ஆழமளக்கும் சாதனம்/தத்துவத்தைப் பெயரிடுக. ஒலி மீடிறன் 2920 Hz, கதி 1460 m/s, எதிரொலி நேரம் 20 s. ஆழத்தையும் அலைநீளத்தையும் காண்க.','Echo sounder/SONAR uses reflection of ultrasound. | h = vt/2 = 1460 × 20/2 = 14600 m (two-way journey). | λ = v/f = 1460/2920 = 0.5 m.','எதிரொலி ஆழமானி/SONAR கழியொலியின் தெறிப்பைப் பயன்படுத்தும். | h = vt/2 = 1460 × 20/2 = 14600 m (சென்று திரும்பும் பயணம்). | λ = v/f = 1460/2920 = 0.5 m.'),
      ('B(ii)(a–b)','pressure','Write pressure in terms of depth h, density d and g. Calculate it for d = 1100 kg m⁻³ at the depth above.','h ஆழம், d அடர்த்தி, g கொண்டு அமுக்கச் சமன்பாட்டை எழுதி மேலுள்ள ஆழத்தில் d = 1100 kg m⁻³ எனில் கணிக்கவும்.','p = dgh (water-only pressure). | p = 1100 × 10 × 14600 = 160600000 Pa = 1.606 × 10⁸ Pa. The 1000 kg stored waste mass is not needed for water pressure.','p = dgh (நீரால் மட்டும் அமுக்கம்). | p = 1100 × 10 × 14600 = 160600000 Pa = 1.606 × 10⁸ Pa. நீரமுக்கத்திற்கு 1000 kg கழிவுத் திணிவு தேவையில்லை.')])
