from expanded_physics import mc,written

def add():
    y=2020
    mc(y,3,1,'units','What is the SI unit of momentum?','உந்தத்தின் SI அலகு என்ன?',['kg m s⁻¹','kg m s⁻²','kg m⁻¹ s⁻¹','kg m² s⁻²'],1,'p = mv, so its unit is kg × m s⁻¹ = kg m s⁻¹.','p = mv; அலகு kg × m s⁻¹ = kg m s⁻¹.')
    mc(y,6,1,'radiation','How does heat travel from the Sun to Earth?','சூரியனிலிருந்து புவிக்கு வெப்பம் எவ்வாறு வருகிறது?', [('Radiation','கதிர்வீசல்'),('Conduction','கடத்தல்'),('Convection','உடன்காவல்'),('Radiation and convection','கதிர்வீசலும் உடன்காவலும்')],1,'Space is largely vacuum. Electromagnetic radiation crosses it; conduction and convection require matter.','விண்வெளி பெரும்பாலும் வெற்றிடம். மின்காந்தக் கதிர்வீசல் அதனூடாக வரும்; கடத்தல், உடன்காவலுக்கு சடப்பொருள் தேவை.')
    mc(y,8,1,'graph','A displacement–time graph is straight to t1, then its positive slope decreases to t2. Describe the two intervals.','இடப்பெயர்ச்சி–நேர வரைபு t1 வரை நேர்கோடு; பின்னர் நேர் சாய்வு t2 வரை குறைகிறது. இரு பகுதிகளின் இயக்கம் என்ன?', [('Constant speed, acceleration','சீரான கதி, ஆர்முடுகல்'),('Constant speed, deceleration','சீரான கதி, அமர்முடுகல்'),('Acceleration, deceleration','ஆர்முடுகல், அமர்முடுகல்'),('Acceleration, acceleration','ஆர்முடுகல், ஆர்முடுகல்')],2,'Slope of displacement–time is velocity. Constant slope gives constant velocity; decreasing positive slope means slowing down.','இடப்பெயர்ச்சி–நேர சாய்வு வேகம். மாறா சாய்வு மாறா வேகத்தையும் குறையும் நேர் சாய்வு அமர்முடுகலையும் காட்டும்.')
    mc(y,11,2,'motion','Which statement about displacement magnitude is always true?','இடப்பெயர்ச்சிப் பருமனைப் பற்றிய எக்காலமும் உண்மையான கூற்று எது?', [('Greater than distance','தூரத்தைவிடப் பெரியது'),('Equal to distance','தூரத்திற்குச் சமம்'),('Less than distance','தூரத்தைவிடக் குறைவு'),('Equal to or less than distance','தூரத்திற்குச் சமம் அல்லது குறைவு')],4,'A straight one-way path gives equality. Any detour or reversal increases distance without increasing the straight-line displacement equally.','ஒரே திசை நேர்ப்பாதையில் சமம். விலகலும் திரும்புதலும் தூரத்தை அதிகரிக்கும்; நேரான இடப்பெயர்ச்சி அதேபடி அதிகரிக்காது.')
    mc(y,20,2,'refraction','Which diagram shows total internal reflection from glass toward air?','கண்ணாடியிலிருந்து வளிக்கு முழு அகத்தெறிப்பைக் காட்டும் படம் எது?',['Diagram 1 / படம் 1','Diagram 2 / படம் 2','Diagram 3 / படம் 3','Diagram 4 / படம் 4'],1,'The ray remains completely in glass and reflection angle equals incidence. At the critical angle the refracted ray would instead lie along the surface (diagram 3).','கதிர் முழுவதும் கண்ணாடியிலேயே தெறிக்கும்; தெறிப்புக் கோணம் படுகோணத்திற்குச் சமம். அவதிக் கோணத்தில் முறிந்த கதிர் மேற்பரப்போடு செல்லும் (படம் 3).',(.06,.728,.94,.942))
    mc(y,23,3,'circuit','Which source connection adds two 1.5 V cells to give 3 V?','இரு 1.5 V கலங்களை 3 V ஆக இணைக்கும் மூலப் படம் எது?',['Diagram 1 / படம் 1','Diagram 2 / படம் 2','Diagram 3 / படம் 3','Diagram 4 / படம் 4'],3,'A series-aiding connection joins positive of one cell to negative of the other. Voltages add: 1.5 + 1.5 = 3 V. Parallel cells retain 1.5 V.','தொடர் இணைப்பில் ஒரு கலத்தின் நேர்முனை மற்றதின் மறைமுனையுடன் இணைக்கப்படும். 1.5 + 1.5 = 3 V. சமாந்தரக் கலங்கள் 1.5 V தரும்.',(.075,.201,.91,.332))
    mc(y,27,3,'buoyancy','An object’s weight equals the upthrust when submerged in water. What can it do?','நீரில் அமிழ்ந்த பொருளின் நிறை மேலுதைப்பிற்குச் சமம். அது எவ்வாறு இருக்கலாம்?', [('Float with most above water','பெரும்பகுதி வெளியே மிதக்கும்'),('Float half submerged','அரை அமிழ்ந்து மிதக்கும்'),('Remain fully submerged in equilibrium','முழுமையாக அமிழ்ந்து சமநிலையில் இருக்கும்'),('Sink to bottom','அடிக்குச் செல்லும்')],3,'When fully submerged U = W, net vertical force is zero. It can remain suspended (neutral buoyancy), rather than necessarily rising or sinking.','முழு அமிழ்வில் U = W; நிகர செங்குத்து விசை பூச்சியம். அவசியம் மேலே/கீழே செல்லாமல் நடுநிலை மிதப்பில் இருக்கலாம்.')
    mc(y,29,3,'moment','Two opposite tangential forces of 5 N act on a wheel of radius 0.4 m. Find couple moment.','0.4 m ஆரமுள்ள சில்லில் எதிரான 5 N தொடுகோட்டு விசைகள் தாக்குகின்றன. விசை இணைத் திறன் என்ன?',['5×0.4 N m','5×0.8 N m','5×5×0.4 N m','5×5×0.8 N m'],2,'A couple moment is one force times perpendicular separation. Separation = diameter = 2×0.4 = 0.8 m. Moment = 5×0.8 = 4 N m.','விசை இணைத் திறன் = ஒரு விசை × செங்குத்துப் பிரிப்பு. பிரிப்பு = விட்டம் = 2×0.4 = 0.8 m. திறன் = 5×0.8 = 4 N m.')
    mc(y,33,3,'magnetic','Current points upward and magnetic field to the right. Find the force direction.','மின்னோட்டம் மேலே, காந்தப் புலம் வலப்பக்கம். விசையின் திசை என்ன?', [('Left in page','தாளில் இடப்பக்கம்'),('Right in page','தாளில் வலப்பக்கம்'),('Into page','தாளுக்குள்'),('Out of page','தாளிலிருந்து வெளியே')],3,'Use Fleming’s left-hand rule (or I L × B). Upward current crossed with rightward field gives force into the page.','பிளெமிங்கின் இடக்கை விதியைப் பயன்படுத்துக (அல்லது I L × B). மேல்நோக்கிய மின்னோட்டமும் வலப்புலமும் தாளுக்குள் விசை தரும்.')
    mc(y,34,4,'heatcapacity','Select the graph for pure ice at −10 °C heated to water and then boiling at ordinary pressure.','−10 °C தூய பனியை நீராக்கிப் பின்னர் சாதாரண அமுக்கத்தில் கொதிக்கச் செய்யும் வரைபு எது?',['Diagram 1 / படம் 1','Diagram 2 / படம் 2','Diagram 3 / படம் 3','Diagram 4 / படம் 4'],2,'Temperature rises −10→0 °C, stays at 0 during melting, rises 0→100, then stays at 100 during boiling. Both plateaus represent latent heat.','வெப்பநிலை −10→0 °C உயரும்; உருகும்போது 0 இல் மாறாது; 0→100 உயரும்; கொதிக்கும்போது 100 இல் மாறாது. இரு சமப்பகுதிகளும் மறை வெப்பத்தைக் குறிக்கும்.',(.07,.073,.9,.278))
    mc(y,37,4,'forces','Forces 4 N and 3 N act at an angle. Which are true: A maximum resultant 7 N; B minimum 1 N; C always 5 N?','4 N, 3 N கோணத்தில் தாக்குகின்றன. A அதிகபட்சம் 7 N; B குறைந்தபட்சம் 1 N; C எப்போதும் 5 N. உண்மையானவை எவை?',['A only / A மட்டும்','B only / B மட்டும்','C only / C மட்டும்','A,B only / A,B மட்டும்'],4,'Same direction: 4+3 = 7 N. Opposite: 4−3 = 1 N. A 5 N resultant applies only for perpendicular forces, from √(4²+3²).','ஒரே திசை: 4+3 = 7 N. எதிர்த்திசை: 4−3 = 1 N. செங்குத்தாக இருந்தால் மட்டும் √(4²+3²) = 5 N.')
    mc(y,38,4,'induction','A moving magnet induces current through a lamp and oppositely directed parallel LEDs. Which illuminate during insertion and withdrawal?','அசையும் காந்தம் குமிழிலும் எதிர்த் திசைச் சமாந்தர LED களிலும் மின்னோட்டம் தூண்டும். உள்ளே/வெளியே நகரும்போது ஒளிர்வது எது?', [('Lamp and one LED each time','ஒவ்வொரு முறையும் குமிழும் ஒரு LED உம்'),('Only one LED each time','ஒவ்வொரு முறையும் LED மட்டும்'),('Only lamp on insertion','உள்ளே குமிழ் மட்டும்'),('Only one LED on withdrawal','வெளியே LED மட்டும்')],1,'Both movements change flux, but induced current reverses direction. The lamp lights for either direction; only the forward-biased LED lights, alternating between LEDs.','இரு இயக்கங்களும் பாயத்தை மாற்றும்; மின்னோட்டத் திசை மாறும். குமிழ் இருதிசையிலும் ஒளிரும்; முன்னோக்கிச் சார்புள்ள ஒரு LED மட்டும் ஒளிர்ந்து அடுத்த இயக்கத்தில் மற்றது ஒளிரும்.')
    written(y,7,[6],[
      ('A(i–ii)','lenses','Identify the hand magnifier lens and where tiny print must be placed.','கைவில்லையின் வகையையும் சிறிய எழுத்துகளை வைக்கும் இடத்தையும் கூறுக.','A convex lens. Place the print between the optical centre and principal focus; it produces an upright enlarged virtual image.','குவிவு வில்லை. எழுத்துகளை ஒளியியல் மையத்திற்கும் முதலான குவியத்திற்கும் இடையில் வைக்க; நிமிர்ந்த பெரிய மாயவிம்பம் கிடைக்கும்.'),
      ('A(iii–iv)','lenses','How does a hand lens focus sunlight onto dry cotton, and can a concave lens do this?','கைவில்லை சூரிய ஒளியை உலர் பஞ்சில் எவ்வாறு குவிக்கும்? குழிவு வில்லையால் முடியுமா?','Parallel sunlight refracts toward the principal focus of a convex lens, concentrating energy. A concave lens diverges parallel rays and cannot form this real focused spot.','சமாந்தர சூரியக் கதிர்கள் குவிவு வில்லையின் முதலான குவியத்திற்கு முறிந்து சக்தியைக் குவிக்கும். குழிவு வில்லை கதிர்களை விரிக்கும்; மெய்யான குவிந்த புள்ளியை உருவாக்காது.'),
      ('A(v–vi)','lenses','A distant tree is projected onto a wall with the lens. State two image properties and another instrument using this lens.','தொலை மரம் வில்லையால் சுவரில் விம்பமாக்கப்படுகிறது. இரு விம்ப இயல்புகளும் மற்றொரு சாதனமும் என்ன?','The image on the wall is real and inverted, usually diminished for a distant object. A camera or projector also uses a convex lens.','சுவரிலுள்ள விம்பம் மெய்யானது, தலைகீழானது; தொலைப் பொருளிற்கு பொதுவாகச் சிறியது. கமரா அல்லது படவீழ்த்தி குவிவு வில்லையைப் பயன்படுத்தும்.'),
      ('B(i)(a–b)','energy','A 1000 kg car moving at 20 m/s brakes. Find initial kinetic energy and two energy transformations.','1000 kg கார் 20 m/s இல் சென்று தடுக்கப்படுகிறது. தொடக்க இயக்கச் சக்தியும் இரு மாற்றங்களும் என்ன?','Ek = ½mv² = ½×1000×20² = 200000 J. Braking converts kinetic energy mainly into thermal energy in brakes/tyres/road, with some sound.','Ek = ½mv² = ½×1000×20² = 200000 J. தடைப்பில் இயக்கச் சக்தி பெரும்பாலும் தடை/சக்கரம்/வீதியில் வெப்பமாகவும் சிறிது ஒலியாகவும் மாறும்.'),
      ('B(ii)(a–d)','induction','Name the electric-car device converting braking motion to electricity, explain its principle, name the driving device and find 4 V cell count for 400 V.','தடைப்பில் இயக்கத்தை மின்சாரமாக மாற்றும் சாதனம், தத்துவம், இயக்கும் சாதனம், 400 V இற்கான 4 V கல எண்ணிக்கை என்ன?','A generator converts motion to electricity by electromagnetic induction during regenerative braking. An electric motor converts battery electricity to motion. | Series cell count = 400/4 = 100.','பிறப்பாக்கி மீளுருவாக்கத் தடைப்பில் மின்காந்தத் தூண்டலால் இயக்கத்தை மின்சாரமாக மாற்றும். மின் மோட்டர் பற்றரி மின்சாரத்தை இயக்கமாக மாற்றும். | தொடர் கல எண்ணிக்கை = 400/4 = 100.')])
    written(y,8,[7],[
      ('B(i)(a–b)','pressure','Two identical taps are at different heights on a water tank. Which gives faster flow, and why?','தொட்டியில் வெவ்வேறு உயரத்தில் இரு ஒத்த குழாய்கள். எதில் விரைவாக நீர் வெளியேறும்? ஏன்?','The lower tap has greater water depth above it and thus greater pressure p = ρgh. This larger pressure difference drives a faster jet.','கீழுள்ள குழாயிற்கு மேலே அதிக நீர் ஆழம் இருப்பதால் p = ρgh அதிகம். பெரிய அமுக்க வேறுபாடு விரைவான நீர்ப் பீச்சை ஏற்படுத்தும்.'),
      ('B(ii)(a–b)','pressure','A tank has base area 1 m², height 1 m, ρ = 1000 and g = 10. Find full water mass and base pressure.','தொட்டி அடிப்பரப்பு 1 m², உயரம் 1 m, ρ = 1000, g = 10. நிரம்பிய நீர்த் திணிவும் அடியமுக்கமும் என்ன?','V = Ah = 1×1 = 1 m³. | m = ρV = 1000×1 = 1000 kg. | p = ρgh = 1000×10×1 = 10000 Pa (water only).','V = Ah = 1×1 = 1 m³. | m = ρV = 1000×1 = 1000 kg. | p = ρgh = 1000×10×1 = 10000 Pa (நீர் மட்டும்).'),
      ('B(iii)(a–c)','buoyancy','Explain the float valve: force on float, change as it starts to enter water, and advantage of the lever.','மிதவை வால்வில் விசை, நீரில் அமிழத் தொடங்கியபின் மாற்றம், நெம்பின் நன்மை என்பவற்றை விளக்குக.','Upthrust acts upward on the float. More submerged volume displaces more water, increasing upthrust until the float rises and the lever closes the valve. The lever amplifies the float’s closing effect, stopping inflow automatically.','மிதவையில் மேலுதைப்பு மேல்நோக்கித் தாக்கும். அமிழ்ந்த கனவளவு அதிகரித்தால் இடம்பெயர்ந்த நீரும் மேலுதைப்பும் அதிகரித்து நெம்பு வால்வை மூடும். நெம்பு மிதவையின் மூடும் விளைவை அதிகரித்து உள்வரவைத் தானாக நிறுத்தும்.')])
    written(y,9,[8],[
      ('B(i)(a–b)','transformer','A 240 V AC supply is reduced to 12 V. Name transformer type and which coil needs thicker wire.','240 V ஆடலோட்டம் 12 V ஆகக் குறைக்கப்படுகிறது. நிலைமாற்றி வகையும் தடித்த கம்பி தேவைப்படும் சுருளும் என்ன?','Step-down transformer. The secondary carries a larger current (approximately 20 times primary for an ideal transformer), so use thicker secondary wire to reduce resistance/heating.','இறக்கும் நிலைமாற்றி. துணைச் சுருளில் அதிக மின்னோட்டம் (இலட்சிய நிலையில் முதன்மையின் சுமார் 20 மடங்கு) செல்கிறது; தடித்த துணைக் கம்பி தடை/வெப்பத்தைக் குறைக்கும்.'),
      ('B(ii)','transformer','Primary turns are 1800, primary voltage 240 V and secondary 12 V. Find secondary turns.','முதன்மை 1800 முறுக்குகள், 240 V; துணை 12 V. துணை முறுக்குகள் என்ன?','Ns/Np = Vs/Vp. | Ns = 1800×12/240 = 90 turns.','Ns/Np = Vs/Vp. | Ns = 1800×12/240 = 90 முறுக்குகள்.'),
      ('B(iii–v)','capacitor','Sketch the 12 V AC waveform, describe four-diode full-wave rectification and name the smoothing component X.','12 V ஆடலோட்ட வரைபு, நான்கு இருமுனைய முழு அலைச் சீராக்கம், ஒப்பமாக்கி X என்பவற்றைக் கூறுக.','AC has alternating positive/negative sinusoidal halves (12 V is normally an rms rating). A bridge rectifier uses four diodes, with alternate pairs conducting so load current keeps one direction. X is a smoothing capacitor across the load, charging at peaks and discharging between them.','ஆடலோட்டத்தில் நேர்/மறை சைன் அரைப்பகுதிகள் (12 V பொதுவாக rms குறிப்பு). பாலச் சீராக்கியில் நான்கு இருமுனையங்கள்; மாறும் ஜோடிகள் கடத்தி சுமை மின்னோட்டத்தை ஒரே திசையில் பேணும். X சுமைக்குச் சமாந்தர ஒப்பமாக்கும் கொள்ளளவி; உச்சங்களில் ஏற்றம் பெற்று இடையில் இறங்கும்.')])
    y=2021
    mc(y,3,1,'units','What is the SI unit of work?','வேலையின் SI அலகு என்ன?',['kg m s⁻¹','kg m s⁻²','kg m⁻¹ s⁻¹','kg m² s⁻²'],4,'W = force × distance. N m = kg m s⁻² × m = kg m² s⁻² = J.','வேலை = விசை × தூரம். N m = kg m s⁻² × m = kg m² s⁻² = J.')
    mc(y,6,1,'motion','For motion at constant acceleration, which quantity increases uniformly?','மாறா ஆர்முடுகலுடன் இயங்கும்போது சீராக அதிகரிக்கும் கணியம் எது?', [('Distance','தூரம்'),('Displacement','இடப்பெயர்ச்சி'),('Velocity','வேகம்'),('Acceleration','ஆர்முடுகல்')],3,'v = u + at. With fixed positive acceleration, equal time intervals add equal velocity increments; displacement changes quadratically.','v = u + at. மாறா நேர் ஆர்முடுகலில் சம நேரங்களுக்கு சம வேக உயர்வுகள்; இடப்பெயர்ச்சி இரண்டாம் படியாக மாறும்.')
    mc(y,8,1,'heatcapacity','Why is water suitable as a car-engine coolant?','மோட்டர் எஞ்சின் குளிர்ச்சியாக்கியாக நீர் பொருத்தமானதற்கு காரணம் என்ன?', [('High specific heat capacity','உயர் தன்வெப்பக் கொள்ளளவு'),('High boiling point only','உயர் கொதிநிலை மட்டும்'),('Colourless','நிறமற்றது'),('High density','உயர் அடர்த்தி')],1,'Q = mcΔT. A high c lets water absorb substantial heat for a modest temperature rise.','Q = mcΔT. உயர் c காரணமாகக் குறைந்த வெப்பநிலை உயர்விற்கு நீர் அதிக வெப்பத்தை உறிஞ்சும்.')
    mc(y,14,2,'mirror','What image is always formed by a convex mirror?','குவிவாடி எப்போதும் உருவாக்கும் விம்பம் எது?', [('Real and diminished','மெய், சிறியது'),('Real and enlarged','மெய், பெரியது'),('Virtual and diminished','மாயம், சிறியது'),('Virtual and enlarged','மாயம், பெரியது')],3,'Reflected rays diverge; backward extensions meet behind the mirror. The image is virtual, upright and smaller for a real object in front.','தெறித்த கதிர்கள் விரியும்; பின்நீட்டிப்புகள் வாடிக்குப் பின்னால் சந்திக்கும். முன்னாலுள்ள மெய்ப்பொருளுக்கு விம்பம் மாயம், நிமிர்ந்தது, சிறியது.')
    mc(y,19,2,'potential','A 10 kg object falls freely from rest through 5 m (g = 10). Find impact speed, ignoring air resistance.','10 kg பொருள் ஓய்விலிருந்து 5 m விழுகிறது (g = 10). வளித் தடையைப் புறக்கணித்து இறுதி கதி என்ன?',['5 m/s','10 m/s','50 m/s','100 m/s'],2,'mgh = ½mv²; mass cancels. v = √(2gh) = √(2×10×5) = 10 m/s.','mgh = ½mv²; திணிவு நீங்கும். v = √(2gh) = √(2×10×5) = 10 m/s.')
    mc(y,21,3,'circuit','Which arrangement of four equal resistors has the least resistance?','நான்கு சமத் தடைகளில் குறைந்த சமவலுத் தடை தரும் இணைப்பு எது?', [('Four series','நான்கும் தொடர்'),('Two series, two parallel','இரண்டு தொடர், இரண்டு சமாந்தரம்'),('One series, three parallel','ஒன்று தொடர், மூன்று சமாந்தரம்'),('Four parallel','நான்கும் சமாந்தரம்')],4,'Four parallel resistors give R/4. The other configurations include series contributions and have larger total resistance.','நான்கு சமாந்தரத் தடைகள் R/4 தரும். ஏனைய அமைப்புகளில் தொடர் பங்களிப்புகள் இருப்பதால் சமவலுத் தடை பெரியது.')
    mc(y,24,3,'circuit','Compare brightness: A bulb alone, B bulb with series resistor, C bulb bypassed by wire.','ஒளிர்வை ஒப்பிடுக: A குமிழ் மட்டும்; B தொடர் தடையுடன்; C கம்பியால் குறுக்கிணைந்த குமிழ்.',['A > B > C','A > C > B','B > C > A','C > A > B'],1,'A gets full supply. B has reduced current from the series resistor. C has near-zero voltage across the bulb because the bypass shorts it, so it is off.','A முழு வழங்கலைப் பெறும். B இல் தொடர் தடை மின்னோட்டத்தைக் குறைக்கும். C இல் குறுக்கிணைப்பு குமிழ் வோல்ற்றளவை ஏறத்தாழ பூச்சியமாக்குவதால் அணையும்.')
    mc(y,28,4,'buoyancy','Which cannot be explained by Archimedes’ principle?','ஆக்கிமிடீஸ் தத்துவத்தால் விளக்க முடியாதது எது?', [('Ship sinks more in river than sea','கப்பல் ஆற்றில் அதிகம் அமிழும்'),('Helium balloon rises','ஹீலியம் பலூன் உயரும்'),('A straw floats in salt solution','உப்புக் கரைசலில் வைக்கோல் மிதக்கும்'),('Hydraulic jack lifts a heavy load','ஐதராலிக் மூலம் பெரிய சுமை உயர்த்துதல்')],4,'A hydraulic jack uses Pascal’s principle: applied fluid pressure is transmitted through the enclosed liquid. The other effects concern buoyancy and displaced fluid weight.','ஐதராலிக் ஜக் பஸ்கால் தத்துவம்: மூடிய திரவத்தில் பிரயோகித்த அமுக்கம் பரவும். ஏனையவை இடம்பெயர்ந்த பாயியின் நிறையும் மேலுதைப்பும் தொடர்பானவை.')
    mc(y,29,4,'moment','Where on a cylinder is the least horizontal force needed to roll it up a step: A low, B upper-left, C top, D upper-right?','சிலிண்டரைப் படியில் ஏற்ற குறைந்த கிடை விசையை எங்கு பிரயோகிக்க வேண்டும்: A கீழ், B மேல் இடது, C உச்சி, D மேல் வலது?',['A','B','C','D'],3,'The step edge acts as a pivot. A horizontal force at the top has the largest perpendicular distance from that pivot, giving the most turning moment per newton.','படியின் விளிம்பு ஆதாரம். உச்சியில் கிடை விசைக்கு ஆதாரத்திலிருந்து செங்குத்துத் தூரம் மிகப்பெரியது; ஒரு நியூட்டனுக்கு அதிக திறன் கிடைக்கும்.')
    mc(y,32,4,'transistor','Choose base, emitter and collector types of an npn transistor.','npn திரான்சிஸ்ரரின் அடி, காலி, சேகரிப்பான் வகைகளைத் தேர்க.',['p,n,n','n,p,n','p,n,p','n,n,p'],1,'The npn layers are emitter n, base p and collector n. In the requested base–emitter–collector order: p,n,n.','npn பகுதிகள் காலி n, அடி p, சேகரிப்பான் n. கேட்கப்பட்ட அடி–காலி–சேகரிப்பான் வரிசையில் p,n,n.')
    mc(y,33,4,'waves','A transverse wave has crest height 4 cm above equilibrium; opposite zero crossings are 5 cm apart. Find amplitude and wavelength.','குறுக்கு அலையின் முகடு சமநிலையிலிருந்து 4 cm; எதிரான பூச்சியச் சந்திப்புகள் 5 cm இடைவெளி. வீச்சும் அலைநீளமும் என்ன?', ['4 cm, 5 cm','4 cm, 10 cm','5 cm, 4 cm','8 cm, 10 cm'],2,'Amplitude is the one-sided displacement: 4 cm. Consecutive opposite-phase zero crossings span λ/2 = 5 cm, so λ = 10 cm.','வீச்சு ஒருபக்க இடப்பெயர்ச்சி 4 cm. எதிர் நிலைப் பூச்சியச் சந்திப்புகள் λ/2 = 5 cm; λ = 10 cm.')
    mc(y,36,5,'transformer','Choose the ideal-transformer voltage/turns relation.','இலட்சிய நிலைமாற்றியின் வோல்ற்றளவு/முறுக்கு தொடர்பு எது?',['Vp/Vs = Np/Ns','Vs/Vp = Np/Ns','Vs Vp = Ns Np','Vs Ns = 1/(Vp Np)'],1,'Both coils link the same changing flux; induced voltage is proportional to turns. Keep primary/secondary in the same order on both sides.','இரு சுருள்களும் ஒரே மாறும் பாயத்துடன் இணையும்; தூண்டிய வோல்ற்றளவு முறுக்கு எண்ணிக்கைக்கு நேர்விகிதம். இருபக்கமும் முதன்மை/துணை வரிசையைப் பேணுக.')
    mc(y,37,5,'energy','Which house relies only on a nonrenewable energy source: A solar+LPG, B national grid+electric cooker, C generator+kerosene, D biogas+firewood?','மீளப்புதுப்பிக்க முடியாத சக்தி மூலத்தை மட்டும் பயன்படுத்தும் வீடு எது: A சூரிய+LP, B தேசிய மின்+மின்சமையல், C பிறப்பாக்கி+மண்ணெண்ணெய், D உயிர்வாயு+விறகு?',['A','B','C','D'],3,'C uses fuel in its generator and kerosene cooker, both fossil-fuel sources in the source table. The grid includes hydroelectric generation; solar and biomass are renewable.','C இன் பிறப்பாக்கி எரிபொருளும் மண்ணெண்ணெய்ச் சமையலும் படிம எரிபொருள் மூலங்கள். தேசிய மின்சாரத்தில் நீர்மின் உள்ளது; சூரியமும் உயிர்த்திணிவும் புதுப்பிக்கக்கூடியவை.')
    mc(y,39,5,'energy','Which source-table house has the least cooking-related indoor air pollution?','மூல அட்டவணையில் சமையலால் குறைந்த வீட்டுவளி மாசுள்ள வீடு எது?',['A (LPG)','B (electric)','C (kerosene)','D (wood)'],2,'Electric cooking has no local combustion exhaust. LPG, kerosene and wood burn fuel and release combustion products indoors.','மின் சமையலில் உள்ளூர் எரிப்புப் புகை இல்லை. LP, மண்ணெண்ணெய், விறகு எரிந்து வீட்டிற்குள் எரிப்புப் பொருள்களை வெளியிடும்.')
    mc(y,40,5,'energy','Which house is most resilient to both electricity and fuel shortages?','மின், எரிபொருள் நெருக்கடிகளுக்கு மிகச் சிறந்த தீர்வுள்ள வீடு எது?',['A (solar + LPG)','B (grid + electric)','C (generator + kerosene)','D (biogas + wood)'],4,'D obtains energy from locally available biogas and firewood rather than imported fossil fuel or the electricity grid. It has independent lighting and cooking sources.','D உள்ளூரில் கிடைக்கும் உயிர்வாயு, விறகைப் பயன்படுத்தும்; இறக்குமதி படிம எரிபொருள்/தேசிய மின்வழங்கலைச் சாராது. ஒளியூட்டலும் சமையலும் சுயாதீன மூலங்களைக் கொண்டுள்ளன.')
    written(y,7,[7,8],[
      ('A(i–iii)','refraction','A ray meets a parallel glass slab at 30° in air. Describe its path and write the index relation using r.','சமாந்தர கண்ணாடித் தகட்டில் வளியிலிருந்து 30° கதிர் படுகிறது. பாதையையும் r கொண்ட முறிவுச் சுட்டி தொடர்பையும் கூறுக.','At entry it bends toward the normal: r < 30°. At exit it bends away from the normal, emerging parallel to the incident ray with lateral displacement. | n = sin30°/sin r (air index ≈ 1).','உள்நுழையும்போது செங்குத்தை நோக்கி முறியும்; r < 30°. வெளியே செங்குத்திலிருந்து விலகி படுகதிருக்குச் சமாந்தரமாகப் பக்க இடப்பெயர்ச்சியுடன் வரும். | n = sin30°/sin r (வளிச் சுட்டி ≈ 1).'),
      ('A(iv–v)','refraction','Find emergence angle. For denser-to-rarer passage, state the path at the critical angle, name the effect above it and give two uses.','வெளியேறும் கோணம் என்ன? அடர்ந்த→அரும் பயணத்தில் அவதிக் கோணப் பாதை, அதற்கு மேல் நிகழ்வு, இரு பயன்பாடுகள் என்ன?','Emergence angle = 30°. At the critical angle, refraction is 90° along the surface. Above it, total internal reflection occurs. Uses: optical fibres and reflecting prisms in binoculars.','வெளியேறும் கோணம் = 30°. அவதிக் கோணத்தில் முறிவு 90°; மேற்பரப்போடு கதிர் செல்லும். அதற்கு மேல் முழு அகத்தெறிப்பு. பயன்பாடுகள்: ஒளியியல் நார்கள், இருகண்ணாடி தெறிப்புப் பட்டகங்கள்.'),
      ('B(i–iii)','heatcapacity','An electric kettle holds 1 kg water, heated 20→100 °C. Water c = 4200 J kg⁻¹ K⁻¹; kettle heat capacity 160 J K⁻¹; heater 1000 W. Find both heats and ideal heating time.','மின் கேத்தலில் 1 kg நீர் 20→100 °C. நீர் c = 4200 J kg⁻¹ K⁻¹; கேத்தல் கொள்ளளவு 160 J K⁻¹; வலு 1000 W. இரு வெப்பங்களையும் இலட்சிய நேரத்தையும் காண்க.','ΔT = 80 K. | Qwater = 1×4200×80 = 336000 J. | Qkettle = 160×80 = 12800 J. | t = (336000+12800)/1000 = 348.8 s ≈ 5.81 min, ignoring heat loss.','ΔT = 80 K. | Qநீர் = 1×4200×80 = 336000 J. | Qகேத்தல் = 160×80 = 12800 J. | t = (336000+12800)/1000 = 348.8 s ≈ 5.81 min; வெப்ப இழப்பு புறக்கணிக்கப்பட்டது.'),
      ('B(iv)(a–b)','radiation','Which heat losses are reduced by a lid and a shiny outer surface?','மூடியும் பளபளப்பான வெளிப்பரப்பும் எந்த வெப்ப இழப்புகளைக் குறைக்கும்?','The lid reduces convection and evaporation from the water surface. A polished shiny surface has lower emissivity, reducing thermal radiation loss.','மூடி நீர் மேற்பரப்பிலிருந்து உடன்காவல், ஆவியாதலைக் குறைக்கும். பளபளப்பான மேற்பரப்பின் உமிழ்வுத்திறன் குறைவதால் வெப்பக் கதிர்வீசல் இழப்பு குறையும்.')])
    written(y,8,[8],[
      ('B(i–iii)','induction','A rod PQ moves right through a field into the page. Name the rule, determine current direction, identify the forward LED and explain the other LED.','PQ கோல் தாளுக்குள் காந்தப் புலத்தில் வலமாக நகரும். விதி, மின்னோட்டத் திசை, முன்னோக்கிய LED, மற்றதன் நிலை என்ன?','Use Fleming’s right-hand generator rule. Velocity right and field inward give positive-charge force upward: induced current flows Q→P in the rod. External current flows top-to-bottom on the right branch, so the forward-biased LED conducts; the opposite LED is reverse-biased and dark.','பிளெமிங்கின் வலக்கைப் பிறப்பாக்கி விதி. வல இயக்கம், உள்புலம் நேரேற்றத்தில் மேல்விசை தரும்; கோலில் மின்னோட்டம் Q→P. வெளிக் கிளையில் மேலிருந்து கீழே மின்னோட்டம்; முன்னோக்கிய LED கடத்தி ஒளிரும்; எதிரான LED மறைச் சார்பால் ஒளிராது.'),
      ('B(iv)(a–b)','magnetic','With a cell connected across the rails, what happens when the switch closes? Name one application.','தண்டவாளங்களுக்குக் கலம் இணைத்து ஆளியை மூடும்போது என்ன நிகழும்? ஒரு பயன்பாடு என்ன?','Current in the rod in the magnetic field experiences a force and the rod moves: the motor effect, described by Fleming’s left-hand rule. Applications include electric motors and loudspeakers.','காந்தப் புலத்திலுள்ள கோல் மின்னோட்டம் விசையை அனுபவித்துக் கோல் நகரும்; இது மோட்டர் விளைவு. பிளெமிங்கின் இடக்கை விதி பொருந்தும். பயன்பாடுகள்: மின் மோட்டர், ஒலிபெருக்கி.')])
    written(y,9,[9],[
      ('B(i–ii)','induction','Name A, B, C in the public-address chain and explain A.','பொது ஒலிபெருக்கித் தொடரில் A, B, C ஐப் பெயரிட்டு A ஐ விளக்குக.','A microphone, B amplifier, C loudspeaker. In a moving-coil microphone, sound vibrates the diaphragm and attached coil in a magnetic field, inducing a changing electrical signal.','A நுணுக்குப்பன்னி, B விரிவாக்கி, C ஒலிபெருக்கி. அசையும் சுருள் நுணுக்குப்பன்னியில் ஒலி மென்சவ்வையும் சுருளையும் காந்தப் புலத்தில் அதிரச் செய்து மாறும் மின் சைகையைத் தூண்டும்.'),
      ('B(iii)','transistor','Describe the main amplifier component: transistor regions and terminals.','விரிவாக்கியின் முக்கிய திரான்சிஸ்ரரின் பகுதிகளையும் முனைகளையும் கூறுக.','A bipolar transistor consists of npn or pnp semiconductor regions. The thin central base controls current between emitter and collector; its three terminals are base, emitter and collector.','இருமுனைத் திரான்சிஸ்ரர் npn அல்லது pnp அரைக்கடத்திப் பகுதிகளைக் கொண்டது. மெலிந்த மைய அடி காலி–சேகரிப்பான் மின்னோட்டத்தைக் கட்டுப்படுத்தும்; முனைகள் அடி, காலி, சேகரிப்பான்.'),
      ('B(iv–vi)','timbre','Name two main loudspeaker parts and explain why amplified speech retains pitch but becomes louder; what if a different person speaks?','ஒலிபெருக்கியின் இரு பகுதிகள், விரிவாக்கிய பேச்சின் சுருதி/உரப்பு, வேறு நபரின் பேச்சு மாற்றம் என்பவற்றை விளக்குக.','Main parts include a coil attached to a cone/diaphragm and a permanent magnet. Amplification increases amplitude, hence loudness, while preserving frequency and pitch. A different person can have different fundamental frequency and harmonics, changing pitch and timbre.','கூம்பு/மென்சவ்வுடன் இணைந்த சுருளும் நிரந்தரக் காந்தமும் முக்கிய பகுதிகள். விரிவாக்கம் வீச்சு/உரப்பை உயர்த்தி மீடிறன்/சுருதியைப் பேணும். வேறு நபரின் அடிப்படை மீடிறனும் மேற்றோன்களும் மாறுவதால் சுருதியும் பண்பும் மாறலாம்.')])
