from expanded_physics import mc,written

def add():
    y=2022
    mc(y,2,1,'units','What is the unit of pressure?','அமுக்கத்தின் அலகு என்ன?',['N m⁻¹','N m⁻²','N m','N m²'],2,'p = F/A, so N/m² = N m⁻² = Pa.','p = F/A; N/m² = N m⁻² = Pa.')
    mc(y,6,1,'units','Which particles carry current through a metal conductor?','உலோகக் கடத்தியில் மின்னோட்டத்தைக் காவும் துணிக்கைகள் எவை?', [('Electrons','இலத்திரன்கள்'),('Protons','புரோத்தன்கள்'),('Neutrons','நியூத்திரன்கள்'),('Metal ions','உலோக அயன்கள்')],1,'Mobile electrons drift through the metal. Its positive ions remain in the lattice rather than travelling through the wire.','நகரக்கூடிய இலத்திரன்கள் உலோகத்தில் நகரும். நேர் அயன்கள் பின்னலில் இருக்கும்; கம்பியூடாகப் பயணிக்காது.')
    mc(y,11,2,'refraction','Which phenomenon is not explained by total internal reflection?','முழு அகத்தெறிப்பால் விளக்கப்படாத நிகழ்வு எது?', [('Light through optical fibre','ஒளியியல் நாரில் ஒளி'),('Bright cut diamond','வெட்டிய வைரம் பிரகாசித்தல்'),('Rainbow colours','வானவில் நிறங்கள்'),('Prism turns a ray 90°','பட்டகம் கதிரை 90° திருப்புதல்')],3,'Rainbow colours come mainly from dispersion/refraction and internal reflection in droplets. Total internal reflection explains optical-fibre guidance and suitable prism/diamond reflections.','வானவில் நிறங்களுக்கு முக்கியம் துளிகளில் நிறப்பிரிகை, முறிவு, அகத்தெறிப்பு. ஒளியியல் நார், பொருத்தமான பட்டகம்/வைரத் தெறிப்பிற்கு முழு அகத்தெறிப்பு பொருந்தும்.')
    mc(y,14,2,'waves','For a mechanical wave entering another medium: A speed changes; B speed is independent of frequency; C speed depends on medium. Which source statements are true?','பொறிமுறை அலைக்கு A வேறு ஊடகத்தில் கதி மாறும்; B கதி மீடிறனில் தங்காது; C கதி ஊடகத்தில் தங்கும். உண்மையான மூலக் கூற்றுகள் எவை?',['A only / A மட்டும்','B only / B மட்டும்','A,C only / A,C மட்டும்','B,C only / B,C மட்டும்'],4,'The source A says frequency changes between media, which is false. Source B says speed does not depend on frequency and C says it depends on the medium: both true in this school model.','மூல A இல் ஊடகம் மாறும்போது மீடிறன் மாறும் எனக் கூறுவது பொய். B இல் கதி மீடிறனில் தங்காது, C இல் ஊடகத்தில் தங்கும்; இப்பாடசாலை மாதிரியில் இரண்டும் உண்மை.')
    from expanded_physics import DATA,bi
    DATA[y][-1]['prompt']=bi('Mechanical waves: A frequency changes between media; B speed is independent of frequency; C speed depends on medium. Which are true?','பொறிமுறை அலைகள்: A ஊடகம் மாறும்போது மீடிறன் மாறும்; B கதி மீடிறனில் தங்காது; C கதி ஊடகத்தில் தங்கும். உண்மையானவை எவை?')
    mc(y,18,2,'moment','What is the advantage of a door handle?','கதவுக் கைப்பிடியின் நன்மை என்ன?', [('Small force can give sufficient moment','சிறிய விசையால் போதுமான திருப்புத் திறன்'),('Produces a larger acceleration','பெரிய ஆர்முடுகலைத் தரும்'),('Small force gives insufficient moment','சிறிய விசை போதாத திறன் தரும்'),('Reduces the work required','வேலையைக் குறைக்கும்')],1,'The handle is far from the hinge, increasing perpendicular moment arm. τ = Fr, so a smaller force gives the required turning effect.','கைப்பிடி கீலிலிருந்து தூரத்தில் இருப்பதால் செங்குத்துத் திறன்புயம் பெரிது. τ = Fr; சிறிய விசையால் தேவையான திருப்பல் விளைவு கிடைக்கும்.')
    mc(y,21,2,'radiation','Heat transfer: A land breeze blows sea→land; B Sun’s heat reaches Earth by radiation; C a hot spoon heats the hand by radiation. Which is true?','வெப்ப மாற்றம்: A தரைக் காற்று கடல்→தரை; B சூரிய வெப்பம் கதிர்வீசலால் வரும்; C சூடான கரண்டி கையை கதிர்வீசலால் சூடாக்கும். உண்மை எது?',['A only / A மட்டும்','B only / B மட்டும்','A,C only / A,C மட்டும்','B,C only / B,C மட்டும்'],2,'B is true. Land breeze goes land→sea. Heat along a metal spoon is conduction, not radiation.','B உண்மை. தரைக் காற்று தரை→கடல் செல்கிறது. உலோகக் கரண்டியூடான வெப்பம் கடத்தல்; கதிர்வீசல் அல்ல.')
    mc(y,24,3,'transformer','An ideal transformer reduces 120 V to 12 V. Primary current is 2 A. Find secondary current.','இலட்சிய நிலைமாற்றி 120 V ஐ 12 V ஆக மாற்றுகிறது. முதன்மை மின்னோட்டம் 2 A. துணை மின்னோட்டம் என்ன?',['0.2 A','2 A','10 A','20 A'],4,'VpIp = VsIs, so Is = 120×2/12 = 20 A. Reducing voltage increases current for equal power.','VpIp = VsIs; Is = 120×2/12 = 20 A. சம வலுவில் வோல்ற்றளவு குறைந்தால் மின்னோட்டம் அதிகரிக்கும்.')
    mc(y,26,3,'graph','Velocity rises 0→10 m/s in 10 s then remains 10 m/s to 20 s. Find displacement.','வேகம் 10 s இல் 0→10 m/s; பின்னர் 20 s வரை 10 m/s. இடப்பெயர்ச்சி என்ன?',['50 m','100 m','150 m','200 m'],3,'Area under v–t = triangle + rectangle = ½×10×10 + 10×10 = 50+100 = 150 m.','v–t பரப்பு = முக்கோணம் + செவ்வகம் = ½×10×10 + 10×10 = 50+100 = 150 m.')
    mc(y,28,3,'forces','Which event follows Newton’s third law?','நியூட்டனின் மூன்றாம் விதிக்கான நிகழ்வு எது?', [('Falling ball rebounds','விழும் பந்து பாயும்'),('Falling fruit reaches maximum speed','விழும் பழத்தின் கதி'),('Gun recoils when fired','துப்பாக்கி சுடும்போது பின்னுதைக்கும்'),('Kicking a ball changes its direction','உதை பந்தின் திசையை மாற்றும்')],3,'The gun pushes the bullet forward; the bullet exerts an equal opposite force on the gun. The pair acts on different bodies, producing recoil.','துப்பாக்கி குண்டை முன்னே தள்ளும்; குண்டு துப்பாக்கியில் சம எதிர்விசை கொடுக்கும். விசைகள் வெவ்வேறு பொருள்களில் தாக்குவதால் பின்னுதைப்பு ஏற்படும்.')
    mc(y,32,3,'friction','As a horizontal push rises from zero and a block starts sliding, how does friction change?','கிடை விசை பூச்சியத்திலிருந்து அதிகரித்து குற்றி நகரத் தொடங்கும்போது உராய்வு எவ்வாறு மாறும்?', [('Remains nonzero constant','மாறாத நேர் பெறுமானம்'),('Jumps straight to maximum','உடனடியாக உச்சம்'),('Rises then stays at maximum','உயர்ந்து உச்சத்தில் மாறாது'),('Rises to maximum then drops slightly','உச்சம் வரை உயர்ந்து சிறிது குறையும்')],4,'Static friction balances the push up to its limiting value. After sliding begins, kinetic friction is slightly below the limiting static friction.','நிலையுராய்வு எல்லை வரை தள்ளும் விசையைச் சமப்படுத்தும். நகர்ந்தபின் இயக்க உராய்வு எல்லை நிலையுராய்வைவிடச் சிறிது குறையும்.')
    mc(y,34,4,'ohm','A long thin wire, B short thick wire, C short thin wire of the same metal are inserted in series with a lamp. Order increasing brightness.','ஒரே உலோகத்தில் A நீண்ட மெல்லிய, B குறுகிய தடித்த, C குறுகிய மெல்லிய கம்பிகள் குமிழுடன் தொடரில். பிரகாசம் அதிகரிக்கும் வரிசை என்ன?',['A,B,C','A,C,B','B,A,C','C,A,B'],2,'R = ρL/A. A has greatest resistance; C has less length; B has the largest cross section and lowest resistance. Lower series resistance means higher current/brightness.','R = ρL/A. A மிகப்பெரிய தடை; C குறைந்த நீளம்; B பெரிய குறுக்குவெட்டு, குறைந்த தடை. தொடர் தடை குறைந்தால் மின்னோட்டம்/பிரகாசம் அதிகரிக்கும்.')
    mc(y,35,4,'pressure','A water barometer has height 10 m, ρ = 1000 and g = 10. Find atmospheric pressure.','நீர் பாரமானியின் உயரம் 10 m; ρ = 1000, g = 10. வளிமண்டல அமுக்கம் என்ன?',['10×10² Pa','1×10³ Pa','1×10⁴ Pa','1×10⁵ Pa'],4,'p = ρgh = 1000×10×10 = 100000 Pa = 10⁵ Pa.','p = ρgh = 1000×10×10 = 100000 Pa = 10⁵ Pa.')
    mc(y,38,4,'energy','Which pair combines resource conservation with a renewable electricity source?','வளப் பேணலும் புதுப்பிக்கக்கூடிய மின் மூலமும் சேர்ந்த ஜோடி எது?', [('Waste control, wind generation','கழிவு முகாமைத்துவம், காற்று மின்'),('Hydropower, coal generation','நீர்மின், நிலக்கரி மின்'),('Cropland conversion, solar generation','விளைநில மாற்றம், சூரிய மின்'),('Low food miles, petroleum generation','குறைந்த உணவு மைல், பெற்றோலிய மின்')],1,'Waste management conserves resources; wind converts a renewable flow of atmospheric kinetic energy to electricity. Coal and petroleum are nonrenewable.','கழிவு முகாமைத்துவம் வளங்களைப் பேணும்; காற்று வளிமண்டலத்தின் புதுப்பிக்கக்கூடிய இயக்கச் சக்தியை மின்சாரமாக மாற்றும். நிலக்கரி, பெற்றோலியம் புதுப்பிக்க முடியாதவை.')
    written(y,7,[6,7],[
      ('A(i)(a–b)','lenses','An object is between F and the centre of a convex lens. Describe a construction and two image properties.','குவிவு வில்லையில் F, மையம் இடையில் பொருள். கதிர் கட்டமைப்பையும் இரு விம்ப இயல்புகளையும் கூறுக.','Draw one ray parallel to the axis, refracting through far F, and one through the optical centre, undeviated. Extend rays backward to meet on the object side. Image is virtual, upright and enlarged.','ஒரு கதிரை அச்சிற்குச் சமாந்தரமாக வரைந்து மறுபுற F ஊடாக முறிக்கவும்; மையக் கதிர் திசை மாறாது. பின்நீட்டிப்புகள் பொருள் பக்கத்தில் சேரும். விம்பம் மாயம், நிமிர்ந்தது, பெரியது.'),
      ('A(ii)(a–b)','lenses','Complete parallel rays through a concave lens and state two image properties for any real-object position.','குழிவு வில்லையூடான சமாந்தரக் கதிர்களைப் பூர்த்திசெய்து எந்த மெய்ப்பொருள் நிலைக்கும் இரு விம்ப இயல்புகளைக் கூறுக.','Rays diverge as if from the near principal focus. Their backward extensions meet between the lens and focus. The image is always virtual, upright and diminished.','கதிர்கள் அருகுபுற முதலான குவியத்திலிருந்து வந்ததுபோல் விரியும். பின்நீட்டிப்புகள் வில்லைக்கும் குவியத்திற்கும் இடையில் சேரும். விம்பம் எப்போதும் மாயம், நிமிர்ந்தது, சிறியது.'),
      ('B(i)(a–d)','circuit','Four 2 Ω resistors must have minimum resistance. State connection, equivalent resistance and current on 8 V.','நான்கு 2 Ω தடைகளின் குறைந்த சமவலுத் தடை பெற இணைப்பு, தடை, 8 V மின்னோட்டம் என்ன?','Connect all four in parallel across the same two nodes. | 1/R = 4/2 = 2; R = 0.5 Ω. | I = V/R = 8/0.5 = 16 A (ideal supply).','நான்கையும் ஒரே இரு முனைகளுக்குச் சமாந்தரமாக இணைக்கவும். | 1/R = 4/2 = 2; R = 0.5 Ω. | I = V/R = 8/0.5 = 16 A (இலட்சிய வழங்கல்).'),
      ('C(i–iv)','heating','For a 1 kg electric kettle: main heat-transfer mode through water, heat for 25→50 °C (c = 4200), two heater-material properties and reason for a three-pin plug.','1 kg மின் கேத்தலில் நீரின் வெப்பப் பரிமாற்ற முறை, 25→50 °C வெப்பம் (c = 4200), வெப்பமாக்கிப் பொருளின் இரு இயல்புகள், மூன்று முனைச் செருகியின் காரணம் என்ன?','Convection distributes heat through the water. | Q = mcΔT = 1×4200×25 = 105000 J. | Heater material needs high resistance and high melting point. The earth pin connects the metal casing to earth, protecting against shock if a live wire contacts it.','நீரில் உடன்காவல் வெப்பத்தைப் பரப்பும். | Q = mcΔT = 1×4200×25 = 105000 J. | வெப்பமாக்கிப் பொருளிற்கு உயர் தடை, உயர் உருகுநிலை தேவை. புவி முனை உலோக உறையைப் புவியுடன் இணைத்து நேர் கம்பி உறையைத் தொட்டால் மின்னதிர்ச்சியைத் தடுக்கும்.')])
    written(y,8,[8],[
      ('B(i)(a–b)','energy','Compare energy changes for pedalling and motor-driven electric bicycle travel.','மிதித்தலும் மோட்டரால் இயங்குதலும் உள்ள மின் சைக்கிளின் சக்தி மாற்றங்களை ஒப்பிடுக.','Pedalling: chemical energy in food → mechanical/kinetic energy. Motor drive: battery chemical → electrical → mechanical/kinetic energy, with heat losses in both routes.','மிதித்தல்: உணவின் இரசாயனச் சக்தி → பொறிமுறை/இயக்கச் சக்தி. மோட்டர்: பற்றரி இரசாயன → மின் → பொறிமுறை/இயக்கச் சக்தி; இரண்டிலும் வெப்ப இழப்புகள் உண்டு.'),
      ('B(ii)(a–c)','power','The motor is 250 W on 50 V; battery capacity is 10 Ah. Find current, ideal running time and range at 30 km/h.','மோட்டர் 50 V இல் 250 W; பற்றரி 10 Ah. மின்னோட்டம், இலட்சிய நேரம், 30 km/h தூரம் என்ன?','I = P/V = 250/50 = 5 A. | Time = capacity/current = 10 Ah/5 A = 2 h. | Range = speed×time = 30×2 = 60 km under stated constant-load assumptions.','I = P/V = 250/50 = 5 A. | நேரம் = கொள்ளளவு/மின்னோட்டம் = 10 Ah/5 A = 2 h. | தூரம் = கதி×நேரம் = 30×2 = 60 km; மாறா சுமை நிபந்தனையில்.'),
      ('B(iii)','lightdevice','Suggest charging without the national grid.','தேசிய மின்வழங்கல் இன்றி மின்னேற்றும் முறையைக் கூறுக.','Use a solar photovoltaic panel with a suitable charge controller matched to the battery. Sunlight is converted into electricity for charging.','பற்றரிக்குப் பொருத்தமான மின்னேற்றக் கட்டுப்படுத்தியுடன் சூரிய ஒளிமின்னழுத்தப் பலகையைப் பயன்படுத்துக. சூரிய ஒளி மின்னேற்ற மின்சாரமாக மாற்றப்படும்.')])
    written(y,9,[8],[
      ('B(i)','buoyancy','State Archimedes’ principle.','ஆக்கிமிடீஸ் தத்துவத்தை எழுதுக.','An object partly or fully immersed in a fluid experiences an upward buoyant force equal to the weight of the fluid it displaces.','பாயியில் பகுதியாக அல்லது முழுமையாக அமிழ்ந்த பொருள் இடம்பெயர்த்த பாயியின் நிறைக்குச் சமமான மேல்நோக்கிய மேலுதைப்பை அனுபவிக்கும்.'),
      ('B(ii)(a–b)','buoyancy','A floating object remains partly above water. Which force relation explains this, and what two properties affect it?','மிதக்கும் பொருள் பகுதியாக நீருக்கு வெளியே உள்ளது. விசைத் தொடர்பும் இரு காரணிகளும் என்ன?','Equilibrium requires upthrust = weight. Its mean density is lower than water, so only part of its volume must displace water to balance weight. Submerged fraction depends on object mean density and fluid density.','சமநிலையில் மேலுதைப்பு = நிறை. பொருளின் சராசரி அடர்த்தி நீரைவிடக் குறைவதால் பகுதிக் கனவளவு நீரை இடம்பெயர்த்தாலே போதும். அமிழ்ந்த பங்கு பொருளின் சராசரி அடர்த்தியிலும் பாயி அடர்த்தியிலும் தங்கும்.'),
      ('B(iii)(a–d)','buoyancy','A submarine model has an air chamber and admits water through valve P. Explain floating, what happens when more water enters and how to rise/descend.','நீர்மூழ்கிக் கப்பல் மாதிரியில் வளியறையும் நீர் புகும் P வால்வும் உள்ளன. மிதப்பு, அதிக நீர் புகுந்தால் மாற்றம், ஏற்றம்/இறக்கம் என்பவற்றை விளக்குக.','Initially upthrust balances model weight. Admitting water increases mass/weight without increasing outer volume substantially; weight can exceed buoyancy, so it sinks. Expelling water with compressed air reduces weight and lets it rise; admitting ballast water lets it descend.','ஆரம்பத்தில் மேலுதைப்பு நிறையைச் சமப்படுத்தும். நீரை அனுமதித்தால் வெளிக் கனவளவு மாறாமல் திணிவு/நிறை அதிகரித்து மேலுதைப்பை மீறுவதால் அமிழும். அழுத்த வளியால் நீரை வெளியேற்றி நிறையைக் குறைத்தால் உயரும்; பார நீரை அனுமதித்தால் இறங்கும்.')])
    y=2023
    mc(y,2,1,'units','What is the SI unit of power?','வலுவின் SI அலகு என்ன?',['W s','W s⁻¹','J s','J s⁻¹'],4,'Power = energy/time, so J/s = J s⁻¹ = W.','வலு = சக்தி/நேரம்; J/s = J s⁻¹ = W.')
    mc(y,5,1,'units','Rubbing two objects gives one a negative charge. Which particles transfer?','இரு பொருள்களைத் தேய்க்கும்போது ஒன்றிற்கு மறையேற்றம் கிடைக்கிறது. இடம்பெயரும் துணிக்கைகள் எவை?', [('Electrons','இலத்திரன்கள்'),('Protons','புரோத்தன்கள்'),('Neutrons','நியூத்திரன்கள்'),('Electrons and protons','இலத்திரன்களும் புரோத்தன்களும்')],1,'The negatively charged object gains electrons from the other. Protons remain bound in nuclei; no charge is created, only redistributed.','மறையேற்றப் பொருள் மற்றதிலிருந்து இலத்திரன்களைப் பெறும். புரோத்தன்கள் கருவில் கட்டுண்டிருக்கும்; ஏற்றம் உருவாகாமல் மீள்பகிரப்படும்.')
    mc(y,9,1,'waves','Which electromagnetic-wave statement is false?','மின்காந்த அலை பற்றிய பொய்யான கூற்று எது?', [('Carry energy','சக்தியைக் காவும்'),('Travel at 3×10⁸ m/s in vacuum','வெற்றிடத்தில் 3×10⁸ m/s'),('Frequency is less than sound frequency','மீடிறன் ஒலி மீடிறனைவிடக் குறைவு'),('Speed in matter is below vacuum speed','சடப்பொருளில் கதி வெற்றிடக் கதியைவிடக் குறைவு')],3,'The source’s false comparison says the speed in matter is smaller than the speed of sound. Electromagnetic waves generally travel far faster than sound; vacuum light speed is 3×10⁸ m/s.','மூலப் பொய்க் கூற்று சடப்பொருளில் மின்காந்த அலையின் கதி ஒலிக் கதியைவிடக் குறைவு என்பதாகும். மின்காந்த அலை பொதுவாக ஒலியைவிட மிக விரைவானது; வெற்றிட ஒளிக் கதி 3×10⁸ m/s.')
    DATA[y][-1]['options'][2]=bi('Speed in matter is less than speed of sound','சடப்பொருளில் கதி ஒலியின் கதியைவிடக் குறைவு')
    mc(y,14,2,'refraction','A refraction occurs only rarer→denser; B rays can bend toward or away from normal; C frequency changes. Which is true?','A அரும்→அடர்ந்த மட்டுமே முறியும்; B செங்குத்தை நோக்கி அல்லது விலகி முறியும்; C மீடிறன் மாறும். உண்மை எது?',['A only / A மட்டும்','B only / B மட்டும்','A,C only / A,C மட்டும்','B,C only / B,C மட்டும்'],2,'Refraction occurs in either direction between media and may bend toward or away from the normal. Frequency remains unchanged; speed and wavelength change.','இரு ஊடகங்களுக்கிடையில் இரு திசைகளிலும் முறிவு நடக்கும்; செங்குத்தை நோக்கி/விலகி முறியும். மீடிறன் மாறாது; கதி, அலைநீளம் மாறும்.')
    mc(y,15,2,'forces','An object weighs 60 N on Earth. Moon g is Earth g/6. Find Moon weight.','புவியில் 60 N நிறையுள்ள பொருளின் சந்திர நிறை என்ன? சந்திர g = புவி g/6.',['10 N','60 N','100 N','360 N'],1,'Wmoon = Wearth/6 = 60/6 = 10 N. Mass remains unchanged.','Wசந்திரன் = Wபுவி/6 = 60/6 = 10 N. திணிவு மாறாது.')
    mc(y,19,2,'sounddistance','A ship receives a sonar echo after 4 s from a seabed 2880 m deep. Find underwater sound speed.','2880 m ஆழத்திலிருந்து SONAR எதிரொலி கப்பலுக்கு 4 s இல் திரும்புகிறது. நீரில் ஒலிக் கதி என்ன?',['720 m/s','1440 m/s','2880 m/s','3700 m/s'],2,'The sound travels down and back: distance = 2×2880 = 5760 m. v = 5760/4 = 1440 m/s.','ஒலி சென்று திரும்பும்: தூரம் = 2×2880 = 5760 m. v = 5760/4 = 1440 m/s.')
    mc(y,22,3,'ohm','Resistance: A depends on end voltage; B proportional to length; C depends on current. Which is true at fixed temperature?','மாறா வெப்பநிலையில் தடை: A முனை வோல்ற்றளவில் தங்கும்; B நீளத்திற்கு நேர்விகிதம்; C மின்னோட்டத்தில் தங்கும். உண்மை எது?',['A only / A மட்டும்','B only / B மட்டும்','A,B only / A,B மட்டும்','A,C only / A,C மட்டும்'],2,'R = ρL/A is fixed by the conductor material and geometry at fixed temperature. V and I change together in V = IR; changing one does not itself change R.','மாறா வெப்பநிலையில் R = ρL/A பொருளாலும் வடிவாலும் நிர்ணயிக்கப்படும். V = IR இல் V,I ஒன்றாக மாறும்; ஒன்றை மாற்றுவதால் மட்டும் R மாறாது.')
    mc(y,25,3,'heatcapacity','In a bimetal strip, lower layer B expands more than upper A on heating. Which source shape results?','இருஉலோகக் கீற்றில் கீழ் B, மேல் A ஐவிட அதிகமாக விரியும். சூடாக்கியபின் மூல வடிவம் எது?',['Diagram 1 / படம் 1','Diagram 2 / படம் 2','Diagram 3 / படம் 3','Diagram 4 / படம் 4'],4,'B must occupy the longer outer arc while A occupies the shorter inner arc. The strip bends toward A, the metal with smaller expansion. Source diagram 4 shows B on the outside of the arch.','B நீண்ட வெளி வளைவிலும் A குறுகிய உள் வளைவிலும் இருக்கும். குறைவாக விரியும் A பக்கமாகக் கீற்று வளையும். மூலப் படம் 4 இல் B வெளிப்புற வளைவில் உள்ளது.',(.10,.333,.91,.55))
    mc(y,26,3,'buoyancy','Which condition must a floating solid satisfy?','மிதக்கும் திண்மப் பொருள் நிறைவேற்ற வேண்டிய நிபந்தனை எது?', [('Density below all liquids','எல்லாத் திரவங்களையும் விடக் குறைந்த அடர்த்தி'),('Mass equals displaced liquid volume','திணிவு இடம்பெயர்ந்த கனவளவிற்குச் சமம்'),('Density equals displaced liquid mass','அடர்த்தி இடம்பெயர்ந்த திணிவிற்குச் சமம்'),('Weight equals buoyancy','நிறை மேலுதைப்பிற்குச் சமம்')],4,'Floating equilibrium requires upward buoyancy equal downward weight. Compare forces with forces, not mass with volume.','மிதக்கும் சமநிலைக்கு மேலுதைப்பு கீழ்நிறைக்குச் சமம். விசைகளை விசைகளுடன் ஒப்பிடுக; திணிவை கனவளவுடன் அல்ல.')
    mc(y,28,3,'circuit','Identical bulbs: A in series with R shares a parallel branch with B; C is in series with the entire pair. Order brightness.','சம குமிழ்களில் A தடையுடன் தொடரில்; அக்கிளை B க்கு சமாந்தரம்; C முழுத் தொகுப்பிற்குத் தொடர். பிரகாச வரிசை என்ன?',['A < B < C','A = B = C','A = B < C','A < C < B'],1,'A branch has extra resistance, so IA < IB. C carries the sum IA+IB, larger than either. For identical bulbs, power I²r gives A < B < C.','A கிளையில் மேலதிகத் தடை; IA < IB. C இல் IA+IB மொத்தம் செல்கிறது; இரண்டையும்விடப் பெரியது. சம குமிழ்களில் I²r வலு A < B < C தரும்.')
    mc(y,31,3,'forces','Which force diagram is in equilibrium: A two upward 5 N balancing central downward 10 N; B angled 5 N forces; C separated opposite 5 N?','சமநிலைப் படம் எது: A இரு மேல் 5 N, மைய கீழ் 10 N; B கோண 5 N; C இடைவெளியுள்ள எதிர் 5 N?', ['A only / A மட்டும்','B only / B மட்டும்','A,C only / A,C மட்டும்','A,B,C / அனைத்தும்'],1,'A has both zero resultant force and zero net moment. B’s vertical components total less than 10 N. C is a couple: zero force but nonzero moment.','A இல் நிகர விசையும் திறனும் பூச்சியம். B செங்குத்துக் கூறுகள் 10 N இற்குக் குறைவு. C விசை இணை; நிகர விசை பூச்சியம் ஆனால் திறன் பூச்சியமல்ல.')
    mc(y,35,4,'induction','A primary coil A with DC and switch shares an iron core with coil B. When is B current induced?','நேரோட்டம், ஆளியுடன் A சுருள் இரும்பு மையத்தை B உடன் பகிர்கிறது. B இல் எப்போது மின்னோட்டம் தூண்டப்படும்?', [('Only A at closing','மூடும்போது A மட்டும்'),('Both continuously when closed','மூடியபோது இரண்டும் தொடர்ந்து'),('Only B at closing','மூடும்போது B மட்டும்'),('B at closing and opening instants','மூடும், திறக்கும் கணங்களில் B')],4,'Only a change of primary current changes core flux. Closing and opening induce opposite transient emf in B; steady DC induces none.','முதன்மை மின்னோட்ட மாற்றம் மட்டும் மையப் பாயத்தை மாற்றும். மூடும்/திறக்கும் கணங்களில் B இல் எதிர்த் தற்காலிக மின்னியக்க விசைகள்; மாறா நேரோட்டத்தில் இல்லை.')
    mc(y,36,4,'graph','Which statement about a velocity–time graph is false?','வேகம்–நேர வரைபு பற்றிய பொய்யான கூற்று எது?', [('Area gives displacement','பரப்பு இடப்பெயர்ச்சி தரும்'),('From rest graph begins at origin','ஓய்விலிருந்து இயக்கம் மூலத்தில் தொடங்கும்'),('Slope gives displacement','சாய்வு இடப்பெயர்ச்சி தரும்'),('Slope gives acceleration','சாய்வு ஆர்முடுகல் தரும்')],3,'The slope Δv/Δt is acceleration. Signed area ∫v dt gives displacement.','சாய்வு Δv/Δt ஆர்முடுகல். குறியுடன் கூடிய பரப்பு ∫v dt இடப்பெயர்ச்சி தரும்.')
    written(y,4,[8],[
      ('A(i–iii)','pressure','A sealed funnel is connected to a U-tube. Press its rubber membrane, then rotate it in air. Explain level changes and lack of changes.','மூடிய புனல் U குழாயுடன் இணைக்கப்பட்டுள்ளது. இறப்பர் மென்சவ்வை அழுத்திப் பின்னர் வளியில் திருப்புக. நீர்மட்ட மாற்றங்களை விளக்குக.','Pressing raises trapped-air pressure: connected arm X falls and open arm Y rises. Pressure difference balances the water-column difference. Rotating the funnel in air does not change external pressure appreciably, so orientation alone does not change the levels.','அழுத்தினால் அடைபட்ட வளியமுக்கம் உயரும்: இணைத்த புயம் X குறையும், திறந்த Y உயரும். அமுக்க வேறுபாடு நீர்நிரல் வேறுபாட்டைச் சமப்படுத்தும். வளியில் புனலைத் திருப்புவது வெளி அமுக்கத்தை மாற்றாததால் திசை மட்டும் மட்டங்களை மாற்றாது.'),
      ('A(iv–vi)','pressure','Immerse the funnel progressively in water. Explain X,Y changes and compare equal-depth readings in water and coconut oil.','புனலை நீரில் படிப்படியாக அமிழ்த்துக. X,Y மாற்றங்களையும் சம ஆழத்தில் நீர்/தேங்காய் எண்ணெய் வாசிப்புகளையும் ஒப்பிடுக.','Greater depth gives larger p = ρgh, depressing X and raising Y more. At the same depth, coconut oil’s lower density gives a smaller pressure and a smaller U-tube level difference than water.','ஆழம் உயர்ந்தால் p = ρgh அதிகரித்து X மேலும் குறையும், Y மேலும் உயரும். சம ஆழத்தில் தேங்காய் எண்ணெயின் அடர்த்தி குறைவதால் நீரைவிடச் சிறிய அமுக்கமும் சிறிய மட்ட வேறுபாடும் கிடைக்கும்.'),
      ('B(i–iii)','waves','Classify a water-surface wave, indicate wavelength/amplitude on its graph and explain a floating foam ball’s up/down motion.','நீர் மேற்பரப்பு அலையை வகைப்படுத்தி அலைநீளம்/வீச்சைக் குறிக்கவும்; நுரைமிதவையின் மேல்/கீழ் இயக்கத்தை விளக்குக.','School approximation: transverse wave because the observed vertical displacement is perpendicular to horizontal travel. Wavelength is crest-to-crest distance; amplitude is equilibrium-to-crest height. The float oscillates as crests/troughs pass; it does not travel along with the wave (idealised small-amplitude case).','பாடசாலை அண்மிப்பில் குறுக்கு அலை; காணும் செங்குத்து இடப்பெயர்ச்சி கிடைப் பரவலுக்குச் செங்குத்து. அலைநீளம் முகடு–முகடு தூரம்; வீச்சு சமநிலை–முகடு உயரம். முகடு/தாழி செல்லும்போது மிதவை அதிரும்; அலையுடன் நீண்ட தூரம் செல்லாது (சிறிய வீச்சு மாதிரி).')])
    written(y,7,[10,11],[
      ('A(i)','refraction','A submerged coin appears raised. Describe two rays reaching an observer and the apparent-image construction.','நீரிலுள்ள நாணயம் உயர்ந்ததாகத் தோன்றுகிறது. இரு கதிர்களும் தோற்ற விம்பக் கட்டமைப்பும் விளக்குக.','Rays from the coin bend away from the normal at the water–air surface. Extend their air paths backward into water; extensions meet above the real coin, locating its shallower virtual image.','நாணயக் கதிர்கள் நீர்–வளி எல்லையில் செங்குத்திலிருந்து விலகி முறியும். வளிப் பாதைகளை நீருக்குள் பின்நீட்டித்தால் மெய்நாணயத்திற்கு மேலே சேர்ந்து குறைந்த ஆழ மாயவிம்பத்தைக் காட்டும்.'),
      ('A(ii)(a–d)','refraction','Define critical angle, describe rays below/equal/above it and give two applications of the final effect.','அவதிக் கோண வரையறை, அதற்குக் கீழ்/சமம்/மேல் கதிர்ப்பாதைகள், இறுதி நிகழ்வின் இரு பயன்பாடுகள் என்ன?','Critical angle is incidence in the denser medium giving a refracted angle of 90° in the rarer medium. Below it rays refract out; at it they run along the boundary; above it total internal reflection occurs. Applications: optical fibres and prism binoculars.','அடர்ந்த ஊடகத்தில் படுகோணம் அரும் ஊடகத்தில் 90° முறிவைத் தருவது அவதிக் கோணம். அதற்குக் கீழ் வெளியே முறியும்; சமத்தில் எல்லையோடு செல்லும்; மேலே முழு அகத்தெறிப்பு. பயன்பாடுகள்: ஒளியியல் நார், பட்டக இருகண்ணாடி.'),
      ('B(i–iii)','power','A 1000 W kettle boils four cups of water in 3 min; two cups require 2 min. Find the first energy in J/kWh and energy wasted compared with the second water-only estimate.','1000 W கேத்தல் நான்கு கோப்பைகளை 3 min இல் கொதிக்கச் செய்கிறது; இரண்டு கோப்பைக்கு 2 min. முதல் சக்தி J/kWh, இரண்டாவது கணிப்புடன் ஒப்பிட்ட விரயத்தை காண்க.','E = Pt = 1000×180 = 180000 J = 0.050 kWh. | Preparing only two cups uses 1000×120 = 120000 J = 0.0333 kWh. | Extra energy from boiling four instead of the needed two = 60000 J = 0.0167 kWh. This comparison is not a measured thermal efficiency.','E = Pt = 1000×180 = 180000 J = 0.050 kWh. | இரண்டு கோப்பைக்கு 1000×120 = 120000 J = 0.0333 kWh. | தேவையான இரண்டுக்கு பதில் நான்கு கொதிக்கும்போது மேலதிக சக்தி = 60000 J = 0.0167 kWh. இது அளந்த வெப்பத் திறன் அல்ல.'),
      ('C(i)','motion','A car at 10 m/s has driver reaction time 0.2 s. Find reaction distance.','10 m/s கார்; சாரதியின் மறுதாக்க நேரம் 0.2 s. மறுதாக்கத் தூரம் என்ன?','During reaction, speed remains 10 m/s. | Distance = vt = 10×0.2 = 2 m before braking starts.','மறுதாக்கத்தில் கதி 10 m/s ஆகவே இருக்கும். | தூரம் = vt = 10×0.2 = 2 m; பின்னரே தடைப்பு தொடங்கும்.'),
      ('C(ii)(a–c)','motion','Braking deceleration is 40 m s⁻² and braking distance 1.25 m. A dog is 4 m away. Is collision avoided? Find force for 1000 kg; compare a 0.3 s reaction.','அமர்முடுகல் 40 m s⁻²; தடைப்புத் தூரம் 1.25 m; நாய் 4 m முன். மோதல் தவிர்க்கப்படுமா? 1000 kg விசையும் 0.3 s மறுதாக்கமும் ஒப்பிடுக.','Total stop distance = 2+1.25 = 3.25 m < 4 m: avoided. | Force magnitude = ma = 1000×40 = 40000 N opposite motion. | At 0.3 s, reaction distance = 3 m; total = 4.25 m > 4 m, so collision cannot be avoided under these assumptions.','நிறுத்தத் தூரம் = 2+1.25 = 3.25 m < 4 m; தவிர்க்கலாம். | விசைப் பருமன் = ma = 1000×40 = 40000 N இயக்கத்திற்கு எதிர். | 0.3 s இல் மறுதாக்கத் தூரம் 3 m; மொத்தம் 4.25 m > 4 m; இந்நிபந்தனையில் தவிர்க்க முடியாது.')])
    written(y,8,[12],[
      ('B(i–iii)','power','A is rated 6 V, 12 W and B 4 V, 0.5 A. State connection, current through A and meaning of B’s rating.','A 6 V, 12 W; B 4 V, 0.5 A. இணைப்பு, A மின்னோட்டம், B குறிப்பின் பொருள் என்ன?','The two branches are parallel across 6 V. | IA = P/V = 12/6 = 2 A. | B requires 4 V and draws 0.5 A in normal operation; its rated power is 4×0.5 = 2 W.','இரு கிளைகளும் 6 V இற்கு சமாந்தரம். | IA = P/V = 12/6 = 2 A. | B சாதாரணமாக 4 V இல் 0.5 A பெறும்; வலு 4×0.5 = 2 W.'),
      ('B(iv)(a–c)','ohm','B must run normally on 6 V with series resistor R. Find R voltage, current and resistance.','B ஐ 6 V இல் சரியாக இயக்கத் தொடர் R உள்ளது. R வோல்ற்றளவு, மின்னோட்டம், தடை என்ன?','Voltage across R = 6−4 = 2 V. | Same series current = 0.5 A. | R = V/I = 2/0.5 = 4 Ω.','R வோல்ற்றளவு = 6−4 = 2 V. | தொடர் மின்னோட்டம் = 0.5 A. | R = V/I = 2/0.5 = 4 Ω.'),
      ('B(v)','circuit','Find battery current when both devices run normally.','இரு சாதனங்களும் சரியாக இயங்கும்போது பற்றரி மின்னோட்டம் என்ன?','Parallel branch currents add: Ibattery = IA + IB = 2 + 0.5 = 2.5 A.','சமாந்தரக் கிளை மின்னோட்டங்கள் கூடும்: Iபற்றரி = IA + IB = 2 + 0.5 = 2.5 A.')])
    written(y,9,[12],[
      ('B(i)(a–b)','magnetic','Describe the field around a straight current-carrying wire and two applications of the coil field.','மின்னோட்டமுள்ள நேர்க் கம்பியைச் சுற்றிய புலத்தையும் சுருள் புலத்தின் இரு பயன்பாடுகளையும் விளக்குக.','Draw concentric circles around the wire; right-hand thumb follows conventional current and fingers give field sense. A solenoid produces a stronger bar-magnet-like field; uses include an electric bell and electromagnet crane.','கம்பியைச் சுற்றி ஒருமைய வட்டங்கள் வரைக. வலக்கைப் பெருவிரல் மின்னோட்டத் திசை; விரல்கள் புலத் திசை. வரிச்சுருள் வலுவான கோல்காந்தப் புலம் தரும்; பயன்பாடுகள் மின் மணி, மின்காந்தப் பாரந்தூக்கி.'),
      ('B(ii)(a–c)','magnetic','A vertical conductor carries upward current in a rightward field. Name two factors affecting force, the direction rule and two uses.','செங்குத்துக் கடத்தியில் மேல் மின்னோட்டம், வலப்புலம். விசையை மாற்றும் இரு காரணிகள், திசை விதி, இரு பயன்பாடுகள் என்ன?','Force depends on current and magnetic-field strength (also conductor length and angle): F = BIL sinθ. Fleming’s left-hand rule gives force into the page. Uses: electric motor and loudspeaker.','விசை மின்னோட்டம், காந்தப் புல வலிமையில் தங்கும் (நீளம்/கோணமும்): F = BIL sinθ. பிளெமிங்கின் இடக்கை விதி தாளுக்குள் விசை தரும். பயன்பாடுகள் மின் மோட்டர், ஒலிபெருக்கி.'),
      ('C(i–ii)','induction','Define electromagnetic induction and give two ways of increasing hydroelectric generator current.','மின்காந்தத் தூண்டலை வரையறுத்து நீர்மின் பிறப்பாக்கி மின்னோட்டத்தை அதிகரிக்க இரு முறைகளைக் கூறுக.','A changing magnetic flux linked to a conductor induces an emf; in a closed circuit this drives current. Increase rotation speed or magnetic-field strength (or coil turns), increasing the rate of flux linkage change for a fixed load.','கடத்தியுடன் இணைந்த காந்தப் பாய மாற்றம் மின்னியக்க விசையைத் தூண்டும்; மூடிய சுற்றில் அது மின்னோட்டம் தரும். சுழற்சிக் கதி அல்லது புல வலிமை (அல்லது முறுக்குகள்) அதிகரித்தால் மாறா சுமையில் பாய இணைவு மாற்ற வீதம் உயரும்.')])
