# -*- coding: utf-8 -*-
"""Independent bilingual model solutions; labels follow the uploaded Tamil paper.

Teaching paraphrases are paired with the original scans, not presented as OCR.
No per-part marks or official essay marking claims are made.
"""

def append_written(written, part):
    p = part
    written(1, ['biology','chemistry','physics'], ['Coastal environment','Buoyancy'], [5,6],
        'A coastal environment: plants, animals, minerals, waves and a floating ship.',
        'கரையோரச் சூழல்: தாவரங்கள், விலங்குகள், கனிமங்கள், அலைகள், மிதக்கும் கப்பல்.', [
        p('i(a)','biology','Why do coconut palms bend towards the sea? Name the response and stimulus.','தென்னை மரங்கள் கடலை நோக்கி வளைவதன் அசைவும் தூண்டியும் என்ன?',
          'Positive phototropism: growth towards light. Light is the stimulus; this is growth, not movement of the whole plant.','நேரொளிநாட்டம்: ஒளியை நோக்கிய வளர்ச்சி. தூண்டி ஒளி; முழுத் தாவரத்தின் இடப்பெயர்ச்சி அல்ல.'),
        p('i(b)','biology','Give the phyla of sea anemone and Nereis.','கடல் அனிமனி, நீரிஸ் ஆகியவற்றின் தொகுதிகளைக் குறிப்பிடுக.',
          'Sea anemone: Cnidaria (Coelenterata). Nereis: Annelida. The first has stinging cells; Nereis is a segmented marine worm.','கடல் அனிமனி: குழியுடலிகள் (Cnidaria). நீரிஸ்: வளையப்புழுக்கள் (Annelida). முதலாவது கொட்டும் கலங்களைக் கொண்டது; நீரிஸ் கண்டங்களுள்ள கடல்வாழ் புழு.'),
        p('ii(a)','chemistry','Where is the main Sri Lankan coastal ilmenite deposit?','இலங்கையில் இல்மனைற் அதிகமாகக் காணப்படும் கரையோரப் பிரதேசம் எது?',
          'Pulmoddai, on the northeast coast. Ilmenite is a titanium-bearing mineral.','வடகிழக்குக் கரையிலுள்ள புல்மோட்டை. இல்மனைற் தைற்றேனியம் கொண்ட கனிமம்.'),
        p('ii(b)','chemistry','Name an industry using ilmenite.','இல்மனைற் பயன்படும் கைத்தொழில் ஒன்றைக் குறிப்பிடுக.',
          'Titanium extraction, or production of titanium dioxide pigments for paint. The mineral supplies titanium compounds.','தைற்றேனியம் பிரித்தெடுத்தல் அல்லது வர்ணத்திற்கான தைற்றேனியம் ஈரொட்சைடு தயாரித்தல்.'),
        p('iii(a)','chemistry','How can sodium be extracted from salt obtained from sea water?','கடல்நீரிலிருந்து பெற்ற உப்பிலிருந்து சோடியத்தை எவ்வாறு பிரித்தெடுக்கலாம்?',
          'Electrolyse molten sodium chloride. First obtain and dry the salt, then melt it. Sodium ions gain electrons at the cathode: Na⁺ + e⁻ → Na. Aqueous salt solution does not produce sodium metal.','உருகிய சோடியம் குளோரைட்டை மின்னாற்பகுக்கலாம். உப்பைப் பெற்று உலர்த்தி உருக்க வேண்டும். எதிர்மின்வாயில் Na⁺ + e⁻ → Na. நீர்க்கரைசலிலிருந்து சோடிய உலோகம் கிடைக்காது.'),
        p('iii(b)','chemistry','Why is electrolysis used?','மின்னாற்பகுப்பு ஏன் பயன்படுத்தப்படுகிறது?',
          'Sodium is very reactive and cannot be extracted by carbon reduction. Electrical energy supplies the required reduction. In water, water is reduced instead.','சோடியம் மிகத் தாக்கமுடையது; காபன் ஒடுக்கத்தால் பிரித்தெடுக்க முடியாது. மின்சக்தி தேவையான ஒடுக்கத்தை ஏற்படுத்துகிறது. நீர்க்கரைசலில் நீரே ஒடுக்கப்படும்.'),
        p('iv','physics','Classify small ripples on the water surface.','நீர்மேற்பரப்பில் தோன்றும் சிறிய அலைகளை வகைப்படுத்துக.',
          'Transverse, in the school model: surface displacement is up/down while the wave travels horizontally. Real surface-water particle motion is more complex.','பாடசாலை மாதிரியில் குறுக்கலை: நீர் மேலும் கீழும் அசைய அலை கிடையாகச் செல்கிறது. உண்மையான நீரலைத் துணிக்கை இயக்கம் மேலும் சிக்கலானது.',lessons=['g11-chapter-04-waves']),
        p('v(a)','physics','Find the upthrust on a floating 75,000 kg ship (g = 10 N kg⁻¹).','75,000 kg கப்பல் மிதக்கும்போது மேலுதைப்பைக் காண்க (g = 10 N kg⁻¹).',
          '750,000 N upward. For floating equilibrium, upthrust equals weight, not mass.','மேல்நோக்கி 750,000 N. மிதக்கும் சமநிலையில் மேலுதைப்பு நிறைக்குச் சமம்; திணிவுக்குச் சமமல்ல.',
          steps=[('W = mg = 75,000 × 10 = 750,000 N.','W = mg = 75,000 × 10 = 750,000 N.'),('Vertical resultant is zero, so U = W.','நிலைக்குத்து விளைவுவிசை பூச்சியம்; U = W.')],lessons=['g10-chapter-15-hydrostatic-pressure','chapter-12-equilibrium']),
        p('v(b)','physics','Why does an iron ship float although solid iron sinks?','திண்ம இரும்பு மூழ்கினாலும் இரும்புக் கப்பல் ஏன் மிதக்கிறது?',
          'The hollow hull displaces a large volume of water. Its average density, including the enclosed air, is lower than that of water, allowing upthrust to balance weight.','வெற்றிடமான கப்பல் உடல் அதிக நீரை இடம்பெயர்க்கிறது. உள்ளிருக்கும் வளியையும் சேர்த்த சராசரி அடர்த்தி நீரைவிடக் குறைவு; மேலுதைப்பு நிறையைச் சமப்படுத்துகிறது.',lessons=['g10-chapter-15-hydrostatic-pressure']),
        p('vi(a)','biology','Give two causes of coastal pollution.','கரையோர மாசடைதலுக்கான இரண்டு காரணங்களைக் குறிப்பிடுக.',
          'Untreated industrial/sewage discharge and dumping plastic waste (oil spills are another example). State two distinct sources.','சுத்திகரிக்காத தொழிற்சாலை/கழிவுநீர் வெளியேற்றம், பிளாஸ்டிக் கழிவுகளைக் கொட்டுதல். எண்ணெய்க் கசிவும் எடுத்துக்காட்டு.'),
        p('vi(b)','biology','Suggest measures to reduce that pollution.','அம்மாசடைதலைக் குறைப்பதற்கான நடவடிக்கைகளைக் குறிப்பிடுக.',
          'Treat wastewater before discharge and collect/recycle solid waste instead of dumping it. Match each measure to the pollution source.','வெளியேற்றுமுன் கழிவுநீரைச் சுத்திகரித்தல்; திண்மக் கழிவுகளைச் சேகரித்து மீள்சுழற்சி செய்தல். நடவடிக்கையை மாசின் காரணத்துடன் இணைக்கவும்.')])

    written(2,['biology'],['Transpiration','Ecology'],[6], 'Transpiration experiment and organisms in Sinharaja forest.', 'ஆவியுயிர்ப்புப் பரிசோதனையும் சிங்கராஜ வன உயிரிகளும்.',[
        p('A(i)','biology','Compare droplets after five hours in sunlight: bagged leafy plant A and soil-only control B.','சூரிய ஒளியில் ஐந்து மணிநேரத்தின் பின் இலைத் தாவரமுள்ள A, மண் மட்டும் உள்ள B பைகளின் நீர்த்துளிகளை ஒப்பிடுக.',
          'A has more droplets. Water vapour from leaves condenses on the bag, whereas B mainly measures evaporation from the soil.','A இல் அதிக நீர்த்துளிகள். இலைகளிலிருந்து வெளியேறிய நீராவி பையில் ஒடுங்கும்; B மண்ணின் ஆவியாதலைக் காட்டுகிறது.'),
        p('A(ii)','biology','Name the leaf structures through which most water vapour escapes.','இலையிலிருந்து பெரும்பாலான நீராவி வெளியேறும் அமைப்புகள் என்ன?',
          'Stomata. Guard cells regulate these pores, which also allow gas exchange.','இலைவாய்கள். காப்புக் கலங்கள் இத்துளைகளை ஒழுங்குபடுத்துகின்றன; வாயுப் பரிமாற்றமும் நிகழும்.'),
        p('A(iii)','biology','What process produces the droplets in B?','B இல் நீர்த்துளிகள் ஏற்படுவதற்கான செயன்முறை என்ன?',
          'Evaporation from soil followed by condensation on the bag; there are no leaves in B to transpire.','மண்ணிலிருந்து ஆவியாதலும் பையில் ஒடுங்குதலும். B இல் ஆவியுயிர்ப்பிற்கான இலைகள் இல்லை.'),
        p('A(iv)','biology','Identify the control.','கட்டுப்பாட்டுப் பரிசோதனை எது?',
          'B, the soil-only setup. Comparing A with B separates the contribution of the plant from soil evaporation.','மண் மட்டும் உள்ள B. தாவரத்தின் பங்களிப்பை மண்ணின் ஆவியாதலிலிருந்து வேறுபடுத்த உதவும்.'),
        p('A(v)(a)','biology','Dry blue cobalt chloride papers cover both leaf surfaces between glass slides. State the observations after a short time.','கண்ணாடி வழுக்கிகளுக்கிடையில் இரு இலை மேற்பரப்புகளையும் உலர்ந்த நீல கோபால்ற் குளோரைட் தாள்கள் மூடுகின்றன. சிறிது நேரத்தின் பின் அவதானிப்புக்களைக் குறிப்பிடுக.',
          'Both papers change from blue to pink as they absorb moisture; the paper on the lower surface changes sooner or becomes more strongly pink. Compare under identical conditions.','ஈரப்பதத்தை உறிஞ்சும்போது இரு தாள்களும் நீலத்திலிருந்து இளஞ்சிவப்பாக மாறும். கீழ்ப்பரப்பின் தாள் விரைவாக அல்லது அதிகமாக இளஞ்சிவப்பாகும். ஒரே நிலைமையில் ஒப்பிடவும்.'),
        p('A(v)(b)','biology','Explain the usual difference between upper and lower surfaces.','மேல், கீழ் மேற்பரப்புகளில் வழக்கமாகக் காணப்படும் வேறுபாட்டை விளக்குக.',
          'In a typical terrestrial broad leaf, more stomata occur on the lower surface, so its paper changes sooner. This pattern is not universal for every plant.','பொதுவான நிலவாழ் அகன்ற இலையின் கீழ்ப்பரப்பில் அதிக இலைவாய்கள் உள்ளதால் அங்குள்ள தாள் விரைவாக நிறம்மாறும். எல்லாத் தாவரங்களுக்கும் இது பொதுவல்ல.'),
        p('B(i)','biology','How do fungi on a decaying log obtain food?','அழுகும் மரக்கட்டையிலுள்ள பங்கசுக்கள் எவ்வாறு உணவு பெறுகின்றன?',
          'Saprotrophic nutrition: enzymes are secreted onto dead material, digest it outside the body, and soluble products are absorbed.','இறந்த பொருளில் நொதியங்களைச் சுரந்து உடலுக்கு வெளியே சமிபாடடையச் செய்து கரையக்கூடிய விளைவுகளை உறிஞ்சும் பூதியுண்ணிப் போசணை.'),
        p('B(ii)','biology','Give an adaptation of orchid flowers that prevents self-pollination.','தன்மகரந்தச் சேர்க்கையைத் தவிர்க்கும் ஒட்சிட் பூவின் ஓர் இசைவாக்கத்தைக் குறிப்பிடுக.',
          'Herkogamy: stamens and stigma are spatially separated. In orchids a barrier (rostellum) helps prevent the flower’s own pollen from reaching its stigma.','ஆணகமும் சூலகமுடியும் இடவெளியால் பிரிந்திருத்தல் (herkogamy). ஒட்சிட்டில் தடுப்பு (rostellum) அதே பூவின் மகரந்தம் அதன் சூலகமுடியை அடைவதைத் தடுக்க உதவும்.'),
        p('B(iii)(a)','biology','Construct a possible food chain with the plant, snail, bird and snake.','தாவரம், நத்தை, பறவை, பாம்பு கொண்டு சாத்தியமான உணவுச் சங்கிலி அமைக்கவும்.',
          'Green plant → snail → bird → snake. Arrows show the direction of transfer of food/energy, from food to consumer.','பசுந்தாவரம் → நத்தை → பறவை → பாம்பு. அம்புகள் உணவு/சக்தி நுகரியை நோக்கிக் கடத்தப்படுவதைச் சுட்டும்.'),
        p('B(iii)(b)','biology','Identify the primary consumer in that chain.','அச்சங்கிலியின் முதன்மை நுகரி எது?',
          'The snail, which feeds directly on the producer. The plant is a producer, not a consumer.','உற்பத்தியாளரை நேரடியாக உண்பதால் நத்தை முதன்மை நுகரி. தாவரம் உற்பத்தியாளர்.'),
        p('B(iv)','biology','Name conservation within the natural forest habitat.','இயற்கை வனவாழிடத்திலேயே மேற்கொள்ளும் பாதுகாப்பு என்ன?',
          'In situ conservation: protecting organisms in their natural habitat.','இருப்பிடப் பாதுகாப்பு (in situ): உயிரிகளை அவற்றின் இயற்கை வாழிடத்திலேயே பாதுகாத்தல்.')])

    written(3,['chemistry','physics'],['Bonding','Chemical reactions','Gas laws'],[7], 'Use the electron diagrams and test-tube setups in the scan; then consider a cooled balloon.', 'மூலத்தாளின் இலத்திரன் படங்களையும் சோதனைக் குழாய்களையும் பயன்படுத்தி, குளிர்விக்கப்பட்ட பலூனைக் கருதுக.',[
        p('A(i)','chemistry','From the diagrams, give the valency of Y.','படங்களிலிருந்து Y இன் வலுவளவைக் குறிப்பிடுக.',
          '4: Y shares four electron pairs, forming four single covalent bonds.','4: Y நான்கு இலத்திரன் சோடிகளைப் பகிர்ந்து நான்கு தனிப் பங்கீட்டுப் பிணைப்புகளை உருவாக்குகிறது.'),
        p('A(ii)','chemistry','Which diagram represents a diatomic molecule?','ஈரணு மூலக்கூறைக் காட்டும் படம் எது?',
          'Diagram (1), X₂. A diatomic molecule contains two atoms.','படம் (1), X₂. ஈரணு மூலக்கூறு இரண்டு அணுக்களைக் கொண்டது.'),
        p('A(iii)','chemistry','Write the formula represented by diagram (3).','படம் (3) இன் மூலக்கூற்றுச் சூத்திரத்தை எழுதுக.',
          'ZX₃: one Z atom bonded to three X atoms. The letters here are the paper’s placeholders, not element symbols.','ZX₃: ஒரு Z அணு மூன்று X அணுக்களுடன் பிணைகிறது. இவ்வெழுத்துக்கள் இவ்வினாவின் குறியீடுகள்; உண்மையான மூலகக் குறியீடுகள் அல்ல.'),
        p('A(iv)','chemistry','What type of bonding occurs in the three diagrams?','மூன்று படங்களிலும் காணப்படும் பிணைப்பு வகை என்ன?',
          'Covalent bonding: electron pairs are shared between atoms rather than transferred.','பங்கீட்டுப் பிணைப்பு: அணுக்களிடையே இலத்திரன் சோடிகள் பகிரப்படுகின்றன; மாற்றப்படுவதில்லை.'),
        p('A(v)','chemistry','Identify X, Y and Z and give their atomic numbers.','X, Y, Z ஐ இனங்கண்டு அணு எண்களைக் குறிப்பிடுக.',
          'X = hydrogen (1); Y = carbon (6); Z = nitrogen (7). Their bonding capacities are 1, 4 and 3 in these diagrams.','X = ஐதரசன் (1); Y = காபன் (6); Z = நைதரசன் (7). இப்பிணைப்புக்களில் வலுவளவுகள் முறையே 1, 4, 3.'),
        p('B(i)(a)','chemistry','Which setup releases gas? (B: zinc + dilute HCl.)','எந்த அமைப்பில் வாயு வெளியேறும்? (B: துத்தநாகம் + ஐதான HCl.)',
          'B: zinc reacts with acid to release hydrogen bubbles.','B: துத்தநாகம் அமிலத்துடன் தாக்கமுற்று ஐதரசன் குமிழிகளை வெளியேற்றும்.'),
        p('B(i)(b)','chemistry','Which setup shows no displacement? (C: copper in ZnSO₄.)','எந்த அமைப்பில் இடப்பெயர்ச்சித் தாக்கம் நிகழாது? (C: ZnSO₄ இல் செம்பு.)',
          'C. Copper is less reactive than zinc, so it cannot displace zinc from its salt.','C. செம்பு துத்தநாகத்தைவிடக் குறைந்த தாக்கத்திறனுடையதால் அதன் உப்பிலிருந்து துத்தநாகத்தை இடம்பெயர்க்காது.'),
        p('B(i)(c)','chemistry','Which setup gives a precipitate? (D: BaCl₂ + Na₂SO₄.)','எந்த அமைப்பில் வீழ்படிவு தோன்றும்? (D: BaCl₂ + Na₂SO₄.)',
          'D: a white barium sulfate precipitate. Ba²⁺ + SO₄²⁻ → BaSO₄(s); the product is insoluble.','D: வெள்ளை பேரியம் சல்பேற் வீழ்படிவு. Ba²⁺ + SO₄²⁻ → BaSO₄(s); விளைவு கரையாதது.'),
        p('B(ii)','chemistry','Write the balanced equation for zinc and hydrochloric acid.','துத்தநாகம், ஐதரோகுளோரிக் அமிலத் தாக்கத்தின் சமப்படுத்திய சமன்பாட்டை எழுதுக.',
          'Zn + 2HCl → ZnCl₂ + H₂. One zinc atom requires two chloride ions; two hydrogen ions form one hydrogen molecule.','Zn + 2HCl → ZnCl₂ + H₂. ஒரு துத்தநாகத்திற்கு இரண்டு குளோரைட் அயன்கள் தேவை; இரண்டு ஐதரசன் அயன்கள் ஒரு H₂ மூலக்கூறைத் தரும்.'),
        p('B(iii)','chemistry','Which ions formed in A account for the permanganate colour change?','A இல் உருவாகும் எந்த அயன்கள் பெர்மங்கனேற்றின் நிறமாற்றத்திற்குக் காரணம்?',
          'Fe²⁺ ions form when iron dissolves in acid. They reduce acidified permanganate while being oxidised to Fe³⁺, removing the purple colour.','இரும்பு அமிலத்தில் கரையும்போது Fe²⁺ அயன்கள் உருவாகும். அவை அமிலப் பெர்மங்கனேற்றை ஒடுக்கித் தாம் Fe³⁺ ஆக ஒட்சியேற்றப்படும்; ஊதா நிறம் மறையும்.'),
        p('C(i)','physics','What happens to the balloon volume when cooled to 10°C?','10°C வரை குளிர்விக்கும்போது பலூனின் கனவளவுக்கு என்ன நிகழும்?',
          'It decreases, assuming the gas amount stays fixed and external pressure is approximately constant.','வாயுவின் அளவு மாறாமலும் வெளி அமுக்கம் ஏறத்தாழ மாறாமலும் இருந்தால் கனவளவு குறையும்.'),
        p('C(ii)','physics','Name the gas law for this change.','இம்மாற்றத்திற்கான வாயு விதி என்ன?',
          'Charles’s law: V/T is constant for a fixed amount of gas at constant pressure, with T in kelvin.','சாள்ஸ் விதி: மாறா அமுக்கத்தில் குறிப்பிட்ட வாயுவிற்கு V/T மாறிலி; T கெல்வினில் இருக்க வேண்டும்.'),
        p('C(iii)','physics','Describe the volume–absolute temperature graph.','கனவளவு–தனிவெப்பநிலை வரைபை விவரிக்கவும்.',
          'Plot V vertically and T (K) horizontally: a straight line through the origin in the ideal-gas model. A Celsius graph does not pass through (0,0).','நிலைக்குத்தாக V, கிடையாக T (K): இலட்சிய வாயு மாதிரியில் ஆதியூடாகச் செல்லும் நேர்கோடு. செல்சியஸ் வரைபு (0,0) வழியாகச் செல்லாது.')])

    written(4,['physics'],['Forces','Circuits','Optics','Electronics'],[8], 'Evaluate statements and applications around the school.', 'பாடசாலைச் சூழலிலுள்ள கூற்றுக்களையும் பயன்பாடுகளையும் மதிப்பிடுக.',[
        p('A(i)','physics','True or false: pushing perpendicular to a door near its hinge makes it easier to open.','உண்மையா பொய்யா: கீலுக்கருகில் செங்குத்தாகத் தள்ளும்போது கதவு இலகுவாகத் திறக்கும்.',
          'False. Moment = force × perpendicular distance from hinge. Apply the same force farther from the hinge for a greater turning effect.','பொய். திருப்புத்திறன் = விசை × கீலிலிருந்து செங்குத்துத் தூரம். அதே விசையை கீலிலிருந்து தொலைவில் பிரயோகித்தால் அதிக திருப்புத்திறன் கிடைக்கும்.',lessons=['chapter-11-turning-effect']),
        p('A(ii)','physics','True or false: a current-carrying conductor has a magnetic field around it.','உண்மையா பொய்யா: மின்னோட்டம் செல்லும் கடத்தியைச் சுற்றிக் காந்தப்புலம் காணப்படும்.',
          'True. Electric current produces a magnetic field; its direction around a straight wire follows the right-hand grip rule.','உண்மை. மின்னோட்டம் காந்தப்புலத்தை உருவாக்கும்; நேர்கடத்தியைச் சுற்றிய திசையை வலக்கைப் பிடி விதி தரும்.',lessons=['g11-chapter-13-electromagnetism']),
        p('B(i)','physics','Which listed school equipment uses semiconductors?','குறிப்பிட்ட பாடசாலை உபகரணங்களில் அரைக்கடத்திகள் பயன்படுவது எதில்?',
          'The photocopier in the library. Its light-sensitive semiconductor surface helps form the image.','நூலகத்தின் ஒளிப்பிரதி இயந்திரம். ஒளியுணர் அரைக்கடத்தி மேற்பரப்பு படத்தை உருவாக்க உதவும்.',lessons=['g11-chapter-11-electronics']),
        p('B(ii)','physics','Why are thick curtains fitted in the hall?','மண்டபத்தில் தடித்த திரைச்சீலைகள் ஏன் பொருத்தப்படுகின்றன?',
          'They absorb sound and reduce repeated reflections, echoes and reverberation.','ஒலியை உறிஞ்சி மீள்மீள் தெறிப்பையும் எதிரொலியையும் குறைக்கும்.',lessons=['g11-chapter-04-waves']),
        p('B(iii)(a)','physics','Name the microscope lens near the onion cells.','வெங்காயக் கலங்களுக்கருகிலுள்ள நுணுக்குக்காட்டி வில்லை என்ன?',
          'The objective lens, a converging lens close to the specimen.','பொருள்வில்லை: மாதிரிக்கருகிலுள்ள குவிவு வில்லை.',lessons=['g11-chapter-05-geometrical-optics']),
        p('B(iii)(b)','physics','Name the lens near the eye.','கண்ணுக்கருகிலுள்ள வில்லை என்ன?',
          'The eyepiece, which magnifies the image produced by the objective.','கண்வில்லை: பொருள்வில்லை உருவாக்கிய விம்பத்தை உருப்பெருக்கும்.',lessons=['g11-chapter-05-geometrical-optics']),
        p('B(iv)','physics','A cupboard is pushed with 150 N against 135 N friction. Find the resultant.','அலுமாரிக்கு 150 N தள்ளுவிசையும் எதிராக 135 N உராய்வும் உள்ளன. விளைவுவிசையைக் காண்க.',
          '15 N in the direction of the push. Opposing parallel forces subtract.','தள்ளும் திசையில் 15 N. எதிர்த்திசை சமாந்தர விசைகளை கழிக்க வேண்டும்.',steps=[('Fnet = 150 − 135 = 15 N.','Fnet = 150 − 135 = 15 N.')],lessons=['chapter-05-friction','chapter-09-resultant-force']),
        p('B(v)(a)','physics','Describe/draw the Ohm’s law circuit, including six components.','ஆறு உபகரணங்களுடன் ஓமின் விதிக்கான சுற்றை வரைக/விவரிக்கவும்.',
          'Battery, switch, rheostat, ammeter and test resistor are in series. Connect a voltmeter in parallel across the test resistor. The ammeter measures its current; the voltmeter measures its potential difference.','மின்கலம், ஆளி, மாறுதடை, அம்மீற்றர், சோதனைத் தடை தொடர் இணைப்பில். சோதனைத் தடைக்குக் குறுக்காக வோல்ற்மீற்றரைச் சமாந்தரமாக இணைக்கவும். அம்மீற்றர் மின்னோட்டத்தையும் வோல்ற்மீற்றர் அழுத்த வேறுபாட்டையும் அளக்கும்.',lessons=['g10-chapter-19-current-electricity']),
        p('B(v)(b)','physics','Why open the switch between readings?','அளவீடுகளுக்கிடையில் ஆளியை ஏன் திறக்க வேண்டும்?',
          'To limit heating. Ohm’s law requires constant temperature; heating changes the resistance and makes comparison unreliable.','சூடாதலைக் குறைக்க. ஓமின் விதிக்கு மாறா வெப்பநிலை தேவை; சூடாதல் தடையை மாற்றி ஒப்பீட்டைப் பாதிக்கும்.',lessons=['g10-chapter-19-current-electricity']),
        p('C(i)','physics','Name two main circuits in a mobile phone.','கையடக்கத் தொலைபேசியின் முக்கிய இரண்டு சுற்றுகள் என்ன?',
          'Transmitter and receiver circuits: one sends signals and the other receives them.','செலுத்தி, பெறுநர் சுற்றுகள்: ஒன்று சமிக்ஞையை அனுப்பும்; மற்றொன்று பெறும்.'),
        p('C(ii)','physics','Draw the two-input OR gate symbol.','இரண்டு உள்ளீட்டு OR வாயிலின் குறியீட்டை வரைக.',
          'Two inputs enter the curved left side and one output leaves the pointed right side. For inputs 00, 01, 10, 11 the outputs are 0, 1, 1, 1: either input high makes the output high. Use the provided model diagram.','வளைந்த இடப்பக்கத்தில் இரண்டு உள்ளீடுகள்; கூரான வலப்பக்கத்தில் ஒரு வெளியீடு. 00, 01, 10, 11 இற்கு முறையே 0, 1, 1, 1. ஓர் உள்ளீடாவது 1 எனில் வெளியீடு 1. மாதிரிப் படத்தைப் பார்க்கவும்.',lessons=['g11-chapter-11-electronics'])])

    written(5,['biology'],['Reproduction','Human physiology'],[9], 'Vegetative propagation and reproduction in humans.', 'தாவர இனப்பெருக்கமும் மனித இனப்பெருக்கமும்.',[
        p('A(i)','biology','Name the underground structures in ginger and potato.','இஞ்சி, உருளைக்கிழங்கின் நிலக்கீழ் அமைப்புக்களைப் பெயரிடுக.',
          'Ginger: rhizome. Potato: stem tuber. Both are modified stems, not roots.','இஞ்சி: மட்டநிலத்தண்டு. உருளைக்கிழங்கு: தண்டுக் கிழங்கு. இரண்டும் மாற்றமடைந்த தண்டுகள்; வேர்கள் அல்ல.'),
        p('A(ii)','biology','Give a stem feature shared by these structures.','இவ்வமைப்புக்கள் தண்டுகள் என்பதைக் காட்டும் பொதுப் பண்பு ஒன்றைக் குறிப்பிடுக.',
          'Nodes with buds (and internodes). The “eyes” of a potato are buds that can form shoots.','கணுக்களும் அரும்புகளும் (கணுவிடைகளும்). உருளைக்கிழங்கின் “கண்கள்” முளைகளைத் தரும் அரும்புகள்.'),
        p('A(iii)','biology','Name this type of reproduction.','இவ்வினப்பெருக்க வகை என்ன?',
          'Vegetative propagation, a form of asexual reproduction. No fusion of gametes is needed.','தாவர வழி இனப்பெருக்கம்; பாலிலி இனப்பெருக்க வகை. பாலணுக்களின் இணைவு தேவையில்லை.'),
        p('A(iv)','biology','Why is stored food useful here?','இங்கு சேமித்த உணவு ஏன் பயனுள்ளது?',
          'It supplies materials and energy for new shoots before enough leaves develop for photosynthesis.','ஒளித்தொகுப்பிற்கு போதிய இலைகள் உருவாகும்வரை புதிய முளைகளுக்கு மூலப்பொருளும் சக்தியும் வழங்கும்.'),
        p('B(i)','biology','Name male and female human gametes.','மனிதனின் ஆண், பெண் பாலணுக்களைப் பெயரிடுக.',
          'Sperm and ovum (egg), respectively. Their nuclei fuse at fertilisation.','முறையே விந்து, முட்டை. கருக்கட்டலில் அவற்றின் கருக்கள் இணையும்.'),
        p('B(ii)(a)','biology','Which division produces gametes?','பாலணுக்களை உருவாக்கும் பிரிவு எது?',
          'Meiosis: it reduces the chromosome number from diploid to haploid.','ஒடுக்கற்பிரிவு: நிறமூர்த்த எண்ணிக்கையை இருமயத்திலிருந்து ஒருமயமாகக் குறைக்கும்.'),
        p('B(ii)(b)','biology','Give a biological importance of that division.','அப்பிரிவின் உயிரியல் முக்கியத்துவம் ஒன்றைக் குறிப்பிடுக.',
          'Halving chromosome number allows fertilisation to restore the species’ number. Recombination and independent assortment also create genetic variation.','நிறமூர்த்த எண்ணிக்கையை அரைவாசியாக்குவதால் கருக்கட்டலில் இனத்தின் எண்ணிக்கை மீளும். மீள்சேர்க்கையும் சுயாதீன ஒதுக்கீடும் மரபு மாறுபாட்டைத் தரும்.'),
        p('B(iii)(a)','biology','For a group-B mother, which ABO red-cell groups are compatible in the school model?','B குருதியுள்ள தாய்க்கு பாடசாலை ABO மாதிரியில் பொருந்தும் சிவப்புக் கலக் குழுக்கள் எவை?',
          'B or O for red cells. B plasma has anti-A antibodies, so A or AB red cells are incompatible. This simplified exam answer is not a transfusion decision: clinical compatibility testing is required.','சிவப்புக் கலங்களுக்கு B அல்லது O. B பிளாஸ்மாவில் anti-A இருப்பதால் A, AB பொருந்தாது. இது எளிய பரீட்சை மாதிரி; உண்மையான குருதி வழங்கலுக்கு மருத்துவப் பொருத்தச் சோதனை தேவை.'),
        p('B(iii)(b)','biology','Which other blood-group factor must be considered?','மேலும் கவனிக்க வேண்டிய குருதிக் காரணி எது?',
          'The Rh factor, as well as compatibility testing. ABO group alone is insufficient.','Rh காரணி மற்றும் பொருத்தச் சோதனை. ABO குழு மட்டும் போதாது.'),
        p('B(iv)(a)','biology','State the role of progesterone in pregnancy.','கர்ப்பத்தில் புரொஜெஸ்ரரோனின் பணி என்ன?',
          'Maintains the uterine lining, helping support the developing embryo and pregnancy.','கருப்பை அகப்படையைப் பேணி வளர்கருவையும் கர்ப்பத்தையும் ஆதரிக்கும்.'),
        p('B(iv)(b)','biology','State a postnatal role of oxytocin.','பிறப்பின் பின் ஒக்சிற்றோசினின் பணி ஒன்றைக் குறிப்பிடுக.',
          'Milk ejection: contraction around mammary glands pushes milk into ducts. Distinguish this from prolactin, which stimulates milk production.','பால் வெளியேற்றம்: பால்சுரப்பிகளைச் சுற்றிய சுருக்கம் பாலை நாளங்களுக்குத் தள்ளும். பால் உற்பத்தியைத் தூண்டும் புரொலாக்ரினிலிருந்து வேறுபடுத்தவும்.')])

    written(6,['biology'],['Vertebrates','Nervous system'],[9], 'Vertebrate adaptations and functions of the brain.', 'முள்ளந்தண்டுளிகளின் இசைவாக்கமும் மூளையின் பணிகளும்.',[
        p('A(i)','biology','Give two traits shared by birds and mammals.','பறவைகளும் முலையூட்டிகளும் கொண்ட பொதுப் பண்புகள் இரண்டைக் குறிப்பிடுக.',
          'Endothermy (maintaining body temperature through metabolic heat) and a four-chambered heart, with separation of oxygenated and deoxygenated blood.','அனுசேப வெப்பத்தால் உடல்வெப்பத்தைப் பேணுதல், நான்கு அறைகளுள்ள இதயம். ஒட்சிசனேறிய, ஒட்சிசனற்ற குருதி பிரிந்திருக்கும்.'),
        p('A(ii)','biology','Which body shape helps birds move through air?','வளியில் செல்ல உதவும் பறவையின் உடல் வடிவம் என்ன?',
          'A streamlined body, which reduces air resistance.','வளியுராய்வைக் குறைக்கும் ஒழுக்குருவான உடல்.'),
        p('A(iii)','biology','Which limbs are modified as wings?','சிறகுகளாக மாற்றமடைந்த அங்கங்கள் எவை?',
          'The forelimbs. Hindlimbs retain other roles such as walking or perching.','முன்னங்கங்கள். பின்னங்கங்கள் நடத்தல், அமர்தல் போன்ற பணிகளைச் செய்கின்றன.'),
        p('A(iv)(a)','biology','Name the other three vertebrate groups.','ஏனைய மூன்று முள்ளந்தண்டுளிக் குழுக்களைப் பெயரிடுக.',
          'Fish, amphibians and reptiles (in the five-group school classification).','பாடசாலையின் ஐந்து குழு வகைப்பாட்டில் மீன்கள், ஈரூடகவாழிகள், ஊர்வன.'),
        p('A(iv)(b)','biology','Which school vertebrate group first adapted to life on land?','நிலவாழ்க்கைக்கு முதலில் இசைவாக்கமடைந்த பாடசாலை முள்ளந்தண்டுளிக் குழு எது?',
          'Amphibians. They show adaptations for land but generally still depend on water for reproduction.','ஈரூடகவாழிகள். நிலவாழ்க்கை இசைவாக்கமிருந்தாலும் பொதுவாக இனப்பெருக்கத்திற்கு நீரைச் சார்ந்திருக்கும்.'),
        p('B(i)','biology','Name two hindbrain structures in the list.','பட்டியலிலுள்ள பின்மூளையின் இரண்டு பகுதிகளைக் குறிப்பிடுக.',
          'Cerebellum and medulla oblongata.','சிறுமூளை, நீள்வளைய மையவிழையம்.'),
        p('B(ii)(a)','biology','Which part is responsible for memory?','ஞாபகத்திற்குப் பொறுப்பான பகுதி எது?',
          'Cerebrum: involved in memory, learning and conscious processing.','பெருமூளை: ஞாபகம், கற்றல், நனவுணர்வுச் செயற்பாடுகளில் பங்கெடுக்கும்.'),
        p('B(ii)(b)','biology','Which part regulates heartbeat?','இதயத் துடிப்பை ஒழுங்குபடுத்தும் பகுதி எது?',
          'Medulla oblongata: regulates vital involuntary functions.','நீள்வளைய மையவிழையம்: முக்கிய தன்னிச்சையற்ற பணிகளை ஒழுங்குபடுத்தும்.'),
        p('B(ii)(c)','biology','Which part regulates breathing?','சுவாசத்தை ஒழுங்குபடுத்தும் பகுதி எது?',
          'Medulla oblongata: its respiratory centres help regulate the rhythm of breathing.','நீள்வளைய மையவிழையம்: அதன் சுவாச மையங்கள் சுவாசத் தாளத்தை ஒழுங்குபடுத்த உதவும்.'),
        p('B(ii)(d)','biology','Which part coordinates muscle movements?','தசை இயக்கங்களை ஒருங்கிணைக்கும் பகுதி எது?',
          'Cerebellum: coordinates timing and precision of movements.','சிறுமூளை: இயக்கங்களின் நேரத்தையும் துல்லியத்தையும் ஒருங்கிணைக்கும்.'),
        p('B(ii)(e)','biology','Which part regulates body temperature?','உடல்வெப்பநிலையை ஒழுங்குபடுத்தும் பகுதி எது?',
          'Hypothalamus, involved in homeostasis.','ஐப்போதலமசு: உடலின் அகச்சூழல் சமநிலையைப் பேணும்.'),
        p('B(ii)(f)','biology','Which part interprets visual and auditory sensations?','காட்சி, கேள்வி உணர்வுகளைப் புரிந்துகொள்ளும் பகுதி எது?',
          'Cerebrum: conscious interpretation of sensory information.','பெருமூளை: புலனுணர்வுத் தகவல்களை நனவுணர்வுடன் விளக்கும்.'),
        p('B(iii)(a)','biology','Where can immediate reflex responses be coordinated?','உடனடி மறிவினைகள் எங்கு ஒருங்கிணைக்கப்படலாம்?',
          'The brain or spinal cord, depending on the reflex. A reflex does not require a conscious decision before the response.','மறிவினையைப் பொறுத்து மூளை அல்லது முண்ணாண். எதிர்வினைக்கு முன் நனவுணர்வுத் தீர்மானம் தேவையில்லை.'),
        p('B(iii)(b)(I)','biology','Which centre controls pupil response to light?','ஒளிக்கான கண்மணி மறிவினையின் மையம் எது?',
          'Midbrain, for the pupil light reflex.','கண்மணி ஒளி மறிவினைக்கு நடுமூளை.'),
        p('B(iii)(b)(II)','biology','Which centre coordinates withdrawing a hand from a hot object?','சூடான பொருளிலிருந்து கையை விலக்கும் மறிவினையின் மையம் எது?',
          'Spinal cord. The sensory signal reaches the spinal reflex pathway and a motor signal withdraws the hand.','முண்ணாண். புலனுணர்வுச் சமிக்ஞை முண்ணாண் மறிவினைப் பாதையைக் கடந்த பின் இயக்கச் சமிக்ஞை கையை விலக்குகிறது.')])

    written(7,['chemistry'],['Reaction rates','Combustion'],[10], 'Compare reactions, combustion and the three magnesium–acid experiments shown.', 'தாக்கங்கள், தகனம், காட்டப்பட்ட மக்னீசியம்–அமிலப் பரிசோதனைகளை ஒப்பிடுக.',[
        p('i(a)','chemistry','Give one slow reaction from the list.','பட்டியலிலுள்ள மெதுவான தாக்கம் ஒன்றைக் குறிப்பிடுக.',
          'Rusting of iron (fruit ripening is another slow example). These occur over a much longer time than rapid combustion.','இரும்பு துருப்பிடித்தல்; பழங்கள் பழுத்தலும் எடுத்துக்காட்டு. விரைவான தகனத்தைவிட நீண்ட நேரத்தில் நிகழும்.'),
        p('i(b)','chemistry','Give one fast reaction from the list.','பட்டியலிலுள்ள வேகமான தாக்கம் ஒன்றைக் குறிப்பிடுக.',
          'Burning petrol, or magnesium reacting with dilute HCl. Products form rapidly under the stated conditions.','பெற்றோல் தீப்பற்றல் அல்லது மக்னீசியம் ஐதான HCl உடன் தாக்கமுறுதல். குறிப்பிட்ட நிலையில் விளைவுகள் விரைவாக உருவாகும்.'),
        p('ii(a)','chemistry','Which listed reaction requires microorganisms?','பட்டியலிலுள்ள எந்தத் தாக்கத்திற்கு நுண்ணங்கிகள் தேவை?',
          'Conversion of toddy to vinegar: microbes help oxidise ethanol to ethanoic (acetic) acid in the presence of oxygen.','கள்ளு வினாகிரியாக மாறுதல்: ஒட்சிசனுடன் எதனோலை எதனோயிக் (அசற்றிக்) அமிலமாக ஒட்சியேற்ற நுண்ணங்கிகள் உதவும்.'),
        p('ii(b)','chemistry','Write the equation for this conversion.','அம்மாற்றத்திற்கான சமன்பாட்டை எழுதுக.',
          'C₂H₅OH + O₂ → CH₃COOH + H₂O. Carbon, hydrogen and oxygen atoms balance on both sides.','C₂H₅OH + O₂ → CH₃COOH + H₂O. இருபக்கங்களிலும் C, H, O அணுக்களின் எண்ணிக்கை சமம்.'),
        p('iii(a)','chemistry','State the conditions for combustion.','தகனத்திற்குத் தேவையான காரணிகள் என்ன?',
          'Fuel, oxygen and sufficient heat to reach ignition temperature: the fire triangle. Removing any one interrupts combustion.','எரிபொருள், ஒட்சிசன், தீப்பற்றல் வெப்பநிலையை அடையும் வெப்பம். இம்மூன்றில் ஒன்றை நீக்கினால் தகனம் தடைப்படும்.'),
        p('iii(b)','chemistry','Name a suitable extinguisher for a petrol fire in the exam scenario.','பரீட்சைச் சூழலில் பெற்றோல் தீக்கு ஏற்ற தீயணைப்புக் கருவியைப் பெயரிடுக.',
          'A foam extinguisher suitable for flammable liquids. Foam forms a cover over the liquid surface.','எரியக்கூடிய திரவங்களுக்கு ஏற்ற நுரைத் தீயணைப்பான். நுரை திரவ மேற்பரப்பில் மூடியை உருவாக்கும்.'),
        p('iii(c)','chemistry','Explain how that extinguisher works.','அத்தீயணைப்பான் எவ்வாறு செயற்படுகிறது?',
          'The foam blanket separates the fuel from oxygen, suppresses vapour release and helps cool the surface, interrupting combustion.','நுரைப்படை எரிபொருளை ஒட்சிசனிலிருந்து பிரித்து ஆவிவெளியேற்றத்தைக் குறைத்து மேற்பரப்பைக் குளிரச்செய்கிறது; தகனம் தடைப்படும்.'),
        p('iv(a)','chemistry','Which setup reacts fastest: (1) 0.1 M, three 1 cm Mg pieces; (2) 0.1 M, six 0.5 cm pieces; (3) 0.2 M, six 0.5 cm pieces?','எந்த அமைப்பில் தாக்கம் மிகவேகமாக நடைபெறும்: (1) 0.1 M, மூன்று 1 cm Mg துண்டுகள்; (2) 0.1 M, ஆறு 0.5 cm துண்டுகள்; (3) 0.2 M, ஆறு 0.5 cm துண்டுகள்?',
          'Setup (3): increased exposed surface area and higher acid concentration increase collision frequency.','அமைப்பு (3): அதிக வெளிப்பட்ட மேற்பரப்பும் அதிக அமிலச் செறிவும் மோதல் நிகழ்வுகளை அதிகரிக்கும்.'),
        p('iv(b)(I)','chemistry','What factor is tested by comparing (1) and (2)?','(1), (2) ஐ ஒப்பிடும்போது சோதிக்கப்படும் காரணி என்ன?',
          'Surface area (piece size), with total magnesium and acid concentration kept the same. Smaller pieces expose more surface.','மேற்பரப்பளவு (துண்டுகளின் அளவு). மொத்த Mg, அமிலச் செறிவு மாறாது; சிறிய துண்டுகள் அதிக மேற்பரப்பை வெளிப்படுத்தும்.'),
        p('iv(b)(II)','chemistry','What factor is tested by comparing (2) and (3)?','(2), (3) ஐ ஒப்பிடும்போது சோதிக்கப்படும் காரணி என்ன?',
          'Acid concentration. Magnesium pieces and acid volume are unchanged; concentration changes from 0.1 to 0.2 mol dm⁻³.','அமிலச் செறிவு. Mg துண்டுகளும் அமிலக் கனவளவும் மாறாது; செறிவு 0.1 இலிருந்து 0.2 mol dm⁻³ ஆகிறது.'),
        p('iv(c)','chemistry','Find the amount in 2.4 g magnesium (M = 24 g mol⁻¹).','2.4 g மக்னீசியத்தின் மூல் அளவைக் காண்க (M = 24 g mol⁻¹).',
          '0.10 mol. Divide mass by molar mass; do not multiply.','0.10 mol. திணிவை மூலர் திணிவால் வகுக்கவும்; பெருக்க வேண்டாம்.',steps=[('n = m/M = 2.4/24 = 0.10 mol.','n = m/M = 2.4/24 = 0.10 mol.')]),
        p('iv(d)','chemistry','How could the fastest reaction be recognised without collecting the gas?','வாயுவைச் சேகரிக்காமல் உயர் வீதத் தாக்கத்தை எவ்வாறு இனங்காணலாம்?',
          'Compare the number of bubbles released in the same time, or the time taken for equal masses of magnesium to disappear. Faster bubbling/shorter disappearance time indicates the greater rate.','ஒரே நேரத்தில் வெளியாகும் குமிழிகளின் எண்ணிக்கையை அல்லது சம திணிவு Mg மறையும் நேரத்தை ஒப்பிடுக. அதிக குமிழிகள்/குறைந்த மறைவு நேரம் உயர் தாக்க வீதத்தைக் காட்டும்.')])

    written(8,['chemistry','physics'],['Solutions','Materials','Environment'],[10,11], 'Magnesium chloride solutions, dissolved gases and building materials.', 'மக்னீசியம் குளோரைட் கரைசல்கள், கரைந்த வாயுக்கள், கட்டடப் பொருள்கள்.',[
        p('A(i)(a)','chemistry','Why is water a suitable solvent for MgCl₂?','MgCl₂ இற்கு நீர் ஏன் ஏற்ற கரைப்பான்?',
          'Water is polar and hydrates the Mg²⁺ and Cl⁻ ions of this soluble ionic compound. The ions separate into the solution.','நீர் முனைவுள்ளதால் கரையக்கூடிய அயன் சேர்வையின் Mg²⁺, Cl⁻ அயன்களைச் சூழும்; அயன்கள் கரைசலில் பிரிந்து செல்லும்.'),
        p('A(i)(b)','chemistry','30 g MgCl₂ makes 100 g solution. Find mass percentage.','30 g MgCl₂ கொண்டு 100 g கரைசல் தயாரிக்கப்படுகிறது. திணிவுச் சதவீதத்தைக் காண்க.',
          '30% w/w. The denominator is mass of the solution, not mass of water alone.','30% w/w. கீழெண் மொத்தக் கரைசலின் திணிவு; நீரின் திணிவு மட்டும் அல்ல.',steps=[('% = (solute mass/solution mass) × 100 = (30/100) × 100 = 30%.','% = (கரையத்தின் திணிவு/கரைசலின் திணிவு) × 100 = 30%.')]),
        p('A(ii)(a)','chemistry','After another 30 g is stirred in at 25°C, some crystals remain. Name the solution state.','25°C இல் மேலும் 30 g சேர்த்துக் கலக்கிய பின் சில பளிங்குகள் எஞ்சுகின்றன. கரைசலின் நிலை என்ன?',
          'Saturated at 25°C: no more solute dissolves under those conditions. The presence of excess solid does not mean all 60 g has dissolved.','25°C இல் நிரம்பிய கரைசல். அந்நிலையில் மேலும் கரையம் கரையாது. எஞ்சிய திண்மம் இருப்பதால் 60 g முழுவதும் கரைந்ததாகக் கொள்ள முடியாது.'),
        p('A(ii)(b)','chemistry','What happens on heating to 60°C?','60°C வரை சூடாக்கும்போது என்ன நிகழும்?',
          'More of the remaining MgCl₂ crystals dissolve; in the described observation the crystals disappear.','எஞ்சிய MgCl₂ பளிங்குகள் மேலும் கரையும்; குறிப்பிட்ட அவதானிப்பில் அவை மறையும்.'),
        p('A(ii)(c)','chemistry','Explain the observation.','அவ்வவதானிப்பை விளக்குக.',
          'MgCl₂ solubility increases over this temperature interval, so the same solvent can dissolve more salt. Do not generalise this to every solute.','இவ்வெப்பநிலை இடைவெளியில் MgCl₂ கரைதிறன் அதிகரிப்பதால் அதே கரைப்பானில் அதிக உப்பு கரையும். எல்லாக் கரையங்களுக்கும் இதைப் பொதுமைப்படுத்த வேண்டாம்.'),
        p('A(iii)','chemistry','Why do bubbles appear when water is heated from 20°C to 80°C?','நீரை 20°C இலிருந்து 80°C வரை சூடாக்கும்போது ஏன் குமிழிகள் தோன்றுகின்றன?',
          'Dissolved air escapes because gas solubility decreases as temperature increases. These early bubbles are not evidence that water is boiling at 80°C.','வெப்பநிலை அதிகரிக்கும்போது வாயுக்களின் கரைதிறன் குறைந்து கரைந்த வளி வெளியேறும். இக்குமிழிகள் 80°C இல் நீர் கொதிப்பதைக் காட்டவில்லை.'),
        p('B(i)(a)','chemistry','Name the alloy used to reinforce buildings.','கட்டடங்களை வலுப்படுத்தப் பயன்படும் கலப்புலோகம் எது?',
          'Steel, an iron-based alloy used for reinforcement.','உருக்கு: கட்டட வலுப்படுத்தலுக்குப் பயன்படும் இரும்பை அடிப்படையாகக் கொண்ட கலப்புலோகம்.'),
        p('B(i)(b)','chemistry','Name its main metal.','அதன் பிரதான உலோகம் எது?',
          'Iron (Fe); controlled carbon content changes the alloy’s properties.','இரும்பு (Fe). காபனின் அளவு கலப்புலோகப் பண்புகளை மாற்றும்.'),
        p('B(ii)','chemistry','Which building mixture uses calcium oxide?','கல்சியம் ஒட்சைடு பயன்படுத்தப்படும் கட்டடக் கலவை எது?',
          'Lime plaster/mortar. Quicklime reacts with water to form calcium hydroxide (slaked lime), which is used in the mixture.','சுண்ணாம்புச் சாந்து. சுட்ட சுண்ணாம்பு நீருடன் தாக்கமுற்று கல்சியம் ஐதரொட்சைடு உருவாகும்; அது கலவையில் பயன்படும்.'),
        p('B(iii)','chemistry','Why must fresh concrete be spread before it hardens?','புதிய கொங்கிறீற்றை இறுகுமுன் ஏன் பரப்ப வேண்டும்?',
          'Cement reacts with water through hydration and sets. Once set, the concrete cannot be shaped as a workable paste; this is not simply drying.','சீமெந்து நீருடன் நீரேற்றத் தாக்கமுற்று இறுகும். இறுகிய பின் பசையாக வடிவமைக்க முடியாது; இது உலர்தல் மட்டும் அல்ல.'),
        p('B(iv)','chemistry','Name a harmful metal associated with some paints.','சில வர்ணங்களிலுள்ள தீங்கான உலோகம் ஒன்றைக் குறிப்பிடுக.',
          'Lead (Pb), or cadmium (Cd). Their compounds/ions can cause toxicity. Not all modern paints contain these ingredients.','ஈயம் (Pb) அல்லது கட்மியம் (Cd). அவற்றின் சேர்வைகள்/அயன்கள் நச்சுத்தன்மையுடையவை. எல்லா நவீன வர்ணங்களிலும் இவை இருப்பதில்லை.'),
        p('B(v)','biology','Give two environmental effects of obtaining building materials.','கட்டடப் பொருள்கள் பெறுவதனால் ஏற்படும் சூழல் பாதிப்புக்கள் இரண்டைக் குறிப்பிடுக.',
          'Forest/habitat destruction from timber extraction and loss of biodiversity; quarrying can also cause dust, erosion and habitat loss. Give two distinct effects.','மரப்பொருளுக்கான காடழிப்பும் வாழிட அழிப்பும்; உயிர்ப்பல்வகைமை இழப்பு. கல்லகழ்தல் தூசி, அரிப்பு, வாழிட இழப்பையும் ஏற்படுத்தும். வேறுபட்ட இரண்டு விளைவுகளைக் கூறுக.')])

    written(9,['physics'],['Waves','Motion','Electrical safety'],[11,12], 'X-ray imaging, ambulance motion and electrical safety.', 'X கதிர்ப் படம், அம்புலன்ஸ் இயக்கம், மின்சாரப் பாதுகாப்பு.',[
        p('i','physics','Which X-ray property enables imaging an injured head?','காயமடைந்த தலையைப் படமாக்க உதவும் X கதிரின் இயல்பு என்ன?',
          'Penetration. Tissues absorb X-rays by different amounts; that contrast permits an image to form.','ஊடுருவும் தன்மை. திசுக்கள் வெவ்வேறு அளவில் X கதிர்களை உறிஞ்சுவதால் படத்தில் வேறுபாடு தோன்றும்.',lessons=['g11-chapter-04-waves']),
        p('ii(a)','physics','Which sound characteristic makes an ambulance siren distinguishable?','அம்புலன்ஸ் ஒலியை வேறுபடுத்த உதவும் ஒலியின் பண்பு எது?',
          'Quality or timbre: the waveform/mixture of frequencies differs from other sources, beyond loudness or pitch alone.','ஒலித்தரம்: அலைவடிவம்/மீடிறன் கலப்பு மற்ற ஒலிமூலங்களிலிருந்து வேறுபடும்; உரப்பும் சுருதியும் மட்டும் அல்ல.',lessons=['g11-chapter-04-waves']),
        p('ii(b)','physics','Find frequency when wavelength is 0.44 m and speed is 330 m s⁻¹.','அலைநீளம் 0.44 m, கதி 330 m s⁻¹ எனில் மீடிறனைக் காண்க.',
          '750 Hz. Frequency is wave speed divided by wavelength.','750 Hz. மீடிறன் = அலைக்கதி/அலைநீளம்.',steps=[('v = fλ, so f = v/λ = 330/0.44 = 750 Hz.','v = fλ; f = v/λ = 330/0.44 = 750 Hz.')],lessons=['g11-chapter-04-waves']),
        p('ii(c)','physics','Why is AMBULANCE written reversed on its front?','அம்புலன்ஸின் முன்புறப் பெயர் ஏன் இடவலமாக எழுதப்படுகிறது?',
          'A plane mirror produces lateral inversion, so the reversed lettering is read normally in the rear-view mirror ahead.','தள ஆடி இடவல மாற்றத்தை உருவாக்கும்; முன் வாகனத்தின் பின்பார்வை ஆடியில் எழுத்து நேராகப் படிக்கப்படும்.',lessons=['g11-chapter-05-geometrical-optics']),
        p('iii(a)','physics','Read the maximum velocity from the scan’s graph.','மூலத்தாளின் வரைபிலிருந்து அதிகபட்ச வேகத்தை வாசிக்கவும்.',
          '60 m s⁻¹, the height of the horizontal section of the velocity–time graph.','60 m s⁻¹: வேகம்–நேர வரைபின் கிடைப் பகுதியின் உயரம்.',lessons=['unit-02-motion-in-a-straight-line']),
        p('iii(b)','physics','The constant-speed section covers 15,000 m. Find its duration.','மாறா வேகப் பகுதியில் 15,000 m பயணிக்கிறது. அதன் நேரத்தைக் காண்க.',
          '250 s. The plateau’s duration is a difference of times, not its ending time-coordinate.','250 s. கிடைப் பகுதியின் காலஅளவு நேரங்களின் வேறுபாடு; அதன் இறுதி நேரக் குறியீடு அல்ல.',steps=[('t = s/v = 15,000/60 = 250 s.','t = s/v = 15,000/60 = 250 s.')],lessons=['unit-02-motion-in-a-straight-line']),
        p('iii(c)','physics','Find total distance: acceleration 40 s, plateau as above, braking 20 s.','மொத்தத் தூரத்தைக் காண்க: ஆர்முடுகல் 40 s, மேலுள்ள மாறா வேகப் பகுதி, அமர்முடுகல் 20 s.',
          '16,800 m. Distance is the area under this nonnegative velocity–time graph.','16,800 m. இந்நேர்ம வேகம்–நேர வரைபின் கீழுள்ள பரப்பே தூரம்.',steps=[('First triangle: ½ × 40 × 60 = 1,200 m.','முதல் முக்கோணம்: ½ × 40 × 60 = 1,200 m.'),('Rectangle: 15,000 m. Last triangle: ½ × 20 × 60 = 600 m.','செவ்வகம்: 15,000 m. இறுதி முக்கோணம்: ½ × 20 × 60 = 600 m.'),('Total = 1,200 + 15,000 + 600 = 16,800 m.','மொத்தம் = 1,200 + 15,000 + 600 = 16,800 m.')],lessons=['unit-02-motion-in-a-straight-line']),
        p('iii(d)','physics','Does the journey itself meet the 30-minute limit?','பயணம் மட்டும் 30 நிமிட வரம்பிற்குள் முடிகிறதா?',
          'Yes: 40 + 250 + 20 = 310 s = 5 min 10 s, less than 30 min. This only includes the graph’s journey, not waiting or medical preparation.','ஆம்: 40 + 250 + 20 = 310 s = 5 நிமிடம் 10 செக்கன்; 30 நிமிடங்களைவிடக் குறைவு. வரைபிலுள்ள பயணம் மட்டும்; காத்திருப்பு/மருத்துவ ஆயத்தம் சேர்க்கப்படவில்லை.',lessons=['unit-02-motion-in-a-straight-line']),
        p('iv(a)','physics','Name a device that protects a circuit from excessive current.','அதிக மின்னோட்டத்திலிருந்து சுற்றைப் பாதுகாக்கும் கருவி எது?',
          'A fuse (a suitable circuit breaker is another protective device). The exam’s fuse operates by melting.','உருகி (பொருத்தமான சுற்றுப் பிரிப்பானும் பாதுகாப்புக் கருவி). பரீட்சையின் உருகி உருகுவதால் செயற்படும்.',lessons=['g11-chapter-10-electric-appliances']),
        p('iv(b)','physics','Explain how the fuse protects the circuit.','உருகி எவ்வாறு சுற்றைப் பாதுகாக்கிறது?',
          'Excess current heats and melts the correctly rated fuse wire, opening the circuit and interrupting current. It must be in series, not parallel.','அதிக மின்னோட்டம் பொருத்தமான உருகிக்கம்பியைச் சூடாக்கி உருக்குவதால் சுற்று திறந்து மின்னோட்டம் நிற்கும். தொடர் இணைப்பில் இருக்க வேண்டும்.',lessons=['g11-chapter-10-electric-appliances']),
        p('v','physics','Give three electrical safety precautions.','மின்சாரப் பாதுகாப்பு நடவடிக்கைகள் மூன்றைக் குறிப்பிடுக.',
          'Avoid overloading sockets; keep damaged cables/appliances out of use; use correctly rated protective devices and proper earthing. These are safety principles, not repair instructions.','சொக்கற்றுகளை மிகைப்பளுவாக்காமை; சேதமான கம்பி/உபகரணங்களைப் பயன்படுத்தாமை; பொருத்தமான பாதுகாப்புக் கருவிகளும் புவித்தொடுப்பும். இவை பாதுகாப்புக் கொள்கைகள்; திருத்தச் செய்முறை அல்ல.',lessons=['g11-chapter-10-electric-appliances'])])

    written(10,['physics'],['Heat','Optics','Electronics'],[12], 'Solar heat, mirages, energy calculations and a photodiode.', 'சூரிய வெப்பம், கானல், சக்திக் கணிப்புக்கள், ஒளி இருவாயி.',[
        p('i(a)','physics','How does heat from the Sun reach Earth?','சூரிய வெப்பம் பூமியை எவ்வாறு அடைகிறது?',
          'Radiation: energy is carried by electromagnetic waves.','கதிர்ப்பு: மின்காந்த அலைகளால் சக்தி கடத்தப்படுகிறது.',lessons=['g11-chapter-09-heat']),
        p('i(b)','physics','Why can this transfer occur through space?','விண்வெளியூடாக இது ஏன் நிகழலாம்?',
          'Radiation needs no material medium, unlike conduction and convection. Space between Sun and Earth is largely vacuum.','கதிர்ப்பிற்கு சடப்பொருள் ஊடகம் தேவையில்லை; கடத்தல், உடன்காவலுக்கு தேவை. சூரியன்–பூமி இடைவெளி பெரும்பாலும் வெற்றிடம்.',lessons=['g11-chapter-09-heat']),
        p('ii(a)','physics','Explain a mirage over a hot road.','சூடான வீதியில் தோன்றும் கானலை விளக்குக.',
          'Hot air near the road has a lower refractive index than cooler air above. Light bends through these layers; the school model describes total internal reflection, making the sky appear as a water-like image.','வீதிக்கருகிலுள்ள சூடான வளியின் முறிவுச் சுட்டி மேலுள்ள குளிர்ந்த வளியைவிடக் குறைவு. ஒளி அடுக்குகளூடாக வளைகிறது; பாடசாலை மாதிரியில் முழு அகத்தெறிப்பால் வானின் விம்பம் நீர்போலத் தெரிகிறது.',lessons=['g11-chapter-05-geometrical-optics']),
        p('ii(b)(I)','physics','Find heat absorbed by one 30 kg glass sheet, c = 1050 J kg⁻¹ K⁻¹, temperature rise 5°C.','30 kg கண்ணாடித் தகடு உறிஞ்சும் வெப்பத்தைக் காண்க: c = 1050 J kg⁻¹ K⁻¹, வெப்பநிலை உயர்வு 5°C.',
          '157,500 J. A temperature difference of 5°C equals 5 K.','157,500 J. 5°C வெப்பநிலை வேறுபாடு 5 K இற்கு சமம்.',steps=[('Q = mcΔT = 30 × 1050 × 5 = 157,500 J.','Q = mcΔT = 30 × 1050 × 5 = 157,500 J.')],lessons=['g11-chapter-09-heat']),
        p('ii(b)(II)','physics','Find total heat for 40 identical sheets.','இதே போன்ற 40 தகடுகளுக்கான மொத்த வெப்பத்தைக் காண்க.',
          '6,300,000 J = 6.3 MJ, assuming each sheet has the same temperature rise.','6,300,000 J = 6.3 MJ; எல்லாத் தகடுகளுக்கும் ஒரே வெப்பநிலை உயர்வு எனக் கொள்ளப்படுகிறது.',steps=[('Qtotal = 40 × 157,500 = 6,300,000 J.','Qtotal = 40 × 157,500 = 6,300,000 J.')],lessons=['g11-chapter-09-heat']),
        p('ii(c)','physics','Find energy used by a 0.1 kW fan for half an hour.','0.1 kW மின்விசிறி அரை மணிநேரத்தில் பயன்படுத்தும் சக்தியைக் காண்க.',
          '0.05 kWh = 180,000 J. Keep power/time units consistent.','0.05 kWh = 180,000 J. வலு, நேர அலகுகளைச் சீராகப் பயன்படுத்தவும்.',steps=[('E = Pt = 0.1 kW × 0.5 h = 0.05 kWh.','E = Pt = 0.1 kW × 0.5 h = 0.05 kWh.'),('0.05 × 3,600,000 = 180,000 J.','0.05 × 3,600,000 = 180,000 J.')],lessons=['g11-chapter-10-electric-appliances','g10-chapter-18-work-energy-power']),
        p('ii(d)(I)','physics','Which tank should Suren choose for a cooler bath: black A or white B in sunlight?','சூரிய ஒளியிலுள்ள கருப்பு A, வெள்ளை B தொட்டிகளில் குறைந்த வெப்பநிலை நீரில் குளிக்க சுரேன் எதனைத் தேர்க வேண்டும்?',
          'White tank B, with all other conditions equal. Black A absorbs more solar radiation, so its water becomes warmer.','ஏனைய நிலைகள் சமமெனில் வெள்ளைத் தொட்டி B. கருப்பு A அதிக சூரியக் கதிர்ப்பை உறிஞ்சுவதால் அதன் நீர் அதிகம் சூடாகும்.',lessons=['g11-chapter-09-heat']),
        p('ii(d)(II)','physics','Explain the difference.','வேறுபாட்டை விளக்குக.',
          'Black surfaces absorb radiation more effectively; white surfaces reflect more of the incident radiation.','கருப்பு மேற்பரப்பு கதிர்ப்பை அதிகம் உறிஞ்சும்; வெள்ளை மேற்பரப்பு அதிக கதிர்ப்பைத் தெறிக்கும்.',lessons=['g11-chapter-09-heat']),
        p('iii(a)','physics','Draw the photodiode symbol and identify its terminals.','ஒளி இருவாயியின் குறியீட்டை வரைந்து முனைகளை அடையாளமிடுக.',
          'Use a diode symbol with two arrows pointing towards it (incoming light). The bar is the cathode; the other terminal is the anode. Conventional diode terminal labels are anode + and cathode −; a working photodiode is commonly reverse-biased, with cathode connected + and anode −. Use the model diagram to distinguish terminal names from applied bias.','இருவாயிக் குறியீட்டை நோக்கிய இரண்டு ஒளி அம்புகளை வரைக. கோடுள்ள முனை கதோடு; மற்றது அனோடு. வழக்கமான இருவாயி முனைப் பெயரில் அனோடு +, கதோடு −; பொதுவான ஒளி இருவாயி செயற்பாட்டின் பின்னோக்கிச் சார்பில் கதோடு +, அனோடு −. முனைப் பெயரையும் பிரயோகித்த சார்பையும் வேறுபடுத்துக.',lessons=['g11-chapter-11-electronics']),
        p('iii(b)','physics','Name a compound accepted by this paper for increasing light sensitivity.','இவ்வினாத்தாளில் ஒளியுணர்திறனை அதிகரிக்க ஏற்கப்படும் சேர்வை ஒன்றைப் பெயரிடுக.',
          'Cadmium sulfide (CdS), or cadmium selenide (CdSe), in this historical syllabus question. CdS/CdSe are well known as photoconductive materials; do not assume every modern photodiode uses them.','இவ்வரலாற்றுப் பாடத்திட்ட வினாவில் கட்மியம் சல்பைட்டு (CdS) அல்லது கட்மியம் செலனைட்டு (CdSe). இவை ஒளிக்கடத்திப் பொருள்கள்; எல்லா நவீன ஒளி இருவாயிகளிலும் இவை இருப்பதாகக் கருத வேண்டாம்.',lessons=['g11-chapter-11-electronics']),
        p('iii(c)','physics','Which optical component concentrates light onto the sensitive junction?','ஒளியை உணர்திறனுள்ள சந்திப்பில் குவிக்கும் ஒளியியல் உபகரணம் எது?',
          'A convex/converging lens, which focuses the incident light onto a smaller region.','குவிவு வில்லை: படும் ஒளியைச் சிறிய பகுதியில் குவிக்கும்.',lessons=['g11-chapter-05-geometrical-optics','g11-chapter-11-electronics'])])
